// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/async/time/Period.cfc — do not edit.
/**
 * A date-based amount of time in the ISO-8601 calendar system, such as '2 years, 3 months and 4 days'.
 *
 * This class models a quantity or amount of time in terms of years, months and days. See Duration for the time-based equivalent to this class.
 *
 * Durations and periods differ in their treatment of daylight savings time when added to ZonedDateTime.
 * A Duration will add an exact number of seconds, thus a duration of one day is always exactly 24 hours. By contrast, a Period will add a
 * conceptual day, trying to maintain the local time.
 *
 * For example, consider adding a period of one day and a duration of one day to 18:00 on the evening before a daylight savings gap.
 * The Period will add the conceptual day and result in a ZonedDateTime at 18:00 the following day. By contrast, the Duration will add exactly
 * 24 hours, resulting in a ZonedDateTime at 19:00 the following day (assuming a one hour DST gap).
 *
 * @see https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Period.html
 */
component {
	this.CHRONO_UNIT = new coldbox.system.async.time.DateTimeHelper();
	/**
	 * Initialize to zero date base period
	 *
	 * @years  The years
	 * @months The months
	 * @days   The days
	 */
	coldbox.system.async.time.Period function init( years, months, days ) {}
	/**
	 * Get the native java class we proxy to.
	 *
	 * @return java.time.Period
	 */
	coldbox.system.async.time.Period function getNative() {}
	/**
	 * Checks if the period is negative, excluding zero
	 */
	boolean function isNegative() {}
	/**
	 * Checks if the period is zero length
	 */
	boolean function isZero() {}
	/**
	 * Checks if this period is equal to the specified period.
	 *
	 * @otherPeriod The period to compare against
	 */
	boolean function isEquals( required Period otherPeriod ) {}
	/**
	 * Returns a copy of this duration with the length negated.
	 */
	coldbox.system.async.time.Period function negated() {}
	/**
	 * Returns a copy of this period with the years and months normalized.
	 */
	coldbox.system.async.time.Period function normalized() {}
	/**
	 * Gets the value of the requested unit in seconds by default (days) or years, months, days
	 *
	 * @unit years, months, days
	 *
	 * @throws UnsupportedTemporalTypeException All other units throw an exception.
	 */
	numeric function get( unit ) {}
	/**
	 * Gets the chronology of this period, which is the ISO calendar system.
	 *
	 * @return java.time.chrono.IsoChronology
	 */
	function getChronology() {}
	/**
	 * Gets the number of Days in this period.
	 */
	numeric function getDays() {}
	/**
	 * Gets the number of Months in this period.
	 */
	numeric function getMonths() {}
	/**
	 * Gets the number of Years in this period.
	 */
	numeric function getYears() {}
	/**
	 * Gets the set (array) of units supported by this period.
	 */
	array function getUnits() {}
	/**
	 * Gets the total number of months in this period.
	 */
	numeric function toTotalMonths() {}
	/**
	 * Outputs this period as a String, such as P6Y3M1D.
	 */
	string function toString() {}
	/**
	 * Adds this period to the specified temporal object and return back to you a date/time object
	 *
	 * @target   The date/time object or string to incorporate the period into
	 * @asNative If true, we will give you the java.time.LocalDate object, else a ColdFusion date/time string
	 *
	 * @return The date/time object with the period added to it or a java LocalDate
	 */
	function addTo( required target, boolean asNative ) {}
	/**
	 * Subtracts this period to the specified temporal object and return back to you a date/time object or a Java LocalDate object
	 *
	 * @target   The date/time object or string to incorporate the period into
	 * @asNative If true, we will give you the java.time.LocalDate object, else a ColdFusion date/time string
	 *
	 * @return Return the result either as a date/time string or a java.time.LocalDate object
	 */
	function subtractFrom( required target, boolean asNative ) {}
	/**
	 * Obtains a Duration representing the duration between two temporal date objects.
	 *
	 * This calculates the duration between two temporal objects. If the objects are of different types,
	 * then the duration is calculated based on the type of the first object. For example, if the first argument is a
	 * LocalTime then the second argument is converted to a LocalTime.
	 *
	 * @start The start date/time object
	 * @end   The end date/time object
	 */
	coldbox.system.async.time.Period function between( required start, required end ) {}
	/**
	 * Returns a copy of this period with the specified period subtracted.
	 *
	 * @amountToSubtract The period to subtract
	 */
	coldbox.system.async.time.Period function minus( required Period amountToSubtract ) {}
	coldbox.system.async.time.Period function minusDays( required daysToSubtract ) {}
	coldbox.system.async.time.Period function minusMonths( required monthsToSubtract ) {}
	coldbox.system.async.time.Period function minusYears( required yearsToSubtract ) {}
	coldbox.system.async.time.Period function multipliedBy( required scalar ) {}
	/**
	 * Returns a copy of this period with the specified period added.
	 *
	 * @amountToAdd The period to Add
	 */
	coldbox.system.async.time.Period function plus( required Period amountToAdd ) {}
	coldbox.system.async.time.Period function plusDays( required daysToAdd ) {}
	coldbox.system.async.time.Period function plusMonths( required monthsToAdd ) {}
	coldbox.system.async.time.Period function plusYears( required yearsToAdd ) {}
	/**
	 * Returns a copy of this period with the specified amount of days.
	 *
	 * @days The days
	 */
	coldbox.system.async.time.Period function withDays( required days ) {}
	/**
	 * Returns a copy of this period with the specified amount of months.
	 *
	 * @months The months
	 */
	coldbox.system.async.time.Period function withMonths( required months ) {}
	/**
	 * Returns a copy of this period with the specified amount of years.
	 *
	 * @years The years
	 */
	coldbox.system.async.time.Period function withYears( required years ) {}
	/**
	 * Obtains a Period from a text string such as PnYnMnD.
	 *
	 * This will parse the string produced by toString() which is based on the ISO-8601 period formats PnYnMnD and PnW.
	 *
	 * Examples:
	 *
	 * "P2Y"             -- Period.ofYears(2)
	 * "P3M"             -- Period.ofMonths(3)
	 * "P4W"             -- Period.ofWeeks(4)
	 * "P5D"             -- Period.ofDays(5)
	 * "P1Y2M3D"         -- Period.of(1, 2, 3)
	 * "P1Y2M3W4D"       -- Period.of(1, 2, 25)
	 * "P-1Y2M"          -- Period.of(-1, 2, 0)
	 * "-P1Y2M"          -- Period.of(-1, -2, 0)
	 *
	 * @see  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Period.html#parse(java.lang.CharSequence)
	 * @text The string to parse and build up to a period
	 */
	coldbox.system.async.time.Period function parse( required text ) {}
	/**
	 * Obtains an instance of Period from another period
	 *
	 * @amount The period
	 */
	coldbox.system.async.time.Period function from( required Period amount ) {}
	/**
	 * Obtains a Period representing an amount in the specified arguments
	 *
	 * @years  The years
	 * @months The months
	 * @days   The days
	 */
	coldbox.system.async.time.Period function of( years, months, days ) {}
	/**
	 * Obtains a Period representing a number of days.
	 *
	 * @days The number of days, positive or negative
	 */
	coldbox.system.async.time.Period function ofDays( required days ) {}
	/**
	 * Obtains a Period representing a number of months.
	 *
	 * @months The number of months, positive or negative
	 */
	coldbox.system.async.time.Period function ofMonths( required months ) {}
	/**
	 * Obtains a Period representing a number of weeks.
	 *
	 * @weeks The number of weeks, positive or negative
	 */
	coldbox.system.async.time.Period function ofWeeks( required weeks ) {}
	/**
	 * Obtains a Period representing a number of years.
	 *
	 * @years The number of years, positive or negative
	 */
	coldbox.system.async.time.Period function ofYears( required years ) {}
}
