// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/async/tasks/FutureTask.cfc — do not edit.
/**
 * This is a ColdBox Future Task object modeled and backed by Java's Future interface but with Dynamic Goodness!
 *
 * This is the return of most of the executors when you send runnables to execute
 *
 * @see https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html
 */
component {
	/**
	 * The native future we model: java.util.concurrent.Future
	 */
	property name="native";
	this.$timeUnit = new coldbox.system.async.time.TimeUnit();
	/**
	 * Build the ColdBox Future with the Java native class
	 *
	 * @native The native Future class we are wrapping
	 */
	coldbox.system.async.tasks.FutureTask function init( native ) {}
	/**
	 * If not already completed, completes this Future with a CancellationException.
	 * Dependent Futures that have not already completed will also complete exceptionally, with a CompletionException caused by this CancellationException.
	 *
	 * @return true if this task is now cancelled
	 */
	boolean function cancel( boolean mayInterruptIfRunning ) {}
	/**
	 * Waits if necessary for at most the given time for this future to complete, and then returns its result, if available.
	 * If the result is null, then you can pass the defaultValue argument to return it.
	 *
	 * @timeout      The timeout value to use, defaults to forever
	 * @timeUnit     The time unit to use, available units are: days, hours, microseconds, milliseconds, minutes, nanoseconds, and seconds. The default is milliseconds
	 * @defaultValue If the Future did not produce a value, then it will return this default value.
	 *
	 * @return The result value
	 *
	 * @throws CancellationException , ExecutionException, InterruptedException, TimeoutException
	 */
	any function get( numeric timeout, string timeUnit, defaultValue ) {}
	/**
	 * Returns true if this Future was cancelled before it completed normally.
	 */
	boolean function isCancelled() {}
	/**
	 * Returns true if completed in any fashion: normally, exceptionally, or via cancellation.
	 */
	boolean function isDone() {}
}
