// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/async/tasks/Scheduler.cfc — do not edit.
/**
 * The Async Scheduler is in charge of registering scheduled tasks, starting them, monitoring them and shutting them down if needed.
 *
 * Each scheduler is bound to an scheduled executor class. You can override the executor using the `setExecutor()` method if you so desire.
 * The scheduled executor will be named <code>{name}-scheduler</code>
 *
 * In a ColdBox context, you might have the global scheduler in charge of the global tasks and also 1 per module as well in HMVC fashion.
 * In a ColdBox context, this object will inherit from the ColdBox super type as well dynamically at runtime.
 */
component {
	/**
	 * The name of this scheduler
	 */
	property name="name";
	/**
	 * An ordered struct of all the tasks this scheduler manages
	 */
	property name="tasks" type="struct";
	/**
	 * The Scheduled Executor we are bound to
	 */
	property name="executor";
	/**
	 * The default timezone to use for task executions
	 */
	property name="timezone";
	/**
	 * The default timeout to use when gracefully shutting down this scheduler. Default is 30 seconds.
	 */
	property name ="shutdownTimeout" type ="numeric" default="30";
	/**
	 * If this scheduler has been started or not
	 */
	property name ="started" type ="boolean" default="false";
	/**
	 * When this scheduler was started
	 */
	property name="startedAt" type="date";
	/**
	 * Inet Host
	 */
	property name="inetHost";
	/**
	 * Local Ip
	 */
	property name="localIp";
	/**
	 * Utility Object
	 */
	property name="util";
	variables.util = new coldbox.system.core.util.Util();
	/**
	 * Constructor
	 *
	 * @name         The name of this scheduler
	 * @asyncManager The async manager we are linked to
	 */
	coldbox.system.async.tasks.Scheduler function init( required name, required asyncManager ) {}
	/**
	 * Usually where concrete implementations add their tasks and configs
	 */
	function configure() {}
	/**
	 * Set the timezone for all tasks to use using the timezone string identifier
	 *
	 * @see      https:   //docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZoneId.html
	 * @timezone The timezone string identifier
	 */
	coldbox.system.async.tasks.Scheduler function setTimezone( required timezone ) {}
	/**
	 * Startup this scheduler and all of it's scheduled tasks
	 */
	coldbox.system.async.tasks.Scheduler function startup() {}
	/**
	 * Startup a task in this scheduler.  You can use the task name if registered or the task object itself.
	 * <p>
	 * If the task is disabled, it will not be scheduled.
	 * <p>
	 * If the task is already scheduled, it will not be scheduled again.
	 * <p>
	 * If the task has an error scheduling, it will be marked as such.
	 *
	 * name, task, future, registeredAt, scheduledAt, disabled, error, errorMessage, stacktrace, inetHost, localIp
	 * }
	 *
	 * @task The task name or task object to startup
	 *
	 * @return The task record struct: {
	 */
	struct function startupTask( any task ) {}
	/**
	 * Check if this scheduler has started or not
	 */
	boolean function hasStarted() {}
	/**
	 * Shutdown this scheduler by calling the executor to shutdown and disabling all tasks
	 *
	 * @force   If true, it forces all shutdowns this is usually true when doing reinits
	 * @timeout The timeout in seconds to wait for the shutdown of all tasks, defaults to 30 or whatever you set using the setShutdownTimeout() method
	 */
	coldbox.system.async.tasks.Scheduler function shutdown( boolean force, numeric timeout ) {}
	/**
	 * Restarts a scheduler by shutting it down, clearing out the tasks, calling `configure`, and starting it again.
	 * Useful when loading tasks from a database or other dynamic sources.
	 *
	 * @force   If true, it forces all shutdowns this is usually true when doing reinits
	 * @timeout The timeout in seconds to wait for the shutdown of all tasks, defaults to 30 or whatever you set using the setShutdownTimeout() method
	 */
	public coldbox.system.async.tasks.Scheduler function restart( boolean force, numeric timeout ) {}
	/**
	 * Called before the scheduler is going to be shutdown
	 */
	function onShutdown() {}
	/**
	 * Called after the scheduler has registered all schedules
	 */
	function onStartup() {}
	/**
	 * Called whenever ANY task fails
	 *
	 * @task      The task that got executed
	 * @exception The ColdFusion exception object
	 */
	function onAnyTaskError( required task, required exception ) {}
	/**
	 * Called whenever ANY task succeeds
	 *
	 * @task   The task that got executed
	 * @result The result (if any) that the task produced
	 */
	function onAnyTaskSuccess( required task, result ) {}
	/**
	 * Called before ANY task runs
	 *
	 * @task The task about to be executed
	 */
	function beforeAnyTask( required task ) {}
	/**
	 * Called after ANY task runs
	 *
	 * @task   The task that got executed
	 * @result The result (if any) that the task produced
	 */
	function afterAnyTask( required task, result ) {}
	/**
	 * Clear the tasks                      from this scheduler
	 * BEWARE: This will not stop the tasks    , it will just remove them from the scheduler
	 */
	public coldbox.system.async.tasks.Scheduler function clearTasks() {}
	/**
	 * Register a new task in this scheduler but disable it immediately.  This is useful
	 * when debugging tasks and have the easy ability to disable them.
	 *
	 * @name  The name of this task
	 * @debug Add debugging logs to System out, disabled by default in coldbox.system.async.tasks.ScheduledTask
	 *
	 * @return The registered and disabled Scheduled Task
	 */
	coldbox.system.async.tasks.ScheduledTask function xtask( required name, boolean debug ) {}
	/**
	 * Register a new task in this scheduler that will be executed once the `startup()` method is called on the scheduler
	 * by the framework.
	 * <p>
	 * If you want to start the task immediately, or dynamically, then call the `startTask( Task task)` method on this
	 * scheduler.  This will make sure the task and it's task records are managed by the scheduler.
	 *
	 * @name  The name of this task
	 * @debug Add debugging logs to System out, disabled by default in coldbox.system.async.tasks.ScheduledTask
	 *
	 * @return a ScheduledTask object so you can work on the registration of the task
	 */
	coldbox.system.async.tasks.ScheduledTask function task( required name, boolean debug ) {}
	/**
	 * Builds out a report for all the registered tasks in this scheduler
	 */
	struct function getTaskStats() {}
	/**
	 * Get an array of all the tasks managed by this scheduler
	 */
	array function getRegisteredTasks() {}
	/**
	 * Checks if this scheduler manages a task by name
	 *
	 * @name The name of the task to search
	 */
	boolean function hasTask( required name ) {}
	/**
	 * Get's a task record from the collection by name
	 *
	 * @name The name of the task
	 *
	 * @return The task record struct: { name, task, future, scheduledAt, registeredAt, error, errorMessage, stacktrace }
	 *
	 * @throws UnregisteredTaskException if no task is found under that name
	 */
	struct function getTaskRecord( required name ) {}
	/**
	 * Unregister a task from this scheduler
	 *
	 * @name The name of the task to remove
	 *
	 * @throws UnregisteredTaskException if no task is found under that name
	 */
	coldbox.system.async.tasks.Scheduler function removeTask( required name ) {}
	/**
	 * Get the current thread name
	 */
	private function getThreadName() {}
	/**
	 * Get the current thread java object
	 */
	private function getCurrentThread() {}
	/**
	 * Create a new scheduled executor for this scheduler according to it's name and type
	 */
	private function createSchedulerExecutor() {}
}
