// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/TestBox@af36cddb7b68 system/Assertion.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This is the TestBox Assertion class. It is used to assert test results in a BDD or TDD style.
 */
component {
	/**
	 * Fail assertion
	 *
	 * @message The message to send in the failure
	 * @detail  The detail to add in the exception
	 */
	function fail( message, detail ) {}
	/**
	 * Skip a Test
	 *
	 * @message The message to send in the skip information dialog
	 * @detail  The detail to add in the exception
	 */
	function skip( message, detail ) {}
	/**
	 * Assert that the passed expression is true
	 *
	 * @expression The expression to test
	 * @message    The message to send in the failure
	 */
	function assert( required boolean expression, message ) {}
	/**
	 * Assert something is true
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isTrue( required boolean actual, message ) {}
	/**
	 * Assert something is false
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isFalse( required boolean actual, message ) {}
	/**
	 * Assert something is equal to each other, no case is required
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isEqual( any expected, any actual, message ) {}
	/**
	 * Assert something is not equal to each other, no case is required
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isNotEqual( any expected, any actual, message ) {}
	/**
	 * Assert an object is the same instance as another object
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isSameInstance( required any expected, required any actual, message ) {}
	/**
	 * Assert an object is not the same instance as another object
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isNotSameInstance( required any expected, required any actual, message ) {}
	/**
	 * Assert strings are equal to each other with case.
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isEqualWithCase( string expected, string actual, message ) {}
	/**
	 * Assert something is null
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function null( any actual, message ) {}
	/**
	 * Assert something is not null
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notNull( any actual, message ) {}
	/**
	 * Assert the type of the incoming actual data, it uses the internal ColdFusion isValid() function behind the scenes
	 *
	 * @type    The type to check, valid types are: array, binary, boolean, component, date, time, float, numeric, integer, query, string, struct, url, uuid
	 * @actual  The actual data to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function typeOf( required string type, required any actual, message ) {}
	/**
	 * Assert that is NOT a type of the incoming actual data, it uses the internal ColdFusion isValid() function behind the scenes
	 *
	 * @type    The type to check, valid types are: array, binary, boolean, component, date, time, float, numeric, integer, query, string, struct, url, uuid
	 * @actual  The actual data to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notTypeOf( required string type, required any actual, message ) {}
	/**
	 * Assert that the actual object is of the expected instance type
	 *
	 * @actual   The actual data to check
	 * @typeName The typename to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function instanceOf( required any actual, required string typeName, message ) {}
	/**
	 * Assert that the actual object is NOT of the expected instance type
	 *
	 * @actual   The actual data to check
	 * @typeName The typename to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function notInstanceOf( required any actual, required string typeName, message ) {}
	/**
	 * Assert that the actual data matches the incoming regular expression with no case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function match( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data matches the incoming regular expression with case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function matchWithCase( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data does NOT match the incoming regular expression with case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notMatchWithCase( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data does NOT match the incoming regular expression with no case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notMatch( required string actual, required string regex, message ) {}
	/**
	 * Assert that a given key exists in the passed in struct/object
	 *
	 * @target        The target object/struct
	 * @key           The key to check for existence
	 * @message       The message to send in the failure
	 * @caseSensitive If the key check is case sensitive
	 */
	testbox.system.Assertion function key( required any target, required string key, message, boolean caseSensitive ) {}
	/**
	 * Assert that a given key DOES NOT exist in the passed in struct/object
	 *
	 * @target        The target object/struct
	 * @key           The key to check for existence
	 * @message       The message to send in the failure
	 * @caseSensitive If the key check is case sensitive
	 */
	testbox.system.Assertion function notKey( required any target, required string key, message, boolean caseSensitive ) {}
	/**
	 * Assert that a given key exists in the passed in struct by searching the entire nested structure
	 *
	 * @target  The target object/struct
	 * @key     The key to check for existence anywhere in the nested structure
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function deepKey( required struct target, required string key, message ) {}
	/**
	 * Assert that a given key DOES NOT exists in the passed in struct by searching the entire nested structure
	 *
	 * @target  The target object/struct
	 * @key     The key to check for existence anywhere in the nested structure
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notDeepKey( required struct target, required string key, message ) {}
	/**
	 * Assert the size of a given string, array, structure or query
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @length  The length to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function lengthOf( required any target, required string length, message ) {}
	/**
	 * Assert the size of a given string, array, structure or query
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @length  The length to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notLengthOf( required any target, required string length, message ) {}
	/**
	 * Assert that a a given string, array, structure or query is empty
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isEmpty( required any target, message ) {}
	/**
	 * Assert that a a given string, array, structure or query is not empty
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isNotEmpty( required any target, message ) {}
	/**
	 * Assert that the passed in function will throw an exception
	 *
	 * @target  The target function to execute and check for exceptions
	 * @type    Match this type with the exception thrown
	 * @regex   Match this regex against the message + detail of the exception
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function throws( required any target, type, regex, message ) {}
	/**
	 * Assert that the passed in function will NOT throw an exception, an exception of a specified type or exception message regex
	 *
	 * @target  The target function to execute and check for exceptions
	 * @type    Match this type with the exception thrown
	 * @regex   Match this regex against the message+detail of the exception
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notThrows( required any target, type, regex, message ) {}
	/**
	 * Assert that the passed in actual number or date is expected to be close to it within +/- a passed delta and optional datepart
	 *
	 * @expected The expected number or date
	 * @actual   The actual number or date
	 * @delta    The +/- delta to range it
	 * @datepart If passed in values are dates, then you can use the datepart to evaluate it
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function closeTo( required any expected, required any actual, required any delta, datePart, message ) {}
	/**
	 * Assert that the passed in actual number or date is between the passed in min and max values
	 *
	 * @actual  The actual number or date to evaluate
	 * @min     The expected min number or date
	 * @max     The expected max number or date
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function between( required any actual, required any min, required any max, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with no case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function includes( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function includesWithCase( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument does not exist in the incoming string or array with case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notIncludesWithCase( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with no case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notIncludes( required any target, required any needle, message ) {}
	/**
	 * Assert that the given target string starts with the given needle string with no case-sensitivity
	 *
	 * $assert.startsWith( "hello world", "hello" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function startsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't start with the given needle string with no case-sensitivity
	 *
	 * $assert.notStartsWith( "hello world", "hello" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notStartsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string starts with the given needle string with case-sensitivity
	 *
	 * $assert.startsWith( "hello world", "hello" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function startsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't start with the given needle string with case-sensitivity
	 *
	 * $assert.notStartsWith( "hello world", "hello" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notStartsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string ends with the given needle string with no case-sensitivity
	 *
	 * $assert.endsWith( "hello world", "World" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function endsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't end with the given needle string with no case-sensitivity
	 *
	 * $assert.notEndsWith( "hello world", "peace" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notEndsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string ends with the given needle string with case-sensitivity
	 *
	 * $assert.endsWith( "hello world", "ld" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function endsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't end with the given needle string with case-sensitivity
	 *
	 * $assert.notEndsWith( "hello world", "ld" )
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function notEndsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the actual value is greater than the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isGT( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is greater than or equal the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isGTE( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is less than the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isLT( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is less than or equal the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isLTE( required any actual, required any target, message ) {}
	/**
	 * Get a string name representation of an incoming object.
	 */
	function getStringName( obj ) {}
	/**
	 * Assert something is JSON
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isJSON( required any actual, message ) {}
	/**
	 * Run all given executables and report every assertion failure at once instead of stopping at the first.
	 * Non-assertion exceptions are rethrown immediately.
	 *
	 * @executables An array of closures to execute
	 * @heading     An optional heading to prepend to the aggregated failure message
	 *
	 * @throws TestBox.AssertionFailed — with an aggregated message and detail containing numbered failures
	 */
	testbox.system.Assertion function all( required array executables, string heading ) {}
	/**
	 * Assert the actual value is truthy (not false, 0, empty string, or null).
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isTruthy( any actual, message ) {}
	/**
	 * Assert the actual value is falsy (false, 0, empty string, or null).
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isFalsy( any actual, message ) {}
	/**
	 * Assert that the target contains ALL of the given needles with no case-sensitivity.
	 *
	 * @target  The target string or array
	 * @needles An array of needles that MUST be found
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function includesAll( required any target, required array needles, message ) {}
	/**
	 * Assert that the target contains AT LEAST ONE of the given needles with no case-sensitivity.
	 *
	 * @target  The target string or array
	 * @needles An array of needles, at least one MUST be found
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function includesAny( required any target, required array needles, message ) {}
	/**
	 * Assert that the target contains NONE of the given needles with no case-sensitivity.
	 *
	 * @target  The target string or array
	 * @needles An array of needles that MUST NOT be found
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function includesNone( required any target, required array needles, message ) {}
	/**
	 * Assert that the actual value is a BoxLang Set type.
	 *
	 * @actual  The actual value to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isASet( required any actual, string message ) {}
	/**
	 * Assert that two sets are equal (contain the same elements, order-independent).
	 *
	 * @expected The expected set
	 * @actual   The actual value to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isEqualSet( required any expected, required any actual, string message ) {}
	/**
	 * Assert that the actual set is a subset of the expected set.
	 *
	 * @expected The expected (parent) set
	 * @actual   The actual value to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isSubsetOf( required any expected, required any actual, string message ) {}
	/**
	 * Assert that the actual set is a superset of the expected set.
	 *
	 * @expected The expected (subset) set
	 * @actual   The actual value to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isSupersetOf( required any expected, required any actual, string message ) {}
	/**
	 * Assert that the actual set is disjoint from the expected set (no common elements).
	 *
	 * @expected The expected set to check disjointness against
	 * @actual   The actual value to check
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function isDisjointFrom( required any expected, required any actual, string message ) {}
	/**
	 * Assert that the union of two sets equals the expected set.
	 *
	 * @other    The other set to union with actual
	 * @expected The expected result of the union
	 * @actual   The actual value to check (must be a Set)
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function hasUnion( required any other, required any expected, required any actual, string message ) {}
	/**
	 * Assert that the intersection of two sets equals the expected set.
	 *
	 * @other    The other set to intersect with actual
	 * @expected The expected result of the intersection
	 * @actual   The actual value to check (must be a Set)
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function hasIntersection( required any other, required any expected, required any actual, string message ) {}
	/**
	 * Assert that the difference of two sets equals the expected set.
	 *
	 * @other    The other set to subtract from actual
	 * @expected The expected result of the difference
	 * @actual   The actual value to check (must be a Set)
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function hasDifference( required any other, required any expected, required any actual, string message ) {}
	/**
	 * Assert that the symmetric difference of two sets equals the expected set.
	 *
	 * @other    The other set to compute symmetric difference with actual
	 * @expected The expected result of the symmetric difference
	 * @actual   The actual value to check (must be a Set)
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function hasSymmetricDifference( required any other, required any expected, required any actual, string message ) {}
	/**
	 * Assert that the actual value is a BoxLang Range type.
	 *
	 * @actual  The actual value to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRange( required any actual, string message ) {}
	/**
	 * Assert that a range contains a specific value.
	 *
	 * @actual  The actual range to check
	 * @value   The value to look for in the range
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function rangeContainsValue( required any actual, required any value, string message ) {}
	/**
	 * Assert that a range contains another range.
	 *
	 * @actual   The actual (parent) range to check
	 * @expected The expected (child) range that should be contained within actual
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function rangeContainsRange( required any actual, required any expected, string message ) {}
	/**
	 * Assert that a value is within a range.
	 *
	 * @actual  The actual value to check
	 * @range   The range to check against
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function valueInRange( required any actual, required any range, string message ) {}
	/**
	 * Assert that a range is entirely before another range.
	 *
	 * @actual   The actual (first) range to check
	 * @expected The expected (second) range that should come after actual
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function rangeBeforeRange( required any actual, required any expected, string message ) {}
	/**
	 * Assert that a range is entirely after another range.
	 *
	 * @actual   The actual (second) range to check
	 * @expected The expected (first) range that should come before actual
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function rangeAfterRange( required any actual, required any expected, string message ) {}
	/**
	 * Assert that a range is bounded (has both start and end).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeBounded( required any actual, string message ) {}
	/**
	 * Assert that a range is unbounded (has no endpoints).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeUnbounded( required any actual, string message ) {}
	/**
	 * Assert that a range is half-bounded (has exactly one endpoint).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeHalfBounded( required any actual, string message ) {}
	/**
	 * Assert that a range is iterable (can be used in for/in loops).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeIterable( required any actual, string message ) {}
	/**
	 * Assert that a range is ascending (start < end).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeAscending( required any actual, string message ) {}
	/**
	 * Assert that a range is descending (start > end).
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeDescending( required any actual, string message ) {}
	/**
	 * Assert that a range is empty.
	 *
	 * @actual  The actual range to check
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function isRangeEmpty( required any actual, string message ) {}
	/**
	 * Assert that a range has a specific step value.
	 *
	 * @actual  The actual range to check
	 * @step    The expected step value
	 * @message The message to send in the failure
	 */
	testbox.system.Assertion function rangeHasStep( required any actual, required any step, string message ) {}
	/**
	 * Assert that clamping a value to the range produces the expected result.
	 *
	 * @actual   The actual range to clamp against
	 * @value    The value to clamp
	 * @expected The expected result after clamping
	 * @message  The message to send in the failure
	 */
	testbox.system.Assertion function rangeClampTo( required any actual, required any value, required any expected, string message ) {}
	/**
	 * Build a detailed message for the assert.all() method that includes each failure's index, message, and detail.
	 *
	 * @failures An array of failure objects, each containing 'index', 'message', and 'detail' properties.
	 *
	 * @return A formatted string that lists all failures with their respective details.
	 */
	private string function buildAssertAllDetail( required array failures ) {}
	/**
	 * Determine if the incoming value is falsey ( false, 0, empty string, or null )
	 *
	 * @value The value to evaluate
	 *
	 * @return True if the value is falsey, false otherwise
	 */
	private boolean function isFalseyValue( any value ) {}
	/**
	 * Temporary BoxSet detector until BoxLang ships an isBoxSet() BIF.
	 *
	 * @target The value to evaluate
	 *
	 * @return True when the value is a BoxSet instance
	 */
	private boolean function isThisASet( required any target ) {}
	/**
	 * Recursively compare two values for equality, with special handling for various types like queries, arrays, structs, etc.
	 *
	 * @expected The expected value
	 * @actual   The actual value
	 *
	 * @return True if the values are considered equal, false otherwise
	 */
	private boolean function equalize( any expected, any actual ) {}
	/**
	 * Returns the length of the target based on its type
	 *
	 * @target The target to get the length of
	 */
	private function getTargetLength( required any target ) {}
	/**
	 * Get the identity hash code for the target.
	 *
	 * @target The target to get the hash code for
	 */
	private function getIdentityHashCode( required any target ) {}
	/**
	 * Normalize the target to a struct if possible.
	 *
	 * @target The target to normalize
	 *
	 * @throws InvalidTargetType - If we can normalize it to a struct
	 */
	private function normalizeToStruct( any target ) {}
	/**
	 * Resolve a path expression in the target data structure.
	 * Uses BoxLang's native dataNavigate() BIF.
	 */
	any function resolvePath( required any target, required string path ) {}
	/**
	 * Resolve a path after normalizing supported target types.
	 */
	private array function getPathResults( required any target, required string path ) {}
	/**
	 * Check if all path results satisfy a predicate.
	 */
	private boolean function allPathResultsMatch( required array results, required function predicate ) {}
	/**
	 * Check if any path result satisfies a predicate.
	 */
	private boolean function anyPathResultMatches( required array results, required function predicate ) {}
	/**
	 * Check if a path exists in the target data structure.
	 *
	 * @target  The target object/struct/array
	 * @path    The path string (e.g., "a.b.c", "users[0].name")
	 * @message The message to send on failure
	 */
	testbox.system.Assertion function toPath( required any target, required string path, message ) {}
	/**
	 * Check if a path does NOT exist in the target data structure.
	 *
	 * @target  The target object/struct/array
	 * @path    The path string (e.g., "a.b.c", "users[0].name")
	 * @message The message to send on failure
	 */
	testbox.system.Assertion function notToPath( required any target, required string path, message ) {}
	/**
	 * Check if the value at a path equals the expected value.
	 *
	 * @target   The target object/struct/array
	 * @path     The path string (e.g., "a.b.c", "users[0].name")
	 * @expected The expected value at the path
	 * @message  The message to send on failure
	 */
	testbox.system.Assertion function toPathValue( required any target, required string path, required any expected, message ) {}
	/**
	 * Check if the value at a path does NOT equal the expected value.
	 */
	testbox.system.Assertion function notToPathValue( required any target, required string path, required any expected, message ) {}
	/**
	 * Check if the value at a path is of the expected type.
	 *
	 * @target  The target object/struct/array
	 * @path    The path string (e.g., "a.b.c", "users[0].name")
	 * @type    The expected type string (e.g., "string", "numeric", "array", "struct")
	 * @message The message to send on failure
	 */
	testbox.system.Assertion function toPathType( required any target, required string path, required string type, message ) {}
	/**
	 * Check if the value at a path does NOT match the expected type.
	 */
	testbox.system.Assertion function notToPathType( required any target, required string path, required string type, message ) {}
	/**
	 * Check if the value at a path satisfies a predicate closure.
	 *
	 * @target    The target object/struct/array
	 * @path      The path string (e.g., "a.b.c", "users[0].name")
	 * @predicate A closure that takes the path value and returns true/false
	 * @message   The message to send on failure
	 */
	testbox.system.Assertion function toPathSatisfying( required any target, required string path, required function predicate, message ) {}
	/**
	 * Check if the value at a path does NOT satisfy a predicate closure.
	 */
	testbox.system.Assertion function notToPathSatisfying( required any target, required string path, required function predicate, message ) {}
	/**
	 * Get the type name of a value for comparison.
	 */
	string function _getTypeName( required any target ) {}
	/**
	 * Check if an actual type matches the expected type (with normalization).
	 */
	boolean function _typeMatches( required string actualType, required string expectedType ) {}
	/**
	 * Compare two BoxSet instances using BoxSet's normalized, order-independent equality rules.
	 *
	 * @expected The expected set
	 * @actual   The actual set
	 *
	 * @return True if both sets contain the same values
	 */
	private boolean function setsAreEqual( required any expected, required any actual ) {}
	private string function limitString( required string str, required numeric limit, string end ) {}
}
