// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/TestBox@af36cddb7b68 system/BaseSpec.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This is a base spec object that is used to test XUnit and BDD style specification methods
 */
component {
	this.$assert = new testbox.system.Assertion();
	variables.$assert = new testbox.system.Assertion();
	variables.$utility = new testbox.system.util.Util();
	variables.$env = new testbox.system.util.Env();
	this.$mockbox = new testbox.system.MockBox();
	variables.$mockbox = new testbox.system.MockBox();
	/**
	 * Constructor
	 */
	remote testbox.system.BaseSpec function init() {}
	/**
	 * Expect an exception from the testing spec
	 *
	 * @type  The type to expect
	 * @regex Optional exception message regular expression to match, by default it matches .*
	 */
	testbox.system.BaseSpec function expectedException( type, regex ) {}
	/**
	 * Assert that the passed expression is true
	 *
	 * @facade
	 */
	function assert( required expression, message ) {}
	/**
	 * Fail an assertion
	 *
	 * @facade
	 */
	function fail( message, detail ) {}
	/**
	 * Run all given executables and report every assertion failure at once instead of stopping at the first.
	 * Delegates to the internal $assert.all() method.
	 *
	 * @executables An array of closures to execute
	 * @heading     An optional heading to prepend to the aggregated failure message
	 * @facade
	 *
	 * @throws TestBox.AssertionFailed
	 */
	function assertAll( required array executables, string heading ) {}
	/**
	 * Skip a test
	 *
	 * @message The message to send in the skip information dialog
	 * @detail  The detail to add in the exception
	 */
	function skip( message, detail ) {}
	/**
	 * This function is used for BDD test suites to store the beforeEach() function to execute for a test suite group
	 *
	 * @body The closure function
	 * @data Data bindings
	 */
	testbox.system.BaseSpec function beforeEach( required any body, struct data ) {}
	/**
	 * This function is used for BDD test suites to store the afterEach() function to execute for a test suite group
	 *
	 * @body The closure function
	 * @data Data bindings
	 */
	testbox.system.BaseSpec function afterEach( required any body, struct data ) {}
	/**
	 * This is used to surround a spec with your own closure code to provide a nice around decoration advice
	 *
	 * @body The closure function
	 * @data Data bindings
	 */
	testbox.system.BaseSpec function aroundEach( required any body, struct data ) {}
	/**
	 * Focused Describe, only this should run
	 *
	 * @title    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function fdescribe( required string title, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The title is usually what you are testing or grouping of tests.
	 * The body is the function that implements the suite.
	 *
	 * @title    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 * @focused  A flag that tells TestBox to only run this suite and no other
	 */
	testbox.system.BaseSpec function describe( required string title, required any body, any labels, boolean asyncAll, any skip, boolean focused ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The story is an alias for describe usually use when you are writing using Gherkin-esque language
	 * The body is the function that implements the suite.
	 *
	 * @story    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function story( required string story, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A focused Story
	 *
	 * @story    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function fstory( required string story, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The feature is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function feature( required string feature, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A Focused Feature
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function ffeature( required string feature, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The given is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function given( required string given, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A focused given
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function fgiven( required string given, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The scenario is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function scenario( required string scenario, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A focused scenario
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function fscenario( required string scenario, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The when is an alias for scenario usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function when( required string when, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A focused when
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function fwhen( required string when, required any body, any labels, boolean asyncAll, any skip ) {}
	/**
	 * A focused `it` where only focused it's are executed
	 *
	 * @title  The title of this spec
	 * @body   The closure that represents the test
	 * @labels The list or array of labels this spec belongs to
	 * @skip   A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data   A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 */
	any function fit( required string title, required any body, any labels, any skip, struct data ) {}
	/**
	 * The it() function describes a spec or a test in TestBox.  The body argument is the closure that implements
	 * the test which usually contains one or more expectations that test the state of the code under test.
	 *
	 * @title   The title of this spec
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @skip    A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 *
	 * @throws TestBox.InvalidBody    If the body is not a closure
	 * @throws TestBox.InvalidContext If the spec is not defined within a suite
	 */
	testbox.system.BaseSpec function it( required string title, required any body, any labels, any skip, struct data, boolean focused ) {}
	/**
	 * An alias to the it() function to provide a more natural language for BDD.
	 *
	 * @title   The title of this test
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @skip    A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 */
	any function test( required string title, required any body, any labels, any skip, struct data, boolean focused ) {}
	/**
	 * A focused alias to the fit() function to provide a more natural language for BDD.
	 *
	 * @then    The title of this spec
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @skip    A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 */
	any function ftest( required string title, required any body, any labels, any skip, struct data, boolean focused ) {}
	/**
	 * The then() function describes a spec or a test in TestBox and is an alias for it.  The body argument is the closure that implements
	 * the test which usually contains one or more expectations that test the state of the code under test.
	 *
	 * @then    The title of this spec
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @skip    A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 */
	any function then( required string then, required any body, any labels, any skip, struct data, boolean focused ) {}
	/**
	 * A focused then
	 *
	 * @then    The title of this spec
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @skip    A flag or a closure that tells TestBox to skip this spec test from testing if true. If this is a closure it must return boolean.
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 */
	any function fthen( required string then, required any body, any labels, any skip, struct data, boolean focused ) {}
	/**
	 * This is a convenience method that makes sure the test suite is skipped from execution
	 *
	 * @title    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 */
	any function xdescribe( required string title, required any body, any labels, boolean asyncAll ) {}
	/**
	 * This is a convenience method that makes sure the test spec is skipped from execution
	 *
	 * @title  The title of this spec
	 * @body   The closure that represents the test
	 * @labels The list or array of labels this spec belongs to
	 * @data   A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 */
	any function xit( required string title, required any body, any labels, struct data ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The story is an alias for describe usually use when you are writing using Gherkin-esque language
	 * The body is the function that implements the suite.
	 *
	 * @story    The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function xstory( required string story, required any body, any labels, boolean asyncAll ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The feature is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function xfeature( required string feature, required any body, any labels, boolean asyncAll ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The given is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function xgiven( required string given, required any body, any labels, boolean asyncAll ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The scenario is an alias for describe usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function xscenario( required string scenario, required any body, any labels, boolean asyncAll ) {}
	/**
	 * The way to describe BDD test suites in TestBox. The when is an alias for scenario usually use when you are writing in a Given-When-Then style
	 * The body is the function that implements the suite.
	 *
	 * @feature  The name of this test suite
	 * @body     The closure that represents the test suite
	 * @labels   The list or array of labels this suite group belongs to
	 * @asyncAll If you want to parallelize the execution of the defined specs in this suite group.
	 * @skip     A flag or a closure that tells TestBox to skip this suite group from testing if true. If this is a closure it must return boolean.
	 */
	any function xwhen( required string when, required any body, any labels, boolean asyncAll ) {}
	/**
	 * This is a convenience method that makes sure the test spec is skipped from execution
	 *
	 * @title  The title of this spec
	 * @body   The closure that represents the test
	 * @labels The list or array of labels this spec belongs to
	 * @data   A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 */
	any function xthen( required string then, required any body, any labels, struct data ) {}
	/**
	 * This is a convenience method that makes sure the test spec is skipped from execution
	 *
	 * @title   The title of this spec
	 * @body    The closure that represents the test
	 * @labels  The list or array of labels this spec belongs to
	 * @data    A struct of data you would like to bind into the spec so it can be later passed into the executing body function
	 * @focused A flag that tells TestBox to only run this spec and no other
	 */
	any function xtest( required string title, required any body, any labels, struct data, boolean focused ) {}
	/**
	 * Start an expectation expression. This returns an instance of Expectation so you can work with its matchers.
	 *
	 * @actual The actual value, it is not required as it can be null.
	 */
	testbox.system.Expectation function expect( any actual ) {}
	/**
	 * Start a collection expectation expression. This returns an instance of CollectionExpectation
	 * so you can work with its collection-unrolling matches (delegating to Expectation).
	 *
	 * @actual The actual value, it should be an array or a struct.
	 */
	testbox.system.CollectionExpectation function expectAll( required any actual ) {}
	/**
	 * Start a collection expectation expression that passes when at least one element passes the chained matcher.
	 * Returns an instance of CollectionExpectation in "any" mode.
	 *
	 * @actual The actual value, it should be an array or a struct.
	 */
	testbox.system.CollectionExpectation function expectAny( required any actual ) {}
	/**
	 * Start a collection expectation expression that passes when a bounded number of elements pass.
	 * Returns an instance of CollectionExpectation in "some" mode.
	 *
	 * @actual The actual value, it should be an array or a struct.
	 * @min    The minimum number of elements that must pass, defaults to 1
	 * @max    The maximum number of elements that may pass, 0 means no upper bound
	 */
	testbox.system.CollectionExpectation function expectSome( required any actual, numeric min, numeric max ) {}
	/**
	 * Start a collection expectation expression that passes when zero elements pass the chained matcher.
	 * Returns an instance of CollectionExpectation in "none" mode.
	 *
	 * @actual The actual value, it should be an array or a struct.
	 */
	testbox.system.CollectionExpectation function expectNone( required any actual ) {}
	/**
	 * Add custom matchers to your expectations
	 *
	 * @matchers The structure of custom matcher functions to register or a path or instance of a class containing all the matcher functions to register
	 */
	testbox.system.BaseSpec function addMatchers( required any matchers ) {}
	/**
	 * Add custom assertions to the $assert object
	 *
	 * @assertions The structure of custom assertion functions to register or a path or instance of a class containing all the assertion functions to register
	 */
	testbox.system.BaseSpec function addAssertions( required any assertions ) {}
	/**
	 * Run a test remotely, only useful if the spec inherits from this class. Useful for remote executions.
	 *
	 * @testSuites A list or array of suite names that are the ones that will be executed ONLY!
	 * @testSpecs  A list or array of test names that are the ones that will be executed ONLY!
	 * @reporter   The type of reporter to run the test with
	 * @labels     A list or array of labels to apply to the testing.
	 */
	remote function runRemote( string testSpecs, string testSuites, string reporter, string labels ) {}
	/**
	 * Run a BDD test in this target
	 *
	 * @spec        The spec definition to test
	 * @suite       The suite definition this spec belongs to
	 * @testResults The testing results object
	 * @suiteStats  The suite stats that the incoming spec definition belongs to
	 * @runner      The runner calling this BDD test
	 */
	testbox.system.BaseSpec function runSpec( required spec, required suite, required testResults, required suiteStats, required runner ) {}
	/**
	 * Execute the before each closures in order for a suite and spec
	 *
	 * @suite The suite definition
	 * @spec  The spec definition
	 */
	testbox.system.BaseSpec function runBeforeEachClosures( required suite, required spec ) {}
	/**
	 * Execute the around each closures in order for a suite and spec
	 *
	 * @suite The suite definition
	 * @spec  The spec definition
	 */
	testbox.system.BaseSpec function runAroundEachClosures( required suite, required spec ) {}
	/**
	 * Generates a specs stack for executions
	 *
	 * @closures The array of closures data to build
	 * @suite    The target suite
	 * @spec     The target spec
	 */
	function generateAroundEachClosuresStack( array closures, required suite, required spec, closureIndex ) {}
	/**
	 * Execute the after each closures in order for a suite and spec
	 *
	 * @suite The suite definition
	 * @spec  The spec definition
	 */
	testbox.system.BaseSpec function runAfterEachClosures( required suite, required spec ) {}
	/**
	 * Runs a xUnit style test method in this target
	 *
	 * @spec        The spec definition to test
	 * @testResults The testing results object
	 * @suiteStats  The suite stats that the incoming spec definition belongs to
	 * @runner      The runner calling this BDD test
	 */
	testbox.system.BaseSpec function runTestMethod( required spec, required testResults, required suiteStats, required runner ) {}
	/**
	 * Send some information to the console via writedump( output="console" )
	 *
	 * @var      The data to send
	 * @top      Apply a top to the dump, by default it does 9999 levels
	 * @showUDFs Show UDFs in the dump, by default it does not
	 * @label    A label to add to the console output
	 */
	testbox.system.BaseSpec function console( required var, numeric top, boolean showUDFs, string label ) {}
	/**
	 * Debug some information into the TestBox debugger array buffer
	 *
	 * @var      The data to debug
	 * @label    The label to add to the debug entry
	 * @deepCopy By default we do not duplicate the incoming information, but you can :)
	 * @top      The top numeric number to dump on the screen in the report, defaults to 999
	 */
	testbox.system.BaseSpec function debug( any var, string label, boolean deepCopy, numeric top, boolean showUDFs ) {}
	/**
	 * Clear the debug array buffer
	 */
	testbox.system.BaseSpec function clearDebugBuffer() {}
	/**
	 * Get the debug array buffer from scope
	 */
	array function getDebugBuffer() {}
	/**
	 * Write some output to the ColdFusion output buffer
	 */
	testbox.system.BaseSpec function print( required message ) {}
	/**
	 * Write some output to the ColdFusion output buffer using a <br> attached
	 */
	any function println( required message ) {}
	/**
	 * Make a private method on a class public with or without a new name and returns the target object
	 *
	 * @target  The target object to expose the method
	 * @method  The private method to expose
	 * @newName If passed, it will expose the method with this name, else just uses the same name
	 */
	any function makePublic( required any target, required string method, string newName ) {}
	/**
	 * Get a private property
	 *
	 * @target       The target to get a property from
	 * @name         The name of the property to retrieve
	 * @scope        The scope to get it from, defaults to 'variables' scope
	 * @defaultValue A default value if the property does not exist
	 */
	any function getProperty( required target, required name, scope, defaultValue ) {}
	/**
	 * First line are the query columns separated by commas. Then do a consequent rows separated by line breaks separated by | to denote columns.
	 */
	function querySim( required queryData ) {}
	/**
	 * Use cbMockData to mock whatever data you want by executing the `mock()` function in cbMockData
	 *
	 * @return The mock data you desire sir!
	 */
	function mockData() {}
	/**
	 * Get the MockData Class object
	 *
	 * @return testbox.system.modules.cbMockData.models.MockData
	 */
	function getCBMockData() {}
	/**
	 * Get the TestBox utility object
	 *
	 * @return testbox.system.util.Util
	 */
	testbox.system.util.Util function getUtility() {}
	/**
	 * Get the TestBox Env  object
	 *
	 * @return testbox.system.util.Env
	 */
	testbox.system.util.Env function getEnv() {}
	/**
	 * Get a reference to the MockBox Engine
	 *
	 * @generationPath The path to generate the mocks if passed, else uses default location.
	 *
	 * @return testbox.system.MockBox
	 */
	testbox.system.MockBox function getMockBox( string generationPath ) {}
	/**
	 * Create an empty mock
	 *
	 * @className   The class name of the object to mock. The mock factory will instantiate it for you
	 * @object      The object to mock, already instantiated
	 * @callLogging Add method call logging for all mocked methods. Defaults to true
	 */
	function createEmptyMock( string className, any object, boolean callLogging ) {}
	/**
	 * Create a mock with or without clearing implementations, usually not clearing means you want to build object spies
	 *
	 * @className    The class name of the object to mock. The mock factory will instantiate it for you
	 * @object       The object to mock, already instantiated
	 * @clearMethods If true, all methods in the target mock object will be removed. You can then mock only the methods that you want to mock. Defaults to false
	 * @callLogging  Add method call logging for all mocked methods. Defaults to true
	 */
	function createMock( string className, any object, boolean clearMethods ) {}
	/**
	 * Prepares an already instantiated object to act as a mock for spying and much more
	 *
	 * @object      The object to mock, already instantiated
	 * @callLogging Add method call logging for all mocked methods. Defaults to true
	 */
	function prepareMock( any object, boolean callLogging ) {}
	/**
	 * Create an empty stub object that you can use for mocking
	 *
	 * @callLogging Add method call logging for all mocked methods. Defaults to true
	 * @extends     Make the stub extend from certain class
	 * @implements  Make the stub adhere to an interface
	 */
	function createStub( boolean callLogging, string extends, string implements ) {}
	function closureStub() {}
	function aroundStub( spec ) {}
	/**
	 * Check if an expected exception is defined
	 */
	boolean function hasExpectedException( required specName, required runner ) {}
	/**
	 * Check if the incoming exception is expected or not.
	 */
	boolean function isExpectedException( required exception, required specName, required runner ) {}
	/**
	 * ------------------------------------------------------------------
	 * Environment Skipping Helpers
	 * ------------------------------------------------------------------
	 */
	function isAdobe() {}
	function isLucee() {}
	function isBoxLang() {}
	function isWindows() {}
	function isLinux() {}
	function isMac() {}
	/**
	 * On missing method handler for dynamic assertions
	 *
	 * @missingMethodName      The name of the missing method
	 * @missingMethodArguments The arguments passed to the missing method
	 */
	function onMissingMethod( missingMethodName, missingMethodArguments ) {}
}
