// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/TestBox@af36cddb7b68 system/CollectionExpectation.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * The CollectionExpectation holds a collection and behaves like an expectation
 * that automatically unrolls the collection to verify elements according to a mode.
 *
 * Modes:
 * - "all"  : every element must pass the chained matcher (default)
 * - "any"  : at least one element must pass
 * - "some" : a bounded number of elements must pass
 * - "none" : zero elements may pass
 */
component {
	property name="actual";
	property name="spec";
	property name="assert";
	property name="mode" default="all";
	property name="min" default="1";
	property name="max" default="0";
	/**
	 * Constructor
	 *
	 * @spec       The target spec
	 * @assertions The assertions library
	 * @collection The collection target
	 * @mode       The evaluation mode: all, any, some, none
	 * @min        The minimum pass count for "some" mode
	 * @max        The maximum pass count for "some" mode, 0 means unbounded
	 */
	testbox.system.CollectionExpectation function init( required spec, required any assertions, required collection, mode, numeric min, numeric max ) {}
	testbox.system.CollectionExpectation function onMissingMethod( string missingMethodName, any missingMethodArguments ) {}
	/**
	 * PRIVATE ********************************************
	 */
	private struct function tryElement( required index, required element, required missingMethodName, required missingMethodArguments ) {}
	private function evaluateResults( required numeric total, required numeric passCount, required array failDetails, required string methodName ) {}
	private string function buildFailureSummary( required numeric total, required numeric passCount, required array failDetails ) {}
}
