// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/TestBox@af36cddb7b68 system/MockBox.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * MockBox is in charge of all kinds of software mocking abilities.
 */
component {
	property name="mockGenerator";
	property name="generationPath";
	/**
	 * Create an instance of MockBox
	 *
	 * @generationPath The mocking generation relative path.  If not defined, then the factory will use its internal tmp path. Just make sure that this folder is accessible from an include.
	 */
	testbox.system.MockBox function init( generationPath ) {}
	/**
	 * Create an empty mock object. By empty we mean we remove all methods so you can mock them.
	 *
	 * @className   The class name of the object to mock. The mock factory will instantiate it for you
	 * @object      The object to mock, already instantiated
	 * @callLogging Add method call logging for all mocked methods. Defaults to true
	 *
	 * @return The object being mocked
	 */
	function createEmptyMock( className, object, boolean callLogging ) {}
	/**
	 * Create a mock object or prepares an object to act as a mock for spying.
	 *
	 * @className    The class name of the object to mock. The mock factory will instantiate it for you
	 * @object       The object to mock, already instantiated
	 * @clearMethods If true, all methods in the target mock object will be removed. You can then mock only the methods that you want to mock. Defaults to false
	 * @callLogging  Add method call logging for all mocked methods. Defaults to true
	 *
	 * @return The object being mocked
	 */
	function createMock( className, object, clearMethods, callLogging ) {}
	/**
	 * Prepares an already instantiated object to act as a mock for spying and much more.
	 *
	 * @object      The already instantiated object to prepare for mocking
	 * @callLogging Add method call logging for all mocked methods
	 *
	 * @return The object being prepared for mocking
	 */
	function prepareMock( required object, callLogging ) {}
	/**
	 * Create an empty stub object that you can use for mocking.
	 *
	 * @callLogging Add method call logging for all mocked methods
	 * @extends     Make the stub extend from certain class
	 * @implements  Make the stub adhere to an interface
	 *
	 * @return The stub object
	 */
	function createStub( callLogging, extends, implements ) {}
	/**
	 * Mock a property inside of an object in any scope. Injected as = $property()
	 *
	 * @propertyName  The name of the property to mock
	 * @propertyScope The scope where the property lives in. By default we will use the variables scope.
	 * @mock          The object or data to inject
	 *
	 * @return The object being mocked
	 */
	testbox.system.MockBox function $property( required propertyName, propertyScope, required mock ) {}
	/**
	 * Gets an internal mocked object property
	 *
	 * @name         The name of the property to retrieve.
	 * @scope        The scope to which to retrieve the property from. Defaults to 'variables' scope.
	 * @defaultValue Default value to return if property does not exist
	 *
	 * @return The value of the property or the default value if the property does not exist
	 */
	function $getProperty( required name, scope, defaultValue ) {}
	/**
	 * I return the number of times the specified mock object's methods have been called or a specific method has been called.  If the mock method has not been defined the results is a -1
	 *
	 * @methodName Name of the method to get the total made calls from. If not passed, then we count all methods in this mock object
	 *
	 * @return The number of times the specified mock object's method or all methods have been called
	 */
	numeric function $count( methodName ) {}
	/**
	 * Assert how many calls have been made to the mock or a specific mock method: Injected as $verifyCallCount() and $times()
	 *
	 * @count      The number of calls to assert
	 * @methodName Name of the method to verify the calls from, if not passed it asserts all mocked method calls
	 *
	 * @return True if the number of calls have been made to the mock or a specific mock method
	 */
	boolean function $times( required count, methodName ) {}
	/**
	 * Assert that no interactions have been made to the mock or a specific mock method: Alias to $times(0). Injected as $never()
	 *
	 * @methodName Name of the method to verify the calls from
	 *
	 * @return True if no interactions have been made to the mock or a specific mock method
	 */
	boolean function $never( methodName ) {}
	/**
	 * Assert that at least a certain number of calls have been made on the mock or a specific mock method. Injected as $atLeast()
	 *
	 * @minNumberOfInvocations The min number of calls to assert
	 * @methodName             Name of the method to verify the calls from, if blank, from the entire mock
	 *
	 * @return True if at least a certain number of calls have been made on the mock or a specific mock method
	 */
	boolean function $atLeast( required minNumberOfInvocations, methodName ) {}
	/**
	 * Assert that only 1 call has been made on the mock or a specific mock method. Injected as $once()
	 *
	 * @methodName Name of the method to verify the calls from, if blank, from the entire mock
	 *
	 * @return True if only 1 call has been made on the mock or a specific mock method
	 */
	boolean function $once( methodName ) {}
	/**
	 * Assert that at most a certain number of calls have been made on the mock or a specific mock method. Injected as $atMost()
	 *
	 * @maxNumberOfInvocations The max number of calls to assert
	 * @methodName             Name of the method to verify the calls from, if blank, from the entire mock
	 *
	 * @return True if at most a certain number of calls have been made on the mock or a specific mock method
	 */
	boolean function $atMost( required maxNumberOfInvocations, methodName ) {}
	/**
	 * Use this method to mock more than 1 result as passed in arguments.  Can only be called when chained to a $() or $().$args() call.  Results will be recycled on a multiple of their lengths according to how many times they are called, simulating a state-machine algorithm. Injected as: $results()
	 */
	testbox.system.MockBox function $results() {}
	/**
	 * Use this method to mock more than 1 result as passed in arguments.  Can only be called when chained to a $() or $().$args() call. Results will be determined by the callback sent in. Basically the method will call this callback and return its results)
	 *
	 * @target The UDF or closure to execute as a callback
	 */
	testbox.system.MockBox function $callback( required target ) {}
	/**
	 * Use this method to return an exception when called.  Can only be called when chained to a $() or $().$args() call.  Results will be recycled on a multiple of their lengths according to how many times they are called, simulating a state-machine algorithm. Injected as: $throws()
	 */
	function $throws() {}
	/**
	 * Use this method to mock specific arguments when calling a mocked method.  Can only be called when chained to a $() call.  If a method is called with arguments and no match, it defaults to the base results defined. Injected as: $args()
	 */
	testbox.system.MockBox function $args() {}
	/**
	 * Mock a method, simple but magical. Injected as: $()
	 *
	 * @method             The method you want to mock
	 * @preserveReturnType Preserve the return type of the method
	 * @throwException     Throw an exception if the method is called
	 * @throwType          The type of exception to throw
	 * @throwDetail        The detail of the exception to throw
	 * @throwMessage       The message of the exception to throw
	 * @throwErrorCode     The error code of the exception to throw
	 * @callOriginal       Call the original method
	 * @preserveArguments  Preserve the arguments of the method
	 * @callback           The callback to execute
	 *
	 * @return The results it must return, if not passed it returns void or you will have to do the mockResults() chain
	 * @return The results it must return, if not passed it returns void or you will have to do the mockResults() chain
	 */
	testbox.system.MockBox function $( required method, any returns, boolean preserveReturnType, boolean throwException, string throwType, string throwDetail, string throwMessage, string throwErrorCode, boolean callOriginal, boolean preserveArguments, any callback ) {}
	/**
	 * Spy on a Method. Like mocking but keeping the original code.
	 *
	 * @method The method you want to mock or spy on
	 */
	function $spy( required method ) {}
	/**
	 * Retrieve the method call logger structures. Injected as: $callLog()
	 */
	struct function $callLog() {}
	/**
	 * Debugging method for MockBox enabled mocks/stubs, useful to find out things about your mocks. Injected as $debug()
	 */
	struct function $debug() {}
	/**
	 * Reset all mock counters and logs on the targeted mock. Injected as $reset
	 */
	testbox.system.MockBox function $reset() {}
	/**
	 * Accepts a specifically formatted chunk of text, and returns it as a query object.
	 * v2 rewrite by Jamie Jackson
	 * v3 rewrite by James Davis
	 *
	 * @queryData Specifically format chunk of text to convert to a query. (Required)
	 * @author    Bert Dawson (bert@redbanner.com)
	 * @version   3, June 25, 2013
	 *
	 * @return Returns a query object.
	 */
	Query function querySim( required queryData ) {}
	/**
	 * Normalize arguments for serialization
	 *
	 * @args The arguments to normalize
	 */
	function normalizeArguments( required args ) {}
	/**
	 * Deterministic string representation of a value for argument hashing.
	 * Struct keys are sorted so iteration order does not affect the hash. Composite
	 * values are JSON-encoded (rather than hand-joined with bare delimiters) so that
	 * delimiter-like characters inside string values can't cause two structurally
	 * different arguments to normalize to the same string.
	 *
	 * @value The value to serialize
	 */
	private function normalizeValue( required any value ) {}
	/**
	 * Decorate a mock object with all the necessary methods and properties
	 *
	 * @target The object to decorate
	 */
	private function decorateMock( required target ) {}
	/**
	 * Get the util object
	 */
	private testbox.system.util.Util function getUtil() {}
}
