// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/migrator/ViewDefinition.cfc — do not edit.
component extends="wheels.migrator.Base" {
	public wheels.migrator.ViewDefinition function init( required any adapter, required string name ) {}
	/**
	 * Select statement to build view.
	 */
	public wheels.migrator.ViewDefinition function selectStatement( required string sql ) {}
	/**
	 * Creates the table in the database.
	 */
	public void function create() {}
}
