// Generated by cmd/cfstubgen from https://github.com/MasaCMS/MasaCMS@696383140578 mura/MuraScope.cfc — do not edit.
/**
 * This provides a utility to access all Mura functionality
 */
component extends="mura.MasaScope" {
	public function init( data ) {}
	function setCustomMuraScopeKey( name, value ) {}
}
