// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/Bootstrap.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * Loads the framwork into memory and provides a ColdBox application.
 *
 * @author Luis Majano <lmajano@ortussolutions.com>
 */
component {
	property name="COLDBOX_CONFIG_FILE";
	property name="COLDBOX_APP_ROOT_PATH";
	property name="COLDBOX_APP_KEY";
	property name="COLDBOX_APP_MAPPING";
	property name="COLDBOX_WEB_MAPPING";
	property name="lockTimeout";
	property name="appHash" default="#getBaseTemplatePath()#";
	property name="COLDBOX_FAIL_FAST";
	/**
	 * Constructor, called by your Application CFC
	 *
	 * @COLDBOX_CONFIG_FILE   The override location of the config file
	 * @COLDBOX_APP_ROOT_PATH The location of the app on disk
	 * @COLDBOX_APP_KEY       The key used in application scope for this application
	 * @COLDBOX_APP_MAPPING   The application mapping where the CFML assets are located
	 * @COLDBOX_FAIL_FAST     By default if an app is reiniting and a request hits it, we will fail fast with a message. This can be a boolean indicator or a closure.
	 * @COLDBOX_WEB_MAPPING   The web mapping where the web root is located, usually this is empty unless in a subdirectory
	 */
	coldbox.system.Bootstrap function init( required string COLDBOX_CONFIG_FILE, required string COLDBOX_APP_ROOT_PATH, string COLDBOX_APP_KEY, string COLDBOX_APP_MAPPING, any COLDBOX_FAIL_FAST, string COLDBOX_WEB_MAPPING ) {}
	/**
	 * Loads the framework into application scope and executes app start procedures
	 *
	 * @throws InvalidColdBoxMapping
	 */
	coldbox.system.Bootstrap function loadColdBox() {}
	/**
	 * Request Reload procedures
	 */
	coldbox.system.Bootstrap function reloadChecks() {}
	/**
	 * Process a ColdBox Request
	 */
	function processColdBoxRequest() {}
	/**
	 * Verify if a reinit is sent
	 */
	boolean function isFWReinit() {}
	/**
	 * This fire on every request, it will process a ColdBox request if the target page is index.cfm or index.bxm
	 *
	 * Also note that this method will output content directly so do not try to return anything from it.
	 *
	 * @targetPage The target page of the request
	 */
	boolean function onRequestStart( required targetPage ) {}
	/**
	 * ON missing template
	 */
	boolean function onMissingTemplate( required template ) {}
	/**
	 * ON session start
	 */
	function onSessionStart() {}
	/**
	 * ON session end
	 */
	function onSessionEnd( required struct sessionScope, struct appScope ) {}
	/**
	 * When the application starts, ColdBox will be loaded into application scope
	 */
	boolean function onApplicationStart() {}
	/**
	 * Tear down the application and execute shutdown procedures
	 */
	function onApplicationEnd( struct appScope ) {}
	/**
	 * Process an exception and returns a rendered bug report
	 *
	 * @controller The ColdBox Controller
	 * @exception  The ColdFusion exception
	 */
	private string function processException( required controller, required exception ) {}
	/**
	 * Process render data setup
	 *
	 * @controller  The ColdBox controller
	 * @statusCode  The status code to send
	 * @contentType The content type to send
	 * @encoding    The content encoding
	 */
	private coldbox.system.Bootstrap function renderDataSetup( required controller, required statusCode, required contentType, required encoding ) {}
	/**
	 * Locate the application key
	 */
	private function locateAppKey() {}
	/**
	 * Helper method to deal with ACF's overload of the page context response, come on Adobe, get your act together!
	 */
	private function getPageContextResponse() {}
}
