// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/Interceptor.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * Base class for all interceptors
 */
component extends="coldbox.system.FrameworkSupertype" {
	/**
	 * The properties this interceptors is bound with
	 */
	property name="properties" type="struct";
	/**
	 * Constructor
	 *
	 * @properties The properties to init the Interceptor with
	 *
	 * @return Interceptor
	 */
	coldbox.system.Interceptor function init( struct properties ) {}
	/**
	 * Internal ColdBox event so all interceptors can load their UDF helpers
	 * DO NOT OVERRIDE or funky things will happen!
	 */
	function cbLoadInterceptorHelpers( event, interceptData ) {}
	/**
	 * Configuration method for the interceptor
	 */
	void function configure() {}
	/**
	 * Get an interceptor property
	 *
	 * @property     The property to retrieve
	 * @defaultValue The default value to return if property does not exist
	 *
	 * @return The property value requested or the default value if not found
	 *
	 * @throws InvalidPropertyException
	 */
	any function getProperty( required property, defaultValue ) {}
	/**
	 * Get the struct of properties defined in this interceptor
	 */
	struct function getProperties() {}
	/**
	 * Store an interceptor property
	 *
	 * @property The property to store
	 * @value    The value to store
	 *
	 * @return Interceptor instance
	 */
	any function setProperty( required property, required value ) {}
	/**
	 * Verify an interceptor property exists
	 *
	 * @property The property to check
	 */
	boolean function propertyExists( required property ) {}
	/**
	 * Unregister the interceptor from the state passed
	 *
	 * @state The named state to unregister this interceptor from
	 *
	 * @return Interceptor
	 */
	coldbox.system.Interceptor function unregister( required state ) {}
}
