// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/comments/CommentService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Service to handle comment operations.
 */
component extends="cborm.models.VirtualEntityService" {
	property name="mailService" inject="mailService@cbmailservices";
	property name="renderer" inject="coldbox:renderer";
	property name="settingService" inject="id:settingService@contentbox";
	property name="securityService" inject="id:securityService@contentbox";
	property name="CBHelper" inject="id:CBHelper@contentbox";
	property name="interceptorService" inject="coldbox:interceptorService";
	variables.settingService = new contentbox.models.system.SettingService();
	variables.securityService = new contentbox.models.security.SecurityService();
	variables.CBHelper = new contentbox.models.system.CBHelper();
	/**
	 * Constructor
	 */
	contentbox.models.comments.CommentService function init() {}
	/**
	 * Get the total comment counts by content object
	 *
	 * @contentId  The content id to filter on
	 * @isApproved If passed, use it to filter on
	 */
	numeric function getTotalCountByContent( string contentId, boolean isApproved ) {}
	/**
	 * Get the total comment counts in the system
	 *
	 * @siteID The site to filter on
	 */
	numeric function getTotalCount( string siteID ) {}
	/**
	 * Get the total number of approved comments in the system
	 *
	 * @siteID The site to filter on
	 */
	numeric function getApprovedCount( string siteID ) {}
	/**
	 * Get the total number of unapproved comments in the system
	 *
	 * @siteID The site to filter on
	 */
	numeric function getUnApprovedCount( string siteID ) {}
	/**
	 * Comment listing for UI of approved comments, returns struct of results=[comments,count]
	 *
	 * @contentID   The content ID to filter on
	 * @contentType The content type discriminator to filter on
	 * @max         The maximum number of records to return, 0 means all
	 * @offset      The offset in the paging, 0 means 0
	 * @sortOrder   Sort the comments asc or desc, by default it is desc
	 * @siteID      The site to filter on if needed
	 *
	 * @return struct with { comments, count }
	 */
	struct function findAllApproved( contentID, contentType, max, offset, string sortOrder, string siteID ) {}
	/**
	 * Deletes unapproved comments
	 *
	 * @expirationDays Required level of staleness in days to delete (0=all unapproved)
	 */
	contentbox.models.comments.CommentService function deleteUnApproved( numeric expirationDays ) {}
	/**
	 * Save a comment according to our rules and process it. Returns a structure of information
	 * results = [moderated:boolean,messages:array]
	 *
	 * @comment      The comment to try to save
	 * @loggedInUser The current logged in user making the comment. If no logged in User, this is a non-persisted entity
	 * @result       Return a struct of : { moderated:boolean, messages : array }
	 */
	struct function saveComment( required comment, required loggedInUser ) {}
	/**
	 * Sends subscription emails to subscribers of the content
	 *
	 * @comment The comment object
	 */
	public void function sendSubscriptionNotifications( required any comment ) {}
	/**
	 * comment search returns struct with keys [comments,count]
	 *
	 * @search     Search query
	 * @isApproved approved bit
	 * @contentID  matching content id
	 * @max        max records
	 * @offset     offset for pagination
	 * @sortOrder  The sort order, defaults to `createdDate DESC`
	 * @siteID     The site to filter on if needed
	 *
	 * @return struct with { comments, count }
	 */
	struct function search( search, isApproved, contentID, numeric max, numeric offset, sortOrder, string siteID ) {}
	/**
	 * Bulk Updates
	 *
	 * @commentID The list or array of ID's to bulk update
	 * @status    The status either 'approve' or 'moderate'
	 *
	 * @return CommentService
	 */
	contentbox.models.comments.CommentService function bulkStatus( any commentID, status ) {}
	/**
	 * Run moderation rules on an incoming comment and set of contentbox settings. If this method returns a false then the comment is moderated
	 * and can continue to be saved. If returns false, then it is blocked and must NOT be saved.
	 *
	 * @comment  Comment to moderate check
	 * @settings The contentbox settings to moderate against
	 */
	private boolean function runModerationRules( required comment, required settings ) {}
	/**
	 * Regex matching of a list of entries against a comment and matching keyword list
	 */
	private boolean function anyKeywordMatch( comment, matchList ) {}
	/**
	 * Check if the user has already a comment in the system
	 *
	 * @email The email address to check.
	 */
	private boolean function userHasPreviousAcceptedComment( required email ) {}
	/**
	 * Send a notification email for comments
	 *
	 * @comment      Comment to moderate check
	 * @siteSettings The contentbox site settings to moderate against
	 */
	private void function sendNotificationEmails( required comment, required siteSettings ) {}
}
