// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/core/dynamic/ObjectPopulator.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This object is in charge of populating objects with incoming data like structs, queries, json and more.
 * It can also populate ORM relationships and respect metadata in objects that can dictate population.
 */
component {
	property name="mixerUtil" inject="coldbox.system.core.dynamic.MixerUtil";
	property name="util" inject="coldbox.system.core.util.Util";
	property name="ormEntityMap";
	property name="entityMetadataMap";
	variables.mixerUtil = new coldbox.system.core.dynamic.MixerUtil();
	variables.util = new coldbox.system.core.util.Util();
	/**
	 * Constructor
	 */
	coldbox.system.core.dynamic.ObjectPopulator function init() {}
	/**
	 * Recreate the metadata caches for orm and entity metadata lookups
	 */
	coldbox.system.core.dynamic.ObjectPopulator function flushMetadataCaches() {}
	/**
	 * Populate a named or instantiated instance from a Json string
	 *
	 * @target               The target to populate
	 * @JSONString           The JSON string to populate the object with. It has to be valid JSON and also a structure with name-key value pairs.
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population
	 * @exclude              A list of keys to exclude in the population
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromJson( required target, required string JSONString, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Populate a named or instantiated instance from an XML Packet
	 *
	 * @target               The target to populate
	 * @xml                  The XML string or packet to populate the target with
	 * @root                 The XML root element to start from, else defaults to XMLRoot
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population
	 * @exclude              A list of keys to exclude in the population
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromXML( required target, required xml, string root, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Populate a named or instantiated instance from a Query object
	 *
	 * @target               The target to populate
	 * @qry                  The query to populate the object with
	 * @rowNumber            The row number to use for population, defaults to 1
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population
	 * @exclude              A list of keys to exclude in the population
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromQuery( required target, required query qry, numeric rowNumber, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Populate a named or instantiated instance from a Query object using a column prefix
	 *
	 * @target               The target to populate
	 * @qry                  The query to populate the object with
	 * @prefix               The prefix used to filter, Example: 'user_' would apply to the following columns: 'user_id' and 'user_name' but not 'address_id'.
	 * @rowNumber            The row number to use for population, defaults to 1
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population
	 * @exclude              A list of keys to exclude in the population
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromQueryWithPrefix( required target, required query qry, required string prefix, numeric rowNumber, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Populate a named or instantiated instance from a struct object using a key prefix
	 *
	 * @target               The target to populate
	 * @memento              The structure to populate the target with
	 * @prefix               The prefix used to filter, Example: 'user_' would apply to the following columns: 'user_id' and 'user_name' but not 'address_id'.
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population
	 * @exclude              A list of keys to exclude in the population
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromStructWithPrefix( required target, required struct memento, required string prefix, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Populate a named or instantiated instance from a struct object using a key prefix
	 *
	 * @target               The target to populate
	 * @memento              The structure to populate the target with
	 * @scope                Use scope injection instead of setters population. Ex: scope=variables.instance.
	 * @trustedSetter        If set to true, the setter method will be called even if it does not exist in the bean
	 * @include              A list of keys to include in the population, if not all keys are populated
	 * @exclude              A list of keys to exclude in the population, if not nothing is excluded
	 * @ignoreEmpty          Ignore empty values on populations, great for ORM population
	 * @nullEmptyInclude     A list of keys to NULL when empty
	 * @nullEmptyExclude     A list of keys to NOT NULL when empty
	 * @composeRelationships Automatically attempt to compose relationships from memento
	 * @ignoreTargetLists    If this is true, then the populator will ignore the target's population include/exclude metadata lists. By default this is false.
	 *
	 * @return The target populated with the packet
	 */
	function populateFromStruct( required target, required struct memento, string scope, boolean trustedSetter, string include, string exclude, boolean ignoreEmpty, string nullEmptyInclude, string nullEmptyExclude, boolean composeRelationships, boolean ignoreTargetLists ) {}
	/**
	 * Compose a related property
	 *
	 * @key            The incoming population key
	 * @relationalMeta The relational metadata being used for population
	 * @target         The target object
	 * @propertyValue  The property value to compose from
	 *
	 * @return The composed property or null if not found
	 */
	private function composeProperty( required key, required relationalMeta, required target, required propertyValue ) {}
	/**
	 * Discover the actual entity name for an orm relationship
	 *
	 * @key            The incoming population key
	 * @relationalMeta The relational metadata being used for population
	 * @target         The target object
	 *
	 * @return The discovered ORM Entity name or if not, then an empty string
	 */
	private string function discoverEntityName( required key, required relationalMeta, required target ) {}
	/**
	 * Get the ORM entity map for the application
	 */
	private array function getORMEntityMap() {}
	/**
	 * Prepares a structure of target relational metadata
	 *
	 * @target The target to work on
	 *
	 * @return The metadata map of composable properties keyed by entity name: { className, path, entityname, persistent, properties }
	 */
	private struct function getRelationshipMetaData( required target ) {}
	/**
	 * Convenience method to get name from target Entity
	 *
	 * @target The target to work on
	 */
	private string function getTargetName( required any target ) {}
}
