// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/TestBox@af36cddb7b68 system/compat/framework/TestCase.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This is the TestBox MXUnit compatible object. You can use this object as a direct replacement
 * To MXUnit BaseTest Case.
 * All assertions found in this object delegate to our core Assertion object.
 */
component extends="testbox.system.BaseSpec" {
	testbox.system.compat.framework.TestCase function init() {}
	function setup() {}
	function teardown() {}
	function afterTests() {}
	function beforeTests() {}
	/**
	 * Run a test remotely like MXUnit
	 *
	 * @testMethod.hint A list or array of test names that are the ones that will be executed ONLY!
	 * @debug.hint      Show debug output on the reports or not
	 * @output.hint     The type of reporter to run the test with
	 */
	remote function runTestRemote( any testMethod, boolean debug, output ) {}
	/**
	 * Utility for dynamically adding assertion behaviors at runtime
	 *
	 * @decoratorName.hint The fully qualified name of the assertion component to add; e.g., org.mycompany.MyAssertionComponent
	 */
	testbox.system.compat.framework.TestCase function addAssertDecorator( required string decoratorName ) {}
	function setMockingFramework() {}
	function getMockFactory() {}
	function mock( mocked ) {}
	/**
	 * MXUnit style debug
	 *
	 * @var.hint   The variable to debug
	 * @label.hint The label to add to the debug entry
	 */
	function debug( required var, string label ) {}
	/**
	 * Expect an exception from the testing spec
	 *
	 * @expectedExceptionType.hint    the type to expect
	 * @expectedExceptionMessage.hint Optional exception message
	 */
	function expectException( expectedExceptionType, expectedExceptionMessage ) {}
	/**
	 * Injects properties into the receiving object
	 */
	any function injectProperty( required any receiver, required string propertyName, required any propertyValue, string scope ) {}
	/**
	 * injects the method from giver into receiver. This is helpful for quick and dirty mocking
	 */
	any function injectMethod( required any receiver, required any giver, required string functionName, string functionNameInReceiver ) {}
	/**
	 * Fail assertion
	 *
	 * @message.hint The message to fail with
	 */
	function fail( message, detail ) {}
	/**
	 * Assert that the passed expression is true
	 */
	function assert( required string condition, message ) {}
	/**
	 * Compares two arrays, element by element, and fails if differences exist
	 */
	function assertArrayEquals( required array expected, required array actual, message ) {}
	/**
	 * Core assertion that compares the values the EXPECTED and ACTUAL parameters
	 */
	function assertEquals( required any expected, required any actual, message ) {}
	/**
	 * Core assertion that compares the values the EXPECTED and ACTUAL parameters with case-sensitivity
	 */
	function assertEqualsCase( required any expected, required any actual, message ) {}
	/**
	 * Assert something is false
	 */
	function assertFalse( required string condition, message ) {}
	/**
	 * Core assertion that compares the values the EXPECTED and ACTUAL parameters to NOT be equal
	 */
	function assertNotEquals( required any expected, required any actual, message ) {}
	/**
	 * Assert that an expected and actual object is NOT the same instance
	 * This only works on objects that are passed by reference, please remember that in Lucee
	 * arrays pass by reference and in Adobe CF they pass by value.
	 */
	function assertNotSame( required expected, required actual, message ) {}
	/**
	 * Compares 2 queries, cell by cell, and fails if differences exist
	 */
	function assertQueryEquals( required query expected, required query actual, message ) {}
	/**
	 * Assert that an expected and actual object is the same instance
	 * This only works on objects that are passed by reference, please remember that in Lucee
	 * arrays pass by reference and in Adobe CF they pass by value.
	 */
	function assertSame( required expected, required actual, message ) {}
	/**
	 * Compares two structures, key by key, and fails if differences exist
	 */
	function assertStructEquals( required struct expected, required struct actual, message ) {}
	/**
	 * Assert something is true
	 */
	function assertTrue( required string condition, message ) {}
	/**
	 * Assert something is array
	 */
	function assertIsArray( required a, message ) {}
	/**
	 * Assert something is query
	 */
	function assertIsQuery( required q, message ) {}
	/**
	 * Assert something is struct
	 */
	function assertIsStruct( required actual, message ) {}
	/**
	 * Assert something is of a certain object type
	 */
	function assertIsTypeOf( required actual, required typeName, message ) {}
	/**
	 * Assert something is of a certain object type without any inheritance lookup
	 */
	function assertIsExactTypeOf( required o, required type, message ) {}
	/**
	 * Assert something is defined or not
	 */
	function assertIsDefined( required o, message ) {}
	/**
	 * Assert something is an XMLDoc
	 */
	function assertIsXMLDoc( required xml, message ) {}
	/**
	 * Assert array is empty
	 */
	function assertIsEmptyArray( required a, message ) {}
	/**
	 * Assert query is empty
	 */
	function assertIsEmptyQuery( required q, message ) {}
	/**
	 * Assert struct is empty
	 */
	function assertIsEmptyStruct( required struct, message ) {}
	/**
	 * Assert string is empty
	 */
	function assertIsEmpty( required o, message ) {}
	/**
	 * Assert that the passed in actual number or date is expected to be close to it within +/- a passed delta and optional datepart
	 */
	function assertEqualsWithTolerance( required expected, required actual, required numeric tolerance, datePart, message ) {}
}
