// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/async/executors/ExecutorBuilder.cfc — do not edit.
/**
 * Static class to build executors from Java:
 *
 * - CachedThreadPool
 * - FixedThreadPool
 * - ForkJoinPool
 * - SingleThreadPool
 * - ScheduledThreadPool
 * - WorkStealingPool
 * - VirtualThreadPool
 *
 * @see https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/Executors.html
 */
component {
	/**
	 * Creates a thread pool that reuses a fixed number of threads operating off a shared unbounded queue.
	 *
	 * @see     https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html
	 * @threads The number of threads in the pool, defaults to 20
	 *
	 * @return ExecutorService: The newly created thread pool
	 */
	function newFixedThreadPool( numeric threads ) {}
	/**
	 * Creates a thread pool that creates new threads as needed, but will
	 * reuse previously constructed threads when they are available.
	 *
	 * @see https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html
	 *
	 * @return ExecutorService: The newly created thread pool
	 */
	function newCachedThreadPool() {}
	/**
	 * Creates a thread pool that can schedule commands to run after a given delay,
	 * or to execute periodically.
	 *
	 * @see          https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html
	 * @corePoolSize The number of threads to keep in the pool, even if they are idle, default is 20
	 *
	 * @return ScheduledExecutorService: The newly created thread pool
	 */
	function newScheduledThreadPool( corePoolSize ) {}
	/**
	 * Create a virtual thread executor that can be used to run tasks in a virtual thread context.
	 *
	 * @see https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/VirtualThreadExecutor.html
	 *
	 * @return VirtualThreadExecutor: The newly created virtual thread executor
	 */
	function newVirtualThreadExecutor() {}
	/**
	 * Create a work stealing pool executor that can be used to run tasks in a work-stealing context.
	 *
	 * @see https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/WorkStealingPoolExecutor.html
	 *
	 * @return WorkStealingPoolExecutor: The newly created work stealing pool executor
	 */
	function newWorkStealingPoolExecutor( numeric parallelism ) {}
	/**
	 * New ForkJoinPool executor.
	 *
	 * @see   https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ForkJoinPool.html
	 * @param maxThreads The maximum number of threads to use in the pool, defaults to 20.
	 *
	 * @return ForkJoinPool: The newly created ForkJoinPool
	 */
	function newForkJoinPool( numeric maxThreads ) {}
}
