// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/modules/jmespath/models/JmesPath.cfc — do not edit.
component {
	property name="jmesPathLexer" inject="Lexer@JMESPath";
	property name="jmesPathParser" inject="Parser@JMESPath";
	property name="jmesPathRuntime" inject="Runtime@JMESPath";
	property name="jmesPathTreeInterpreter" inject="TreeInterpreter@JMESPath";
	variables.jmesPathLexer = new commandbox.system.modules.jmespath.models.Lexer();
	variables.jmesPathParser = new commandbox.system.modules.jmespath.models.Parser();
	variables.jmesPathRuntime = new commandbox.system.modules.jmespath.models.Runtime();
	variables.jmesPathTreeInterpreter = new commandbox.system.modules.jmespath.models.TreeInterpreter();
	function compile( stream ) {}
	function tokenize( stream ) {}
	function search( data, expression ) {}
}
