// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/controller/flash.cfc — do not edit.
component {
	/**
	 * Returns the value of a specific key in the Flash (or the entire Flash as a struct if no key is passed in).
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 *
	 * @key The key to get the value for.
	 */
	public any function flash( string key ) {}
	/**
	 * Deletes everything from the Flash.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 */
	public void function flashClear() {}
	/**
	 * Returns how many keys exist in the Flash.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 */
	public numeric function flashCount() {}
	/**
	 * Deletes a specific key from the Flash.
	 * Returns `true` if the key exists.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 *
	 * @key The key to delete
	 */
	public any function flashDelete( required string key ) {}
	/**
	 * Inserts a new key / value into the Flash.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 */
	public void function flashInsert() {}
	/**
	 * Returns whether or not the Flash is empty.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 */
	public boolean function flashIsEmpty() {}
	/**
	 * Make the entire Flash or specific key in it stick around for one more request.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 */
	public void function flashKeep( string key ) {}
	/**
	 * Checks if a specific key exists in the Flash.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 *
	 * @key The key to check.
	 */
	public boolean function flashKeyExists( required string key ) {}
	/**
	 * Dynamically sets flashStorage during request lifecycle.
	 *
	 * [section: Controller]
	 * [category: Flash Functions]
	 *
	 * @storage   Accepts "session" or "cookie"
	 * @setGlobally       If true, updates both app-level and controller-level flashStorage
	 */
	public void function setFlashStorage( string storage, boolean setGlobally ) {}
	/**
	 * Internal function.
	 */
	public struct function $readFlash() {}
	/**
	 * Internal function.
	 */
	public any function $writeFlash( struct flash ) {}
	/**
	 * Internal function. Returns true when running inside the Wheels test
	 * harness. Set by `wheels/tests/runner.cfm` for every core test request.
	 * Pure CFML — no engine-specific Java calls — so it is safe on
	 * Lucee 5/6/7, Adobe 2018-2025, and BoxLang.
	 */
	public boolean function $inTestHarness() {}
	/**
	 * Internal function.
	 * Builds the attribute collection used when writing the flash cookie so it is
	 * flagged httpOnly / secure / sameSite (mirrors $csrfCookieAttributeCollection).
	 */
	public struct function $flashCookieAttributeCollection( required string value ) {}
	/**
	 * Internal function.
	 */
	public void function $flashClear() {}
	/**
	 * Internal function.
	 */
	public void function $setFlashStorage( required string storage ) {}
	/**
	 * Internal function.
	 */
	public string function $getFlashStorage() {}
	/**
	 * Internal function.
	 */
	public void function $setFlashAppend( required boolean append ) {}
	/**
	 * Internal function.
	 */
	public string function $getFlashAppend() {}
}
