// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/controller/miscellaneous.cfc — do not edit.
component {
	/**
	 * Sends an email using a template and an optional layout to wrap it in.
	 * Besides the Wheels-specific arguments documented here, you can also pass in any argument that is accepted by the `cfmail` tag as well as your own arguments to be used by the view.
	 * Note that only arguments whose names match a known `cfmail` attribute are passed through to `cfmail`; every other argument is made available to the email view as a variable instead.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 *
	 * @template The path to the email template or two paths if you want to send a multipart email (a maximum of two templates, one text and one html version, is supported). if the `detectMultipart` argument is `false`, the template for the text version should be the first one in the list. This argument is also aliased as `templates`.
	 * @from Email address to send from.
	 * @to List of email addresses to send the email to.
	 * @subject The subject line of the email.
	 * @layout Layout(s) to wrap the email template in. This argument is also aliased as `layouts`.
	 * @file A list of the names of the files to attach to the email. This will reference files stored in the `files` folder (or a path relative to it). This argument is also aliased as `files`.
	 * @detectMultipart When set to `true` and multiple values are provided for the `template` argument, Wheels will detect which of the templates is text and which one is HTML (by counting the `<` characters).
	 * @deliver When set to `false`, the email will not be sent.
	 * @writeToFile Path that receives the rendered text and/or HTML body. This is a debug dump of the body content, not a MIME `.eml` — no `From`/`To`/`Subject`/`Content-Type` headers are written. A `.eml` extension will not open as a rendered message in Outlook; use `.html`/`.txt` and open the file in a browser or editor.
	 */
	public any function sendEmail( string template, required string from, required string to, required string subject, any layout, string file, boolean detectMultipart, boolean deliver, string writeToFile ) {}
	/**
	 * Internal function. Restores the controller's `variables` scope after the email view templates have been rendered by `sendEmail`.
	 * Shadowed values are put back and keys that did not exist before are deleted.
	 * Kept as a separate function (rather than inline in `sendEmail`'s `finally` block) because Lucee 7 miscompiles `for` loops that use `local` or `var` variables inside `finally` blocks.
	 */
	public void function $restoreEmailViewVariables( required array customViewVariables, required struct shadowedVariables ) {}
	/**
	 * Sends a file to the user (from the `files` folder or a path relative to it by default).
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 *
	 * @file The file to send to the user. Values containing the `..` character sequence anywhere (even as part of a legitimate file name) are rejected to prevent path traversal.
	 * @name The file name to show in the browser download dialog box.
	 * @type The HTTP content type to deliver the file as.
	 * @disposition Set to `inline` to have the browser handle the opening of the file (possibly inline in the browser) or set to `attachment` to force a download dialog box.
	 * @directory Directory outside of the web root where the file exists. Must be a full path. Values containing the `..` character sequence are rejected to prevent path traversal.
	 * @deleteFile Pass in `true` to delete the file on the server after sending it.
	 * @deliver When set to `false`, the file will not be sent to the browser (used for testing).
	 */
	public any function sendFile( required string file, string name, string type, string disposition, string directory, boolean deleteFile, boolean deliver ) {}
	/**
	 * Returns whether Wheels is communicating over a secure port.
	 * `X-Forwarded-Proto` is client-controlled and is only honored when the app has opted into
	 * proxy trust via `set(trustProxyHeaders=true)` behind a trusted reverse proxy.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isSecure() {}
	/**
	 * Returns whether the page was called from JavaScript or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isAjax() {}
	/**
	 * Returns whether the request was a normal `GET` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isGet() {}
	/**
	 * Returns whether the request came from a form `POST` submission or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isPost() {}
	/**
	 * Returns whether the request was a `PUT` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isPut() {}
	/**
	 * Returns whether the request was a `PATCH` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isPatch() {}
	/**
	 * Returns whether the request was a `DELETE` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isDelete() {}
	/**
	 * Returns whether the request was a `HEAD` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isHead() {}
	/**
	 * Returns whether the request was an `OPTIONS` request or not.
	 *
	 * [section: Controller]
	 * [category: Miscellaneous Functions]
	 */
	public boolean function isOptions() {}
	/**
	 * Internal function.
	 * Returns whether an `only` / `except` action gating declaration applies to the supplied action.
	 * Applies when neither list is provided, when `only` is provided and contains the action, or when `except` is provided and does not contain the action.
	 * When both lists are provided the conditions are OR'ed, so the declaration applies when the action is in `only` or when it's missing from `except`.
	 * Used by filters, verifications and CSRF protection.
	 */
	public boolean function $appliesToAction( required string action, string only, string except ) {}
}
