// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/ioc/Injector.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * The WireBox injector is the pivotal class in WireBox that performs dependency injection.
 * It can be used standalone or it can be used in conjunction of a ColdBox application context.
 * It can also be configured with a mapping configuration file called a binder, that can provide object/mappings and configuration data.
 *
 * A WireBox Injector: Builds the graphs of objects that make up your application.
 *
 * All injectors implement: coldbox.system.ioc.IInjector
 *
 * Easy Startup:
 * <pre class='brush: cf'>
 * injector = new coldbox.system.ioc.Injector();
 * </pre>
 *
 * Inline Config:
 * <pre class='brush: cf'>
 * injector = new coldbox.system.ioc.Injector( { scopeRegistration : { enabled : false } } );
 * </pre>
 *
 * Binder Startup
 * <pre class='brush: cf'>
 * injector = new coldbox.system.ioc.Injector(new MyBinder());
 * </pre>
 *
 * Binder Path Startup
 * <pre class='brush: cf'>
 * injector = new coldbox.system.ioc.Injector( "config.MyBinder" );
 * </pre>
 *
 * @see coldbox.system.ioc.IInjector
 */
component {
	/**
	 * ColdBox  Utility class
	 */
	property name="utility";
	/**
	 * Scope Storages Utility
	 */
	property name="scopeStorage";
	/**
	 * WireBox Version
	 */
	property name="version";
	/**
	 * The Configuration Binder object
	 */
	property name="binder";
	/**
	 * ColdBox Application Link
	 */
	property name="coldbox";
	/**
	 * CacheBox Link
	 */
	property name="cacheBox";
	/**
	 * Event Manager Link
	 */
	property name="eventManager";
	/**
	 * Configured Event States
	 */
	property name="eventStates" type="array";
	/**
	 * LogBox and Class Logger
	 */
	property name="logBox";
	/**
	 * Log Reference
	 */
	property name="log";
	/**
	 * Parent Injector
	 */
	property name="parent";
	/**
	 * Root Injector instance
	 */
	property name="root";
	/**
	 * LifeCycle Scopes
	 */
	property name="scopes";
	/**
	 * The injector Unique ID
	 */
	property name="injectorID";
	/**
	 * The Global AsyncManager
	 *
	 * @see coldbox.system.async.AsyncManager
	 */
	property name="asyncManager";
	/**
	 * The logBox task scheduler executor
	 *
	 * @see coldbox.system.async.executors.ScheduledExecutor
	 */
	property name="taskScheduler";
	/**
	 * An injector can have children injectors referenced by a unique name
	 */
	property name="childInjectors" type="struct";
	/**
	 * The name of the injector
	 */
	property name="name" type="string";
	/**
	 * The object builder for this injector
	 */
	property name="objectBuilder";
	this.SCOPES = new coldbox.system.ioc.Scopes();
	this.TYPES = new coldbox.system.ioc.Types();
	variables.utility = new coldbox.system.core.util.Util();
	variables.scopeStorage = new coldbox.system.core.collections.ScopeStorage();
	variables.coldbox = new coldbox.system.web.Controller();
	variables.asyncManager = new coldbox.system.async.AsyncManager();
	variables.objectBuilder = new coldbox.system.ioc.Builder();
	variables.parent = new coldbox.system.ioc.Injector();
	variables.logBox = new coldbox.system.logging.LogBox();
	variables.eventManager = new coldbox.system.core.events.EventPoolManager();
	variables.mixerUtil = new coldbox.system.core.dynamic.MixerUtil();
	variables.binder = new coldbox.system.ioc.config.Binder();
	/**
	 * WireBox can be constructed with no parameters and it will use the default binder: `coldbox.system.ioc.config.DefaultBinder` for configuration
	 * and place the instance in `application.wirebox` scope for easy access.
	 *
	 * However you can also instantiate Wirebox with:
	 * - A binder instance
	 * - A binder path
	 * - A WireBox configuration DSL structure
	 *
	 * @binder              A binder instance, path, or DSL structure to configure WireBox with
	 * @properties          A structure of binding properties to passthrough to the Binder Configuration CFC
	 * @coldbox             A coldbox application context that this instance of WireBox can be linked to, if not using it, we just ignore it.
	 * @coldbox.doc_generic coldbox.system.web.Controller
	 * @name                The internal name of the injector, defaults to 'root' if not passed
	 */
	coldbox.system.ioc.Injector function init( binder, struct properties, coldbox.system.web.Controller coldbox, name ) {}
	/**
	 * Verify if a child injector has been registered by name
	 *
	 * @name The name of the child injector to check
	 */
	boolean function hasChildInjector( required name ) {}
	/**
	 * Register a child injector instance with this injector and set this injector as a parent of the child.
	 *
	 * @name  The unique name to register the child with
	 * @child The child Injector instance to register
	 */
	coldbox.system.ioc.Injector function registerChildInjector( required name, required child ) {}
	/**
	 * Remove a child injector from this injector
	 *
	 * @name The unique name of the child injector to remove
	 *
	 * @return Boolean indicator if the injector was found and removed (true) or not found and not removed (false)
	 */
	boolean function removeChildInjector( required name ) {}
	/**
	 * Get a child injector from this injector
	 *
	 * @throws ChildNotFoundException - If the passed child name does not exist with this injector
	 */
	coldbox.system.ioc.Injector function getChildInjector( required name ) {}
	/**
	 * Get an array of all the registered child injectors in this injector
	 */
	array function getChildInjectorNames() {}
	/**
	 * Register an injector to be tracked in the lookup reference map. Used for providers mostly.
	 *
	 * @injector The injector to track
	 */
	coldbox.system.ioc.Injector function registerInjectorReference( required injector ) {}
	/**
	 * Get an injector reference by unique name
	 *
	 * @name The unique injector reference name
	 */
	coldbox.system.ioc.Injector function getInjectorReference( required name ) {}
	/**
	 * Get an array of registered injector references
	 */
	array function getInjectorReferenceNames() {}
	/**
	 * Configure this injector for operation, called by the init(). You can also re-configure this injector programmatically, but it is not recommended.
	 *
	 * @binder     The configuration binder object or path or dsl structure to configure this Injector instance with
	 * @properties A structure of binding properties to passthrough to the Configuration CFC
	 */
	coldbox.system.ioc.Injector function configure( required binder, required struct properties ) {}
	/**
	 * Shutdown the injector gracefully by calling the shutdown events internally.
	 */
	coldbox.system.ioc.Injector function shutdown() {}
	/**
	 * Locates, Creates, Injects and Configures an object model instance
	 *
	 * @name          The mapping name or CFC instance path to try to build up
	 * @initArguments The constructor structure of arguments to passthrough when initializing the instance
	 * @dsl           The dsl string to use to retrieve the instance model object, mutually exclusive with 'name
	 * @targetObject  The object requesting the dependency, usually only used by DSL lookups
	 * @injector      The child injector to use when retrieving the instance
	 *
	 * @return The requested instance
	 *
	 * @throws InstanceNotFoundException - When the requested instance cannot be found
	 * @throws InvalidChildInjector      - When you request an instance from an invalid child injector name
	 */
	function getInstance( name, struct initArguments, dsl, targetObject, injector ) {}
	/**
	 * Build an instance, this is called from registered scopes only as they provide locking and transactions
	 *
	 * @mapping             The mapping to construct
	 * @mapping.doc_generic coldbox.system.ioc.config.Mapping
	 * @initArguments       The constructor structure of arguments to passthrough when initializing the instance
	 */
	function buildInstance( required coldbox.system.ioc.config.Mapping mapping, struct initArguments ) {}
	/**
	 * Register a new requested mapping object instance thread safely and returns the mapping configured for this instance
	 *
	 * @name         The name of the mapping to register
	 * @instancePath The path of the mapping to register
	 */
	function registerNewInstance( required name, required instancePath ) {}
	/**
	 * A direct way of registering custom DSL namespaces
	 *
	 * @namespace The namespace you would like to register
	 * @path      The instantiation path to the CFC that implements this scope, it must have an init() method and implement: coldbox.system.ioc.dsl.IDSLBuilder
	 */
	coldbox.system.ioc.Injector function registerDSL( required namespace, required path ) {}
	/**
	 * Checks if this injector can locate a model instance or not
	 *
	 * @name The object name or alias to search for if this container can locate it or has knowledge of it
	 */
	boolean function containsInstance( required name ) {}
	/**
	 * Tries to locate a specific instance by scanning all scan locations and returning the instantiation path. If model not found then the returned instantiation path will be empty
	 *
	 * @name The model instance name to locate
	 *
	 * @return The instantiation path of the located model instance, or an empty string if not found.
	 */
	function locateInstance( required name ) {}
	/**
	 * I wire up target objects with dependencies either by mappings or a-la-carte autowires
	 *
	 * @target              The target object to wire up
	 * @mapping             The object mapping with all the necessary wiring metadata. Usually passed by scopes and not a-la-carte autowires
	 * @mapping.doc_generic coldbox.system.ioc.config.Mapping
	 * @targetID            A unique identifier for this target to wire up. Usually a class path or file path should do. If none is passed we will get the id from the passed target via introspection but it will slow down the wiring
	 * @annotationCheck     This value determines if we check if the target contains an autowire annotation in the cfcomponent tag: autowire=true|false, it will only autowire if that metadata attribute is set to true. The default is false, which will autowire anything automatically.
	 */
	function autowire( required target, coldbox.system.ioc.config.Mapping mapping, targetID, boolean annotationCheck ) {}
	/**
	 * Link a parent Injector with this injector
	 *
	 * @injector             A WireBox Injector to assign as a parent to this Injector
	 * @injector.doc_generic coldbox.system.ioc.Injector
	 *
	 * @return Injector
	 */
	coldbox.system.ioc.Injector function setParent( required coldbox.system.ioc.Injector injector ) {}
	/**
	 * Has a parent injector
	 */
	boolean function hasParent() {}
	/**
	 * Has a root injector
	 */
	boolean function hasRoot() {}
	/**
	 * Get a reference to the parent injector instance, else an empty simple string meaning nothing is set
	 *
	 * @doc.type coldbox.system.ioc.Injector
	 */
	coldbox.system.ioc.Injector function getParent() {}
	/**
	 * Get an object populator useful for populating objects from JSON,XML, etc.
	 *
	 * @return coldbox.system.core.dynamic.ObjectPopulator
	 */
	coldbox.system.core.dynamic.ObjectPopulator function getObjectPopulator() {}
	/**
	 * Checks if Coldbox application context is linked
	 *
	 * @doc.type boolean
	 */
	boolean function isColdBoxLinked() {}
	/**
	 * Checks if CacheBox is linked
	 *
	 * @doc.type boolean
	 */
	boolean function isCacheBoxLinked() {}
	/**
	 * Remove the Injector from scope registration if enabled, else does nothing
	 */
	coldbox.system.ioc.Injector function removeFromScope() {}
	/**
	 * Get a registered scope in this injector by name
	 *
	 * @scope The scope name
	 *
	 * @throws InvalidScopeException - When the scope requested has not been registered in this Injector
	 */
	function getScope( required any scope ) {}
	/**
	 * Clear the singleton cache
	 */
	coldbox.system.ioc.Injector function clearSingletons() {}
	/**
	 * Clear the app singleton cache
	 */
	coldbox.system.ioc.Injector function clearAppSingletons() {}
	/**
	 * Return a self reference using the scoped registration, mostly used by providers or scope widening objects
	 *
	 * @doc.type coldbox.system.ioc.Injector
	 */
	function locateScopedSelf() {}
	/**
	 * Get the structure of scope registration information
	 */
	struct function getScopeRegistration() {}
	/**
	 * Process lazy properties on the target object
	 *
	 * @targetObject The target object to do some goodness on
	 * @mapping      The target mapping
	 */
	private coldbox.system.ioc.Injector function processLazyProperties( required targetObject, required mapping ) {}
	/**
	 * Process observed properties on the target object
	 *
	 * @targetObject The target object to do some goodness on
	 * @mapping      The target mapping
	 */
	private coldbox.system.ioc.Injector function processObservedProperties( required targetObject, required mapping ) {}
	/**
	 * Process mixins on the selected target
	 *
	 * @targetObject The target object to do some goodness on
	 * @mapping      The target mapping
	 */
	private coldbox.system.ioc.Injector function processMixins( required targetObject, required mapping ) {}
	/**
	 * Process provider methods on the selected target
	 *
	 * @targetObject The target object to do some goodness on
	 * @mapping      The target mapping
	 */
	private coldbox.system.ioc.Injector function processProviderMethods( required targetObject, required mapping ) {}
	/**
	 * Process after DI completion routines
	 *
	 * @targetObject      The target object to do some goodness on
	 * @DICompleteMethods The array of DI completion methods to call
	 */
	private coldbox.system.ioc.Injector function processAfterCompleteDI( required targetObject, required DICompleteMethods ) {}
	/**
	 * Process property and setter injections
	 *
	 * @targetObject The target object to do some goodness on, usually a CFC
	 * @DIData       The DI data array to use for injection
	 * @targetID     The target Identifier of the target object
	 * @mapping      The mapping of the target object
	 */
	private coldbox.system.ioc.Injector function processInjection( required targetObject, required array DIData, required string targetID, required mapping ) {}
	/**
	 * Get a reference to the transient cache, if none exists, it will be created for the request.
	 *
	 * @targetID If passed, get the transient cache for the targetID, otherwise, get the global transient cache
	 */
	struct function getTransientCache( targetId ) {}
	/**
	 * Process a target object dependency delegation
	 *
	 * @target   The target object being injected with dependencies/delegations
	 * @targetID The target ID to process injections
	 * @delegate The delegation object that was injected
	 * @DIData   The DI information about the delegation/injection
	 */
	private function processDelegation( required target, required string targetID, required delegate, required DIData ) {}
	/**
	 * Inject a model object with dependencies via setters or property injections
	 *
	 * @target         The target that will be injected with dependencies
	 * @propertyName   The name of the property to inject
	 * @propertyObject The object to inject
	 * @scope          The scope to inject a property into, if any else empty means it is a setter call
	 * @argName        The name of the argument to send if setter injection
	 */
	private coldbox.system.ioc.Injector function injectTarget( required target, required propertyName, required propertyObject, required scope, required argName ) {}
	/**
	 * Register all internal and configured WireBox Scopes
	 */
	private coldbox.system.ioc.Injector function registerScopes() {}
	/**
	 * Register all the configured listeners in the configuration file
	 */
	private coldbox.system.ioc.Injector function registerListeners() {}
	/**
	 * Register all the configured listeners in the configuration file
	 *
	 * @listener The listener struct to register: { class, name, properties }
	 */
	public coldbox.system.ioc.Injector function registerListener( required struct listener ) {}
	/**
	 * Register this injector on a user specified scope
	 *
	 * @scopeInfo The scope info struct: key, scope
	 */
	private coldbox.system.ioc.Injector function doScopeRegistration( scopeInfo ) {}
	/**
	 * Configure a standalone version of cacheBox for persistence
	 *
	 * @config The cacheBox configuration data structure
	 */
	private coldbox.system.ioc.Injector function configureCacheBox( required struct config ) {}
	/**
	 * Configure a standalone version of logBox for logging
	 */
	private coldbox.system.ioc.Injector function configureLogBox( required configPath ) {}
	/**
	 * Configure a standalone version of a WireBox Event Manager
	 */
	private coldbox.system.ioc.Injector function configureEventManager() {}
	/**
	 * Load a configuration binder object according to passed in type
	 *
	 * @binder     The data CFC configuration instance, instantiation path or programmatic binder object to configure this injector with
	 * @properties A map of binding properties to passthrough to the Configuration CFC
	 */
	private coldbox.system.ioc.config.Binder function buildBinder( required binder, required properties ) {}
}
