// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/ioc/Provider.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * A WireBox provider object that retrieves objects by using the provider pattern.
 *
 * @see coldbox.system.ioc.IProvider
 */
component {
	/**
	 * The name of the mapping this provider is binded to, MUTEX with name
	 */
	property name="name";
	/**
	 * The DSL string this provider is binded to, MUTEX with name
	 */
	property name="dsl ";
	/**
	 * he injector scope registration structure
	 */
	property name="scopeRegistration";
	/**
	 * The scope storage utility
	 */
	property name="scopeStorage";
	/**
	 * The target object that requested the provider
	 */
	property name="targetObject";
	variables.scopeStorage = new coldbox.system.core.collections.ScopeStorage();
	/**
	 * Constructor
	 *
	 * @scopeRegistration The injector scope registration structure
	 * @name              The name of the mapping this provider is binded to
	 * @targetObject      The target object that requested the provider.
	 * @injectorName      The name of the injector requesting the dependency
	 */
	coldbox.system.ioc.Provider function init( required struct scopeRegistration, name, required targetObject, required injectorName ) {}
	/**
	 * Get the provided object
	 */
	any function $get() {}
	/**
	 * Proxy calls to provided element
	 *
	 * @missingMethodName      missing method name
	 * @missingMethodArguments missing method arguments
	 */
	any function onMissingMethod( required missingMethodName, required missingMethodArguments ) {}
}
