// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/view/assets.cfc — do not edit.
component {
	/**
	 * Returns a `link` tag for a stylesheet (or several) based on the supplied arguments.
	 *
	 * [section: View Helpers]
	 * [category: Asset Functions]
	 *
	 * @sources The name of one or many CSS files in the stylesheets folder, minus the `.css` extension. Pass a full URL to generate a tag for an external style sheet. Can also be called with the `source` argument.
	 * @type The `type` attribute for the `link` tag.
	 * @media The `media` attribute for the `link` tag.
	 * @rel  The `rel` attribute for the relation between the tag and href.
	 * @head Set to `true` to place the output in the `head` area of the HTML page instead of the default behavior (which is to place the output where the function is called from).
	 * @delim The delimiter to use for the list of CSS files.
	 * @encode Use this argument to decide whether the output of the function should be encoded in order to prevent Cross Site Scripting (XSS) attacks. Set it to `true` to encode all relevant output for the specific HTML element in question (e.g. tag content, attribute values, and URLs). For HTML elements that have both tag content and attribute values you can set this argument to `attributes` to only encode attribute values and not tag content.
	 */
	public string function styleSheetLinkTag( string sources, string type, string media, string rel, boolean head, string delim, boolean encode ) {}
	/**
	 * Returns a `script` tag for a JavaScript file (or several) based on the supplied arguments.
	 *
	 * [section: View Helpers]
	 * [category: Asset Functions]
	 *
	 * @sources The name of one or many JavaScript files in the `javascripts` folder, minus the `.js` extension. Pass a full URL to access an external JavaScript file. Can also be called with the `source` argument.
	 * @type The `type` attribute for the `script` tag.
	 * @head Set to `true` to place the output in the `head` area of the HTML page instead of the default behavior (which is to place the output where the function is called from).
	 * @delim The delimiter to use for the list of JavaScript files.
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function javaScriptIncludeTag( string sources, string type, boolean head, string delim, boolean encode ) {}
	/**
	 * Returns an `img` tag.
	 * If the image is stored in the local `images` folder, the tag will also set the `width`, `height`, and `alt` attributes for you.
	 * You can pass any additional arguments (e.g. `class`, `rel`, `id`), and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Asset Functions]
	 *
	 * @source The file name of the image if it's available in the local file system (i.e. ColdFusion will be able to access it). Provide the full URL if the image is on a remote server.
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function imageTag( required string source, boolean onlyPath, string host, string protocol, numeric port, boolean encode, boolean required ) {}
	/**
	 * Calls $imageTag and adds the result to the cache.
	 * Called from the imageTag function above if images are set to be cached and the image is not already in the cache.
	 */
	public string function $addImageTagToCache() {}
	/**
	 * Called from the imageTag function above to do all of the work (create the tag, get width / height using cfimage etc).
	 */
	public string function $imageTag() {}
	/**
	 * Collapses `.` / `..` on local asset sources and blanks javascript:/data:
	 * schemes. Protocol-relative `//host` URLs are returned unchanged (S15).
	 */
	public string function $sanitizeLocalAssetSource( required string source ) {}
	/**
	 * True when childPath's canonical location is the parent or a descendant.
	 */
	public boolean function $isResolvedPathInside( required string childPath, required string parentPath ) {}
	/**
	 * Appends a query string to the asset (a new query string is created on each app reload).
	 * Used to force local browser caches to refresh when there is an update to assets (CSS, JavaScript etc).
	 */
	public string function $appendQueryString() {}
	/**
	 * Internal function.
	 */
	public string function $assetDomain( required string pathToAsset ) {}
}
