// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/view/csrf.cfc — do not edit.
component {
	/**
	 * Include this in your layouts' `head` sections to include meta tags containing the authenticity token for use by JavaScript AJAX requests needing to `POST` data to your application.
	 *
	 * [section: View Helpers]
	 * [category: Miscellaneous Functions]
	 *
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function csrfMetaTags( any encode ) {}
	/**
	 * Returns a hidden form field containing a new authenticity token.
	 *
	 * [section: View Helpers]
	 * [category: General Form Functions]
	 */
	public string function authenticityTokenField() {}
}
