// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/view/forms.cfc — do not edit.
component {
	/**
	 * Builds and returns a string containing the closing `form` tag.
	 *
	 * [section: View Helpers]
	 * [category: General Form Functions]
	 *
	 * @prepend [see:textField]
	 * @append [see:textField],
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function endFormTag( string prepend, string append, any encode ) {}
	/**
	 * Builds and returns a string containing the opening `form` tag.
	 * The form's action will be built according to the same rules as `URLFor`.
	 * Note: Pass any additional arguments like `class`, `rel`, and `id`, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: General Form Functions]
	 *
	 * @method The type of `method` to use in the `form` tag (`delete`, `get`, `patch`, `post`, and `put` are the options).
	 * @multipart Set to `true` if the form should be able to upload files.
	 * @route Name of a route that you have configured in `config/routes.cfm`.
	 * @controller Name of the controller to include in the URL.
	 * @action Name of the action to include in the URL.
	 * @key Key(s) to include in the URL.
	 * @params Any additional parameters to be set in the query string (example: wheels=cool&x=y). Please note that Wheels uses the & and = characters to split the parameters and encode them properly for you. However, if you need to pass in & or = as part of the value, then you need to encode them (and only them), example: a=cats%26dogs%3Dtrouble!&b=1.
	 * @anchor Sets an anchor name to be appended to the path.
	 * @onlyPath If true, returns only the relative URL (no protocol, host name or port).
	 * @host Set this to override the current host.
	 * @protocol Set this to override the current protocol.
	 * @port Set this to override the current port number.
	 * @prepend String to prepend to the form control. Useful to wrap the form control with HTML tags.
	 * @append String to append to the form control. Useful to wrap the form control with HTML tags.
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function startFormTag( string method, boolean multipart, string route, string controller, string action, any key, string params, string anchor, boolean onlyPath, string host, string protocol, numeric port, string prepend, string append, any encode ) {}
	/**
	 * Internal function. Resolves the route and method for startFormTag: finds a named route
	 * matching controller/action/method, verifies the route's method, and rewrites non-get/post
	 * verbs to `post` while remembering the original verb for the `_method` hidden field.
	 * Mutates `args.route` and `args.method` in place and returns the original verb (empty string
	 * when none applies).
	 */
	public string function $startFormTagMethod( required struct args ) {}
	/**
	 * Builds and returns a string containing a submit button form control.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: General Form Functions]
	 *
	 * @value Message to display in the button form control.
	 * @image File name of the image file to use in the button form control.
	 * @prepend [see:textField]
	 * @append [see:textField]
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function submitTag( string value, string image, string prepend, string append, any encode ) {}
	/**
	 * Builds and returns a string containing a button form control.
	 *
	 * [section: View Helpers]
	 * [category: General Form Functions]
	 *
	 * @content Content to display inside the button.
	 * @type The type for the button: `button`, `reset`, or `submit`.
	 * @value The value of the button when submitted.
	 * @image File name of the image file to use in the button form control.
	 * @prepend [see:textField]
	 * @append [see:textField]
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function buttonTag( string content, string type, string value, string image, string prepend, string append, any encode ) {}
	/**
	 * Internal function. Resolves the object a form helper is bound to once and stashes it on the
	 * helper's argument struct (passed by reference) so the shared internals ($formValue,
	 * $maxLength, $formHasError, $getFieldLabel) reuse it instead of each re-resolving it via
	 * $getObject. The `$`-prefixed key is automatically excluded from rendered HTML attributes
	 * by $tag() / $element().
	 */
	public void function $primeBoundObject( required struct args ) {}
	/**
	 * Internal function.
	 */
	public string function $formValue( required any objectName, required string property ) {}
	/**
	 * Internal function.
	 */
	public any function $maxLength( required any objectName, required string property ) {}
	/**
	 * Internal function.
	 */
	public boolean function $formHasError( required any objectName, required string property ) {}
	/**
	 * Internal function.
	 */
	public string function $createLabel( required any objectName, required string property, required string label, required string prependToLabel, any encode ) {}
	/**
	 * Internal function.
	 */
	public string function $formBeforeElement( required any objectName, required string property, required any label, required string labelPlacement, required string prepend, required string append, required string prependToLabel, required string appendToLabel, required string errorElement, required string errorClass, any encode ) {}
	/**
	 * Internal function.
	 */
	public string function $formAfterElement( required any objectName, required string property, required string label, required string labelPlacement, required string prepend, required string append, required string prependToLabel, required string appendToLabel, required string errorElement, any encode ) {}
	/**
	 * Whether this field helper should emit errorMessageOn() inside its error wrapper.
	 * Per-call `includeErrorMessage` wins; otherwise the app-level setting
	 * `includeFormErrorMessages` (default false) is used.
	 */
	public boolean function $includeFormErrorMessage() {}
	/**
	 * Internal function.
	 */
	public string function $getFieldLabel( required any objectName, required string property, required string label ) {}
}
