// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/view/formsdate.cfc — do not edit.
component {
	/**
	 * Internal function.
	 */
	public string function $yearSelectTag( required numeric startYear, required numeric endYear ) {}
	/**
	 * Internal function.
	 */
	public string function $monthSelectTag( required string monthDisplay, required string monthNames, required string monthAbbreviations ) {}
	/**
	 * Internal function.
	 */
	public string function $daySelectTag() {}
	/**
	 * Internal function.
	 */
	public string function $hourSelectTag() {}
	/**
	 * Internal function.
	 */
	public string function $minuteSelectTag( required numeric minuteStep ) {}
	/**
	 * Internal function.
	 */
	public any function $secondSelectTag( required numeric secondStep ) {}
	/**
	 * Internal function.
	 */
	public string function $dateOrTimeSelect( required any objectName, required string property, required string $functionName, boolean combine, boolean twelveHour ) {}
	/**
	 * Internal function. Normalize a bound date/time value for
	 * $dateOrTimeSelect: unwrap java.time.LocalDateTime and Oracle TIMESTAMP
	 * objects, and repair BoxLang's string date parsing quirks.
	 */
	public any function $dateOrTimeSelectNormalizeValue( required any value ) {}
	/**
	 * Internal function. Render the order segments of $dateOrTimeSelect,
	 * dispatching each segment to its child select-tag helper.
	 */
	public string function $dateOrTimeSelectRender( required struct attrs, required any value, required boolean combine ) {}
	/**
	 * Internal function.
	 */
	public string function $yearMonthHourMinuteSecondSelectTag( required string name, required string value, required any includeBlank, required string label, required string labelPlacement, required string prepend, required string append, required string prependToLabel, required string appendToLabel, string errorElement, string errorClass, required string $type, required any $loopFrom, required any $loopTo, required string $id, required any $step, string $optionNames, boolean twelveHour, date $now, any encode ) {}
	/**
	 * Internal function.
	 */
	public string function $yearMonthHourMinuteSecondSelectTagContent( any encode ) {}
	/**
	 * Internal function.
	 */
	public string function $ampmSelectTag( required string name, required string value, required string $id, date $now ) {}
	public numeric function $resolveDateTime( required string dateTimeString, required date dateTimeValue ) {}
}
