// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/view/formsobject.cfc — do not edit.
component {
	property = arguments.property, valueToAppend = local.valueToAppend );
	/**
	 * Builds and returns a string containing a text field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName The variable name of the object to build the form control for.
	 * @property The name of the property to use in the form control.
	 * @association The name of the association that the property is located on. Used for building nested forms that work with nested properties. If you are building a form with deep nesting, simply pass in a list to the nested object, and Wheels will figure it out.
	 * @position The position used when referencing a hasMany relationship in the association argument. Used for building nested forms that work with nested properties. If you are building a form with deep nestings, simply pass in a list of positions, and Wheels will figure it out.
	 * @label The label text to use in the form control.
	 * @labelPlacement Whether to place the label before, after, or wrapped around the form control. Label text placement can be controlled using aroundLeft or aroundRight.
	 * @prepend String to prepend to the form control. Useful to wrap the form control with HTML tags.
	 * @append String to append to the form control. Useful to wrap the form control with HTML tags.
	 * @prependToLabel String to prepend to the form control's label. Useful to wrap the form control with HTML tags.
	 * @appendToLabel String to append to the form control's label. Useful to wrap the form control with HTML tags.
	 * @errorElement HTML tag to wrap the form control with when the object contains errors.
	 * @errorClass The class name of the HTML tag that wraps the form control when there are errors.
	 * @includeErrorMessage When true, nest errorMessageOn() inside the field's error wrapper after the control. When omitted, the app-level includeFormErrorMessages setting is used (false unless the app opts in).
	 * @type Input type attribute. Common examples in HTML5 and later are text (default), email, tel, and url.
	 * @labelClass String added to the label's class.
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function textField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, string type, any encode ) {}
	/**
	 * Builds and returns a string containing a password field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function passwordField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing an email field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function emailField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a URL field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function urlField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a number field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @min Minimum allowed value.
	 * @max Maximum allowed value.
	 * @step Stepping interval.
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function numberField( required any objectName, required string property, string association, string position, string min, string max, string step, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a telephone field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function telField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a date field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @min Minimum allowed date (YYYY-MM-DD format).
	 * @max Maximum allowed date (YYYY-MM-DD format).
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function dateField( required any objectName, required string property, string association, string position, string min, string max, string step, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a color picker form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function colorField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a range slider form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @min Minimum allowed value.
	 * @max Maximum allowed value.
	 * @step Stepping interval.
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function rangeField( required any objectName, required string property, string association, string position, string min, string max, string step, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a search field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function searchField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a hidden field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function hiddenField( required any objectName, required string property, string association, string position, boolean encode ) {}
	/**
	 * Builds and returns a string containing a file field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function fileField( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a text area field form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function textArea( required any objectName, required string property, string association, string position, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a radio button form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @tagValue The value of the radio button when selected.
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function radioButton( required any objectName, required string property, string association, string position, string tagValue, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a check box form control based on the supplied name.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @checkedValue Value of check box in its checked state.
	 * @uncheckedValue The value of the check box when it's on the unchecked state.
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function checkBox( required any objectName, required string property, string association, string position, string checkedValue, string uncheckedValue, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Builds and returns a string containing a select form control based on the supplied objectName and property.
	 * Note: Pass any additional arguments like class, rel, and id, and the generated tag will also include those values as HTML attributes.
	 *
	 * [section: View Helpers]
	 * [category: Form Object Functions]
	 *
	 * @objectName [see:textField].
	 * @property [see:textField].
	 * @association [see:textField].
	 * @position [see:textField].
	 * @options A collection to populate the select form control with. Can be a query recordSet or an array of objects.
	 * @includeBlank Whether to include a blank option in the select form control. Pass true to include a blank line or a string that should represent what display text should appear for the empty value (for example, "- Select One -").
	 * @valueField The column or property to use for the value of each list element. Used only when a query or array of objects has been supplied in the options argument.  Required when specifying `textField`
	 * @textField The column or property to use for the value of each list element that the end user will see. Used only when a query or array of objects has been supplied in the options argument. Required when specifying `valueField`
	 * @multiple Whether to allow multiple options to be selected. Pass true to create a multi-select box.
	 * @label [see:textField].
	 * @labelPlacement [see:textField].
	 * @prepend [see:textField].
	 * @append [see:textField].
	 * @prependToLabel [see:textField].
	 * @appendToLabel [see:textField].
	 * @errorElement [see:textField].
	 * @errorClass [see:textField].
	 * @encode [see:styleSheetLinkTag].
	 */
	public string function select( required any objectName, required string property, string association, string position, any options, any includeBlank, string valueField, string textField, string label, string labelPlacement, string prepend, string append, string prependToLabel, string appendToLabel, string errorElement, string errorClass, any encode ) {}
	/**
	 * Creates multiple HTML "option" elements.
	 */
	public string function $optionsForSelect( required any options, required string valueField, required string textField, required any encode ) {}
	/**
	 * Resolve the value/text columns for a query passed to $optionsForSelect:
	 * infer them from the first numeric and first non-numeric column when they
	 * aren't provided.
	 */
	public struct function $optionsForSelectColumns( required any options, required string valueField, required string textField ) {}
	/**
	 * Resolve the option value/text for a single array cell passed to
	 * $optionsForSelect (simple value, [value,text] pair, {value,text} struct,
	 * object, or single-key struct). Returns the resolved fields plus any
	 * valueField/textField inferred while inspecting an object cell.
	 */
	public struct function $optionsForSelectCell( required any cell, required string valueField, required string textField ) {}
	/**
	 * Creates an HTML "option" element.
	 */
	public string function $option( required string objectValue, required string optionValue, required string optionText, required any encode, boolean multiple ) {}
}
