// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/content/CategoryService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Category service for contentbox
 */
component extends="cborm.models.VirtualEntityService" {
	property name="htmlHelper" inject="HTMLHelper@coldbox";
	property name="contentService" inject="contentService@contentbox";
	property name="dateUtil" inject="DateUtil@contentbox";
	variables.contentService = new contentbox.models.content.ContentService();
	/**
	 * Constructor
	 */
	contentbox.models.content.CategoryService function init() {}
	/**
	 * Category search with filters
	 *
	 * @search    The search term for the name
	 * @siteID    The site id to filter on
	 * @isPublic  Filter on this public (true) / private (false) or all (null)
	 * @max       The max records
	 * @offset    The offset to use
	 * @sortOrder The sort order
	 *
	 * @return struct of { count, categories }
	 */
	struct function search( search, siteID, boolean isPublic, max, offset, sortOrder ) {}
	/**
	 * This function allows you to receive a category object from a site and
	 * tries to see if it exists in a new site via slug comparison.
	 * If it exists, it returns it, else it creates it and returns it.
	 *
	 * @category The target category object to check
	 * @site     The target site this category should be created in
	 *
	 * @return The target site category
	 */
	contentbox.models.content.Category function getOrCreate( required category, required site ) {}
	/**
	 * This function allows you to receive a category slug string from a site and
	 * tries to see if it exists in a new site via slug comparison.
	 * If it exists, it returns it, else it creates it and returns it.
	 *
	 * @category The target category slug to check
	 * @site     The target site this category should be created in
	 *
	 * @return The target site category object
	 */
	contentbox.models.content.Category function getOrCreateBySlug( required string category, required site ) {}
	/**
	 * Get the total category counts for the entire installation or by site
	 *
	 * @siteID The site to filter on
	 */
	numeric function getTotalCategoryCount( string siteID ) {}
	/**
	 * Save a category in the system
	 *
	 * @category The category object
	 *
	 * @return The saved category
	 *
	 * @throws UniqueCategoryException
	 */
	function save( required category ) {}
	/**
	 * Verify an incoming slug is unique or not
	 *
	 * @slug       The slug to search for uniqueness
	 * @categoryId Limit the search to the passed categoryId usually for updates
	 * @siteID     The site to filter on
	 *
	 * @return True if the slug is unique or false if it's already used
	 */
	boolean function isSlugUnique( required any slug, any categoryID, string siteID ) {}
	/**
	 * Create categories via a comma delimited list and return the entities created
	 *
	 * @categories A list or array of categories to create
	 * @site       The site to attach them to, this must be a site object
	 * @isPublic   Create public or private categories
	 */
	array function createCategories( required categories, required site, boolean isPublic ) {}
	/**
	 * Inflate categories from a collection via 'category_X' pattern and returns an array of category objects
	 * as its representation. This is done by the content editors to display the categories for selection.
	 *
	 * @return array of categories
	 */
	array function inflateCategories( struct memento ) {}
	/**
	 * Delete a category which also removes itself from all many-to-many relationships
	 *
	 * @category The category object to remove from the system
	 */
	boolean function delete( required category ) {}
	/**
	 * Remove all content associations from a category and returns all the content objects it was removed from
	 * @category.hint The category object
	 */
	array function removeAllRelatedContent( required category ) {}
	/**
	 * Get all data prepared for export
	 *
	 * @site The site to export from
	 */
	array function getAllForExport( required site ) {}
	/**
	 * Get an array of names of all categories in the system or by site
	 *
	 * @siteId   The site to filter the names from
	 * @isPublic If passed, show by this filter, else all categories
	 */
	array function getAllNames( string siteID, boolean isPublic ) {}
	/**
	 * Get an array of slugs of all categories in the system
	 *
	 * @siteId   The site to filter the names from
	 * @isPublic If passed, show by this filter, else all categories
	 */
	array function getAllSlugs( string siteID, boolean isPublic ) {}
	/**
	 * Import data from a ContentBox JSON file. Returns the import log
	 *
	 * @importFile The json file to import
	 * @override   Override content if found in the database, defaults to false
	 *
	 * @return The console log of the import
	 *
	 * @throws InvalidImportFormat
	 */
	string function importFromFile( required importFile, boolean override ) {}
	/**
	 * Import data from an array of structures or a single structure of data
	 *
	 * @importData A struct or array of data to import
	 * @override   Override content if found in the database, defaults to false
	 * @importLog  The import log buffer
	 *
	 * @return The console log of the import
	 *
	 * @throws InvalidImportFormat
	 */
	string function importFromData( required importData, boolean override, importLog ) {}
}
