// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/content/ContentService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * A generic content service for content objects
 */
component extends="cborm.models.VirtualEntityService" {
	property name="settingService" inject="id:settingService@contentbox";
	property name="cacheBox" inject="cachebox";
	property name="customFieldService" inject="customFieldService@contentbox";
	property name="categoryService" inject="categoryService@contentbox";
	property name="commentService" inject="commentService@contentbox";
	property name="contentVersionService" inject="contentVersionService@contentbox";
	property name="authorService" inject="authorService@contentbox";
	property name="contentStoreService" inject="contentStoreService@contentbox";
	property name="pageService" inject="pageService@contentbox";
	property name="entryService" inject="entryService@contentbox";
	property name="systemUtil" inject="SystemUtil@contentbox";
	property name="statsService" inject="statsService@contentbox";
	property name="dateUtil" inject="DateUtil@contentbox";
	property name="commentSubscriptionService" inject="CommentSubscriptionService@contentbox";
	property name="subscriberService" inject="subscriberService@contentbox";
	property name="relocationService" inject="RelocationService@contentbox";
	property name="asyncManager" inject="coldbox:asyncManager";
	property = "contentID,title,slug,createdDate,modifiedDate" ) .asStruct() .list( sortOrder = arguments.sortOrder );
	variables.customFieldService = new contentbox.models.content.CustomFieldService();
	variables.categoryService = new contentbox.models.content.CategoryService();
	variables.contentVersionService = new contentbox.models.content.ContentVersionService();
	variables.contentStoreService = new contentbox.models.content.ContentStoreService();
	variables.pageService = new contentbox.models.content.PageService();
	variables.entryService = new contentbox.models.content.EntryService();
	variables.statsService = new contentbox.models.content.StatsService();
	variables.relocationService = new contentbox.models.content.RelocationService();
	/**
	 * Constructor
	 *
	 * @entityName The content entity name to bind this service to.
	 */
	contentbox.models.content.ContentService function init( entityName ) {}
	/**
	 * Get the total content counts according to the passed filters
	 *
	 * @siteID     The site to filter on
	 * @categoryId The category Id to filter on
	 */
	numeric function getTotalContentCount( siteID, categoryId ) {}
	/**
	 * Clear all content caches
	 *
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearAllCaches( boolean async ) {}
	/**
	 * Clear all category content counts caches
	 *
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearAllCategoryCountCaches( boolean async ) {}
	/**
	 * Clear all sitemap caches
	 *
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearAllSitemapCaches( boolean async ) {}
	/**
	 * Clear all page wrapper caches
	 *
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearAllPageWrapperCaches( boolean async ) {}
	/**
	 * Clear a specific page wrapper caches according to slug prefix
	 *
	 * @slug  The slug partial to clean on
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearPageWrapperCaches( required any slug, boolean async ) {}
	/**
	 * Clear a page wrapper cache for a specific content object
	 *
	 * @slug  The slug to clear
	 * @async Run it asynchronously or not, defaults to false
	 */
	contentbox.models.content.ContentService function clearPageWrapper( required any slug, boolean async ) {}
	/**
	 * Searches published content with cool paramters, remember published content only
	 *
	 * @searchTerm          The search term to search
	 * @max                 The maximum number of records to paginate
	 * @offset              The offset in the pagination
	 * @asQuery             Return as query or array of objects, defaults to array of objects
	 * @sortOrder           The sorting of the search results, defaults to publishedDate DESC
	 * @isPublished         Search for published, non-published or both content objects [true, false, 'all']
	 * @searchActiveContent Search only content titles or both title and active content. Defaults to both.
	 * @contentTypes        Limit search to list of content types (comma-delimited). Leave blank to search all content types
	 * @excludeIDs          List of IDs to exclude from search
	 * @showInSearch        If true, it makes sure content has been stored as searchable, defaults to null, which means it searches no matter what this bit says
	 * @siteID              The site ID to filter on
	 * @propertyList        A list of properties to retrieve as a projection instead of array of objects
	 *
	 * @return struct = { content, count }
	 */
	function searchContent( any searchTerm, numeric max, numeric offset, boolean asQuery, any sortOrder, any isPublished, boolean searchActiveContent, string contentTypes, any excludeIDs, boolean showInSearch, string siteID, string propertyList ) {}
	/**
	 * Get an id from a slug of a content object
	 *
	 * @slug   The slug to search an ID for.
	 * @siteID The site this slug belongs to
	 *
	 * @return The id of the content object or empty string if not found
	 */
	function getIdBySlug( required any slug, string siteID ) {}
	/**
	 * This utility tries to get the content type by id/slug or fails
	 *
	 * @return The found entity
	 *
	 * @throws EntityNotFound
	 */
	function getByIdOrSlugOrFail( required id ) {}
	/**
	 * Find a published content object by slug and published unpublished flags, if not found it returns
	 * a new content object
	 *
	 * @slug            The slug to search
	 * @showUnpublished To also show unpublished content, defaults to false.
	 * @siteID          The site this slug belongs to
	 *
	 * @return The content object or a new unpersisted content object
	 */
	function findBySlug( required any slug, required boolean showUnpublished, string siteID ) {}
	/**
	 * Verify an incoming slug is unique or not
	 *
	 * @slug        The slug to search for uniqueness
	 * @contentID   Limit the search to the passed contentID usually for updates
	 * @siteID      The site to filter on
	 * @contentType The content type uniqueness
	 *
	 * @return True if the slug is unique or false if it's already used
	 */
	boolean function isSlugUnique( required any slug, any contentID, string siteID, string contentType ) {}
	/**
	 * Delete a content object safely via hierarchies
	 *
	 * @content the Content object to delete
	 */
	contentbox.models.content.ContentService function delete( required any content ) {}
	/**
	 * Find published content objects by different filters and output formats
	 *
	 * @max        The maximum number of records to paginate
	 * @offset     The offset in the pagination
	 * @searchTerm The search term to search
	 * @category   The category to filter the content on
	 * @asQuery    Return as query or array of objects, defaults to array of objects
	 * @sortOrder  how we need to sort the results
	 * @parent     The parentID or parent entity to filter on, don't pass or pass an empty value to ignore, defaults to 'all'
	 * @slugPrefix If passed, this will do a hierarchical search according to this slug prefix. Remember that all hierarchical content's slug field contains its hierarchy: /products/awesome/product1. This prefix will be appended with a `/`
	 * @siteID     If passed, filter by site id
	 * @properties The list of properties to project on instead of giving you full object graphs
	 * @authorID   The authorID to filter on
	 * @criteria   The criteria object to use if passed, else we create a new one.
	 * @slugSearch If passed, we will search for content items with this field as a full text search on slugs
	 *
	 * @return struct as { count, content }
	 */
	function findPublishedContent( numeric max, numeric offset, any searchTerm, any category, boolean asQuery, string sortOrder, any parent, string slugPrefix, string siteID, string properties, string authorID, any criteria, string slugSearch ) {}
	/**
	 * Bulk Publish Status Updates
	 *
	 * @contentID The list or array of ID's to bulk update
	 * @status    The status either 'publish' or 'draft'
	 */
	any function bulkPublishStatus( required any contentID, required any status ) {}
	/**
	 * Get all the expired content in the system by filters
	 *
	 * @author The author filtering if passed.
	 * @max    The maximum number of records to return
	 * @offset The pagination offset
	 * @siteID The site to filter on
	 */
	array function findExpiredContent( any author, numeric max, numeric offset, string siteID ) {}
	/**
	 * Get all the future published content in the system by filters
	 *
	 * @author The author filtering if passed.
	 * @max    The maximum number of records to return
	 * @offset The pagination offset
	 * @siteID The site to filter on
	 */
	array function findFuturePublishedContent( any author, numeric max, numeric offset, string siteID ) {}
	/**
	 * Get latest edits according to criteria
	 *
	 * @author      The author object to use for retrieval
	 * @isPublished If passed, check if content is published or in draft mode. Else defaults to all states
	 * @max         The maximum number of records to return
	 * @siteID      The site to get edits from
	 */
	array function getLatestEdits( any author, boolean isPublished, numeric max, string siteID ) {}
	/**
	 * Get the top visited content entries
	 *
	 * @max    The maximum to retrieve, defaults to 5 entries
	 * @siteID The site to filter on
	 *
	 * @return An array of structures with contentId, label and hits keys
	 */
	array function getTopVisitedContent( numeric max, string siteID ) {}
	/**
	 * Get the top commented content entries
	 *
	 * @max    The maximum to retrieve, defaults to 5 entries
	 * @siteID The site to filter on
	 */
	array function getTopCommentedContent( numeric max, string siteID ) {}
	/**
	 * Get all content for export as flat data
	 *
	 * @inData The data to use for exporting, usually concrete implementtions can override this.
	 */
	array function getAllForExport( any inData ) {}
	/**
	 * Import data from a ContentBox JSON file. Returns the import log
	 *
	 * @importFile The json file to import
	 * @override   Override content if found in the database, defaults to false
	 *
	 * @return The console log of the import
	 *
	 * @throws InvalidImportFormat
	 */
	string function importFromFile( required importFile, boolean override ) {}
	/**
	 * Import data from an array of structures or a single structure of data
	 *
	 * @importData A struct or array of data to import
	 * @override   Override content if found in the database, defaults to false
	 * @importLog  The import log buffer
	 * @site       If passed, we use this specific site, else we discover it via content data
	 *
	 * @return The console log of the import
	 */
	string function importFromData( required importData, boolean override, required importLog, site ) {}
	/**
	 * Import a content object from a ContentBox JSON structure
	 *
	 * @contentData The content structure inflated from JSON
	 * @importLog   The string builder import log
	 * @parent      If the inflated content object has a parent then it can be linked directly, no inflating necessary. Usually for recursions
	 * @newContent  Map of new content by slug; useful for avoiding new content collisions with recusive relationships
	 * @site        The site we are using for the content
	 * @override    Are we overriding persisted data or not?
	 *
	 * @return The content object representing the struct
	 */
	any function importFromStruct( required any contentData, required any importLog, any parent, struct newContent, required site, boolean override ) {}
	/**
	 * Update a content's hits with some async flava
	 *
	 * @content A content object or id to update the hits on
	 * @async   Async or not
	 */
	contentbox.models.content.ContentService function updateHits( required content, boolean async ) {}
	/**
	 * Returns an array of slugs of all the content objects in the system.
	 */
	array function getAllFlatSlugs() {}
	/**
	 * Returns an array of [contentID, title, slug, createdDate, modifiedDate] structures of all the content in the system
	 *
	 * @sortOrder    The sort ordering of the results
	 * @isPublished  Show all content or true/false published content
	 * @showInSearch Show all content or true/false showInSearch flag
	 * @siteID       The site id to use to filter on
	 *
	 * @return Array of content data {contentID, title, slug, createdDate, modifiedDate}
	 */
	array function getAllFlatContent( sortOrder, boolean isPublished, boolean showInSearch, string siteID, string contentType ) {}
	/**
	 * Adds a relocation for a content item
	 *
	 * @contentItem  the target to relocate to
	 * @originalSlug the URI from which to redirect
	 */
	contentbox.models.content.ContentService function addRelocation( required BaseContent contentItem, required string originalSlug ) {}
	/**
	 * Get the appropriate service by passed content type.
	 * If an invalid type is passed, we return ourselves
	 *
	 * @type The content type to detect
	 */
	private contentbox.models.content.ContentService function getServiceByType( required type ) {}
	/**
	 * Get a unique slug hash
	 *
	 * @slug The slug to unique it
	 */
	private function getUniqueSlugHash( required string slug ) {}
}
