// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/content/EntryService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Manages blog entry content
 */
component extends="contentbox.models.content.ContentService" {
	property name="contentService" inject="id:ContentService@contentbox";
	variables.contentService = new contentbox.models.content.ContentService();
	/**
	 * Constructor
	 */
	contentbox.models.content.EntryService function init() {}
	/**
	 * Save an entry
	 *
	 * @entry        The entry to save or update
	 * @originalSlug The original slug if the save is an update
	 *
	 * @return Saved entry
	 */
	function save( required any entry, string originalSlug ) {}
	/**
	 * Search for blog entries according to many filters
	 *
	 * @search              The search term to search on
	 * @isPublished         Boolean bit to search if page is published or not, pass 'any' or not to ignore. Default is `any`
	 * @author              The authorID to filter on, pass 'all' to ignore filter
	 * @creator             The creatorID to filter on, don't pass or pass an empty value to ignore, defaults to 'all'
	 * @category            The categorie(s) to filter on. You can also pass 'all' or 'none'
	 * @max                 The maximum records to return
	 * @offset              The offset on the pagination
	 * @sortOrder           Sorting of the results, defaults to page title asc
	 * @searchActiveContent If true, it searches title and content on the page, else it just searches on title
	 * @showInSearch        If true, it makes sure content has been stored as searchable, defaults to false, which means it searches no matter what this bit says
	 * @siteId              The site ID to filter on
	 * @propertyList        A list of properties to retrieve as a projection instead of array of objects
	 *
	 * @return struct of { entries, count }
	 */
	struct function search( string search, string isPublished, string author, string creator, string category, numeric max, numeric offset, string sortOrder, boolean searchActiveContent, boolean showInSearch, string siteId, string propertyList ) {}
	/**
	 * Get a query report of entries archive
	 */
	function getArchiveReport() {}
	/**
	 * Find published entries by date filters
	 *
	 * @year    The year to filter on
	 * @month   The month to filter on
	 * @day     The day to filter on
	 * @max     The maximum records to return
	 * @offset  The offset on the pagination
	 * @asQuery Return query or array of structs
	 * @siteId  The site ID to filter on
	 *
	 * @return struct of { entries, count }
	 */
	function findPublishedEntriesByDate( numeric year, numeric month, numeric day, numeric max, numeric offset, boolean asQuery, string siteId ) {}
	/**
	 * Get all site content for export as flat data
	 *
	 * @site The site to get the export from
	 */
	array function getAllForExport( required site ) {}
}
