// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/ANSIConsoleAppender.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.coldbox.org | www.luismajano.com | www.ortussolutions.com
 *
 * Author     :	Brad Wood, Luis Majano
 * Date        :	07/22/2014
 * Description :
 * A logger for outputting ANSI-formatted text to the console
 * for use with CommandBox.
 *
 * Properties:
 * - none
 */
component extends="wirebox.system.logging.AbstractAppender" {
	variables.Shell = new commandbox.system.Shell();
	variables.printBuffer = new commandbox.system.util.PrintBuffer();
	variables.InteractiveJob = new commandbox.system.util.InteractiveJob();
	/**
	 * @name.hint The unique name for this appender.
	 * @properties.hint A map of configuration properties for the appender
	 * @layout.hint The layout class to use in this appender for custom message rendering.
	 * @levelMin.hint The default log level for this appender, by default it is 0. Optional. ex: LogBox.logLevels.WARN
	 * @levelMax.hint The default log level for this appender, by default it is 5. Optional. ex: LogBox.logLevels.WARN
	 */
	commandbox.system.util.ANSIConsoleAppender function init( required name, properties, layout, levelMin, leveMax ) {}
	function logMessage( required logEvent ) {}
	commandbox.system.Shell function getShell() {}
	commandbox.system.util.PrintBuffer function print() {}
	commandbox.system.util.InteractiveJob function job() {}
}
