// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/CommandDSL.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano
 *
 * I am a helper object for executing commands via a DSL.  Create me and call my
 * methods to build up a command chain, then .run() will execute me.
 *
 * I am a transient and hold state.  Do not share me with your friends.
 */
component {
	property name='command';
	property name='params';
	property name='piped';
	property name='flags';
	property name='append';
	property name='overwrite';
	property name='workingDirectory';
	property name='rawParams';
	property name='paramsType';
	property name='returnOutput';
	property name='pipedInput';
	property name='echo';
	property name='parser' inject='parser';
	property name='shell' inject='shell';
	property name="job" inject='interactiveJob';
	property name='ConsolePainter' inject='ConsolePainter';
	variables.parser = new commandbox.system.util.Parser();
	variables.job = new commandbox.system.util.InteractiveJob();
	variables.ConsolePainter = new commandbox.system.util.ConsolePainter();
	/**
	 * Create a new, executable command
	 *
	 * @name.hint I am the command to execute
	 */
	commandbox.system.util.CommandDSL function init( name ) {}
	/**
	 * Add params to the command
	 */
	commandbox.system.util.CommandDSL function params() {}
	/**
	 * Convert params to named or positional arguments
	 */
	private array function processParams() {}
	/**
	 * Add flags to the command
	 */
	commandbox.system.util.CommandDSL function flags() {}
	/**
	 * Append results to file
	 */
	commandbox.system.util.CommandDSL function append( required path ) {}
	/**
	 * overwrite file with results
	 */
	commandbox.system.util.CommandDSL function overwrite( required path ) {}
	/**
	 * Sets the directory to run the command in
	 */
	commandbox.system.util.CommandDSL function inWorkingDirectory( required workingDirectory ) {}
	/**
	 * Pipe additional commands
	 */
	commandbox.system.util.CommandDSL function pipe( commandDSL ) {}
	/**
	 * Turn this CFC into an array of command tokens
	 */
	array function getTokens() {}
	/**
	 * Turn this CFC into a string representation
	 */
	string function getCommandString() {}
	/**
	 * Run this command
	 */
	string function run( returnOutput, string piped, boolean echo, boolean rawParams ) {}
}
