// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/DataConverter.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Scott Steinbeck
 *
 * Utilities converting data between formats
 */
component {
	/**
	 * Constructor
	 */
	commandbox.system.util.DataConverter function init() {}
	/**
	 * Take any data and convert it to a query
	 * @data Any type of data for the table.
	 */
	public query function toQuery( required any rawData, string columns ) {}
	/**
	 * Take a simple value/array of values/or struct and normalize it to fit the table printer format
	 * @data Any type of data for the table.
	 */
	public array function normalizeData( required any rawData ) {}
	/**
	 * Create column names from data, default to col_1 ... for simple values and arrays,
	 * Use key names for structs
	 * @data Any type of data for the table.
	 */
	public array function generateColumnNames( required any data, string columns ) {}
	/**
	 * Takes query object and returns array of ORDERED structs
	 * // https://luceeserver.atlassian.net/browse/LDEV-3511
	 *
	 * @data Any query object
	 */
	function queryToArrayOfOrderedStructs( query data ) {}
	function cellHasFormattingEmbedded( data ) {}
}
