// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/ForgeBox.cfc — do not edit.
/**
 * ForgeBox API REST Wrapper
 */
component {
	property name="progressableDownloader" inject="ProgressableDownloader";
	property name="progressBar" inject="ProgressBar";
	property name="CommandBoxlogger" inject="logbox:logger:{this}";
	property name="configService" inject="configService";
	property name="endpointURL";
	property name="APIURL";
	property name="endpointName";
	variables.progressableDownloader = new commandbox.system.util.ProgressableDownloader();
	variables.progressBar = new commandbox.system.util.ProgressBar();
	variables.configService = new commandbox.system.services.ConfigService();
	/**
	 * Constructor
	 */
	public commandbox.system.util.ForgeBox function init() {}
	/**
	 * Get an array of entry types
	 */
	public any function getTypes( string APIToken ) {}
	/**
	 * Get an array of entry types, locally first else goes and retrieves them
	 */
	public any function getCachedTypes( boolean force, string APIToken ) {}
	/**
	 * Get entries
	 * @orderBy The type to order by, look at this.ORDERBY
	 * @maxrows Max rows to return
	 * @startRow StartRow
	 * @typeSlug The type slug to filter on
	 * @searchTerm String to search on
	 */
	public any function getEntries( string orderBy, numeric maxrows, numeric startRow, string typeSlug, string searchTerm, string APIToken ) {}
	/**
	 * Get an entry from forgebox by slug
	 * @slug The entry slug to retrieve
	 */
	public struct function getEntry( required string slug, string APIToken ) {}
	/**
	 * Verifies if a slug is available
	 * @slug The entry slug to verify
	 */
	public boolean function isSlugAvailable( required string slug, string APIToken ) {}
	/**
	 * Registers a new user in ForgeBox
	 */
	function register( required string username, required string password, required string email, required string fName, required string lName, string APIToken ) {}
	/**
	 * Look up user based on API Token
	 */
	function whoami( required string APIToken ) {}
	/**
	 * Get pre-signed uploaed URL
	 */
	function storeUrl( required string slug, required string version, required string APIToken ) {}
	/**
	 * set user config
	 */
	function setConfig( required struct config, required string username, required string APIToken ) {}
	/**
	 * set user config
	 */
	function getConfig( required string username, required string APIToken ) {}
	/**
	 * Authenticates a user in ForgeBox
	 */
	function login( required string username, required string password ) {}
	/**
	 * Publishes a package in ForgeBox
	 */
	function publish( required string slug, required boolean private, required string version, required string boxJSON, required string isStable, string description, string descriptionFormat, string installInstructions, string installInstructionsFormat, string changeLog, string changeLogFormat, required string APIToken, string zipPath, boolean forceUpload, string binaryHash ) {}
	/**
	 * Unpublishes a package
	 */
	function unpublish( required string slug, string version, required string APIToken ) {}
	/**
	 * Tracks an install
	 */
	function recordInstall( required string slug, string version, string APIToken ) {}
	/**
	 * Autocomplete for slugs
	 */
	function slugSearch( required string searchTerm, string typeSlug, string APIToken ) {}
	function getStorageLocation( required string slug, required string version, required string APIToken ) {}
	/**
	 * Invoke a ForgeBox REST Call
	 * @method The HTTP method to invoke
	 * @resource The resource to hit in the forgebox service.
	 * @body The body content of the request if passed.
	 * @headers An struct of HTTP headers to send
	 * @parameters An struct of HTTP URL parameters to send in the request
	 * @timeout The default call timeout
	 * @formFields A struct of form fields to send
	 * @files A struct of files to send
	 * @multipart Whether the request needs to be multipart/form-data
	 */
	private struct function makeRequest( string method, string resource, any body, struct headers, struct parameters, numeric timeout, struct formFields, struct files, boolean multipart ) {}
}
