// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/InteractiveJob.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano
 *
 * I help update the user's console with progress for a currently executing (foreground)
 * job in a nice and tidy way.
 */
component {
	property name='jobs' type='array';
	property name='active' type='boolean';
	property name='dumpLog' type='boolean';
	property name='startTime' type='numeric';
	property name='animation' type='numeric';
	property name='shell' inject='shell';
	property name='printBuffer' inject='printBuffer';
	property name='print' inject='print';
	property name='ConsolePainter' inject='provider:ConsolePainter';
	variables.printBuffer = new commandbox.system.util.PrintBuffer();
	variables.print = new commandbox.system.util.Print();
	variables.ConsolePainter = new commandbox.system.util.ConsolePainter();
	commandbox.system.util.InteractiveJob function init() {}
	function onDIComplete() {}
	/**
	 * Reset the internal state of this job
	 */
	commandbox.system.util.InteractiveJob function reset() {}
	/**
	 * Clear from the screen, but don't reset
	 */
	commandbox.system.util.InteractiveJob function clear() {}
	/**
	 * Add a line of logging.  Feel free to use ANSI formatting
	 *
	 * @line Message to log
	 */
	commandbox.system.util.InteractiveJob function addLog( required string line, string color ) {}
	/**
	 * Convenience method to log a red message
	 *
	 * @line Message to log
	 */
	function addErrorLog( required string line ) {}
	/**
	 * Convenience method to log a yellow message
	 *
	 * @line Message to log
	 */
	function addWarnLog( required string line ) {}
	/**
	 * Convenience method to log a green message
	 *
	 * @line Message to log
	 */
	function addSuccessLog( required string line ) {}
	/**
	 * Mark job as completed.  This will print out any final permanent lines and clear the state
	 *
	 * @dumpLog Dump out all internal log lines permanently to the console
	 */
	commandbox.system.util.InteractiveJob function complete( boolean dumpLog ) {}
	/**
	 * Mark job as Failed.  This will print out any final permanent lines and clear the state
	 *
	 * @dumpLog Dump out all internal log lines permanently to the console
	 */
	commandbox.system.util.InteractiveJob function error( string message, boolean dumpLog ) {}
	/**
	 * Cancel all remaining jobs and mark with error
	 *
	 * @message Error message to be applied to the current job
	 */
	commandbox.system.util.InteractiveJob function errorRemaining( message ) {}
	/**
	 * Kick off a job.  Clears any previous state and starts drawing
	 *
	 * @name Name of the job
	 */
	commandbox.system.util.InteractiveJob function start( required string name, logSize ) {}
	/**
	 * Outputs final representation of job to console for good
	 * Resets the internal state this CFC so all job data is gone
	 * and there is no active job.
	 *
	 * @dumpLog Include all log messages in output regardless of logSize
	 */
	private function finalizeOutput( boolean dumpLog ) {}
	/**
	 * Render the information to the console
	 */
	commandbox.system.util.InteractiveJob function draw() {}
	/**
	 * Returns array of AttributedString objects that represent this job and its children's current state
	 *
	 * @job Reference to a job struct so this method can be called recursively
	 * @includeAllLogs Ignore logSize and include all log lines
	 * @finalOutput True if getting final output at the completion of the job.
	 */
	array function getLines( job, includeAllLogs, finalOutput ) {}
	/**
	 * Returns colored and formatted job title
	 *
	 * @job Job struct to use
	 */
	private string function getJobTitle( job ) {}
	/**
	 * Returns a character to aninmate for running jobs
	 */
	function runningAnimation() {}
	/**
	 * Returns name of color for current job status
	 *
	 * @job Job struct to use
	 */
	private string function statusColor( job ) {}
	/**
	 * Returns empty struct of default job details
	 *
	 * @name Name of job
	 * @logSize Size of the log to display
	 */
	private struct function newJob( name, logSize ) {}
	/**
	 * Get struct that represents the currently executing job.
	 */
	private struct function getCurrentJob() {}
	/**
	 * Get number that represents the depth of the currently executing job.
	 */
	numeric function getCurrentJobDepth() {}
	/**
	 * Is there an active job?
	 */
	boolean function isActive() {}
}
