// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/PrintBuffer.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 *
 * I am a helper object that wraps the print helper.  Instead of returning
 * text, I accumulate it in a variable that can be retrieved at the end.
 */
component extends="commandbox.system.util.Print" {
	property name="shell" inject="shell";
	property name="job" inject="interactiveJob";
	property name='SystemSettings' inject='SystemSettings';
	property name="objectID";
	/**
	 * Result buffer
	 */
	property name="result";
	variables.job = new commandbox.system.util.InteractiveJob();
	variables.SystemSettings = new commandbox.system.util.SystemSettings();
	commandbox.system.util.PrintBuffer function init() {}
	function toConsole() {}
	function clear() {}
	function getResult() {}
	commandbox.system.util.PrintBuffer function onMissingMethod( missingMethodName, missingMethodArguments ) {}
	/**
	 * Outputs a table to the screen
	 * @headers An array of column headers, or a query.  When passing a query, the "data" argument is not used.
	 * @data An array of data for the table.  Each item in the array may either be
	 * an array in the correct order matching the number of headers or a struct
	 * with keys matching the headers.
	 * @includeHeaders A list of headers to include.  Used for query inputs
	 */
	commandbox.system.util.PrintBuffer function table( required any data, any includedHeaders, any headerNames, boolean debug ) {}
	commandbox.system.util.PrintBuffer function columns( required array items, formatUDF ) {}
	/**
	 * Print a struct of structs as a tree
	 *
	 * @data top level struct
	 * @formatUDF A UDF receiving both a string-concatenated prefix of keys, and an array of the same data.  Returns string of special formating for that node of the tree
	 */
	commandbox.system.util.PrintBuffer function tree( required struct data, formatUDF ) {}
}
