// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/TablePrinter.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Scott Steinbeck
 *
 * I print tables
 */
component {
	property name="print" inject="PrintBuffer";
	property name="shell" inject="shell";
	property name="convert" inject="DataConverter";
	property name="job" inject="InteractiveJob";
	variables.print = new commandbox.system.util.PrintBuffer();
	variables.shell = new commandbox.system.Shell();
	variables.convert = new commandbox.system.util.DataConverter();
	variables.job = new commandbox.system.util.InteractiveJob();
	/**
	 * Outputs a table to the screen
	 * @data Any type of data for the table.  Each item in the array may either be an array in the correct order matching the number of headers or a struct with keys matching the headers.
	 * @includedHeaders A list of headers to include.  Used for query inputs
	 * @headerNames An list/array of column headers to use instead of the default
	 * @debug Only print out the names of the columns and the first row values
	 * @width Override the terminal width
	 */
	public string function print( required any data, any includedHeaders, any headerNames, boolean debug, width ) {}
	/**
	 * Outputs a table to the screen
	 * @headers An array of column headers,
	 * @data An array of data for the table.
	 * @headerNames Header name overrides
	 */
	public array function processHeaders( required array headers, required array data, headerNames, width ) {}
	/**
	 * Calculates the max width of a column across the header and all rows of data.
	 * This value is used to layout the table correctly.
	 * @index The index of the column we are calculating.
	 * @header The column header.
	 * @data The data for the table.
	 * @headerNames Header name overrides
	 */
	private struct function calculateColumnData( required numeric index, required string header, required array data, array headerNames ) {}
	/**
	 * Prints the header row for the table.
	 * @headerData The array of column headers for the table with their corresponding max widths.
	 * @print A reference to the CommandBox Printer that called this table printer.
	 */
	private void function printHeader( required array headerData ) {}
	/**
	 * Prints all the data for the table.
	 * @data The data for the table.
	 * @headerData The array of column headers for the table with their corresponding max widths.
	 * @print A reference to the CommandBox Printer that called this table printer.
	 */
	private void function printData( required array data, required array headerData ) {}
	/**
	 * Prints a single row of data for the table.
	 * @row A single row of data for the table.
	 * @headerData The array of column headers for the table with their corresponding max widths.
	 */
	private void function printRow( required array row, required array headerData ) {}
	/**
	 * Prints the separator between rows.
	 * @headerData The array of column headers for the table with their corresponding max widths.
	 * @print A reference to the CommandBox Printer that called this table printer.
	 */
	private void function printRowSeparator( required array headerData ) {}
	/**
	 * Prints the final line of the table.
	 * @headerData The array of column headers for the table with their corresponding max widths.
	 * @print A reference to the CommandBox Printer that called this table printer.
	 */
	private void function printTableEnd( required array headerData ) {}
	/**
	 * Formats the data into an array of arrays.
	 * If the data is an array of structs, the headers will be used to convert it to an array of arrays.
	 * @data The data for the table.
	 * @headers The column headers for the table.  Used as the lookup keys if data is an array of structs.
	 */
	private array function autoFormatData( required array headers, required array data ) {}
	/**
	 * Gets the required keys from the struct of data and returns them as an array of arrays.
	 * @item The struct of data representing a single row.
	 * @headers The column headers for the table used to get the needed data from the item in the correct order.
	 */
	private array function getStructValues( required struct item, required array headers ) {}
	/**
	 * Adds characters to the right of a string until the string reaches a certain length.
	 * If the text is already greater than or equal to the maxWidth, the text is returned unchanged.
	 * @text The text to pad.
	 * @maxWidth The number of characters to pad up to.
	 * @padChar The character to use to pad the text.
	 */
	private string function padRight( required string text, required numeric maxWidth, string padChar ) {}
	function stringify( any data ) {}
	function cellHasFormattingEmbedded( data ) {}
}
