// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/TaskDSL.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano
 *
 * I am a helper object for executing tasks via a DSL.  Create me and call my
 * methods to build up an execution, then .run() will execute me.
 *
 * I am a transient and hold state.  Do not share me with your friends.
 */
component {
	property name='taskFile';
	property name='target';
	property name='params';
	property name='target';
	property name='flags';
	property name='workingDirectory';
	property name='rawParams';
	property name='exitCode';
	property name='parser' inject='parser';
	property name='shell' inject='shell';
	property name='wirebox' inject='wirebox';
	property name="job" inject='interactiveJob';
	variables.parser = new commandbox.system.util.Parser();
	variables.shell = new commandbox.system.Shell();
	variables.job = new commandbox.system.util.InteractiveJob();
	/**
	 * Create a new, executable task
	 *
	 * @taskFile.hint I am the task to execute
	 */
	commandbox.system.util.TaskDSL function init( taskFile ) {}
	/**
	 * Add params to the task
	 */
	commandbox.system.util.TaskDSL function target( target ) {}
	/**
	 * Add params to the command
	 */
	commandbox.system.util.TaskDSL function params() {}
	/**
	 * Convert params to named or positional arguments
	 */
	private array function processParams() {}
	/**
	 * Add flags to the command
	 */
	commandbox.system.util.TaskDSL function flags() {}
	/**
	 * Sets the directory to run the task in
	 */
	commandbox.system.util.TaskDSL function inWorkingDirectory( required workingDirectory ) {}
	/**
	 * Turn this CFC into an array of command tokens
	 */
	array function getTokens() {}
	/**
	 * Turn this CFC into a string representation
	 */
	string function getCommandString() {}
	/**
	 * Run this command
	 */
	string function run( returnOutput, boolean echo, boolean rawParams ) {}
}
