// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/async/AsyncManager.cfc — do not edit.
/**
 * The ColdBox Async Manager is in charge of creating runnable proxies based on
 * components or closures that can be spawned as native Java Completable futures
 * to support you with multi-threaded and asynchronous programming.
 *
 * The manager can also help you create executor services (queues or work pools) so you can define your own
 * thread pools according to your needs.  If not, the majority of the asynchronous
 * methods will use the ForkJoin.commonPool() implementation.
 *
 * Every ColdBox application has a single AsyncManager loaded with 1 work queue created
 * mostly for internal ColdBox operations: `coldbox-tasks` with 20 threads.
 *
 * However, you can define as many executor pools in your configuration file and ColdBox will
 * manage them for you via this Async Manager.
 *
 * Welcome to the world of async and parallel programming!
 */
component {
	/**
	 * A collection of executors you can register in the async manager
	 * so you can run queues, tasks or even scheduled tasks
	 */
	property name="executors" type="struct";
	/**
	 * This scheduler can be linked to a ColdBox context
	 */
	property name="coldbox";
	this.$executors = new coldbox.system.async.executors.ExecutorBuilder();
	/**
	 * Constructor
	 *
	 * @debug Add debugging logs to System out, disabled by default
	 */
	coldbox.system.async.AsyncManager function init( boolean debug ) {}
	/**
	 * Creates and registers an Executor according to the passed name, type and options.
	 * The allowed types are: fixed, cached, single, scheduled with fixed being the default.
	 *
	 * You can then use this executor object to submit tasks for execution and if it's a
	 * scheduled executor then actually execute scheduled tasks.
	 *
	 * Types of Executors:
	 * - cached : An unbounded pool where the number of threads will grow according to the tasks it needs to service. The threads are killed by a default 60 second timeout if not used and the pool shrinks back
	 * - fixed : By default it will build one with 20 threads on it. Great for multiple task execution and worker processing
	 * - fork_join : A pool that uses the ForkJoinPool.commonPool() by default, it is great for parallel tasks and recursive tasks
	 * - single : A great way to control that submitted tasks will execute in the order of submission: FIFO
	 * - scheduled : A pool to use for scheduled tasks that can run one time or periodically
	 * - work_stealing : A pool that allows you to run parallel tasks, it will use the ForkJoinPool.commonPool() by default
	 * - virtual : A pool that uses the VirtualThreadPerTaskExecutor, it is great for IO bound tasks and can run many tasks in parallel without blocking, requires Java 19+.
	 *
	 * @see            https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html
	 * @name           The name of the executor used for registration
	 * @type           The type of executor to build fixed, cached, single, scheduled, work_stealing, virtual
	 * @threads        How many threads to assign to the thread scheduler, default is 20
	 * @debug          Add output debugging
	 * @loadAppContext Load the CFML App contexts or not, disable if not used
	 * @parallelism    The number of parallel tasks to run at the same time, default is 0 which means no parallelism, only applies to work stealing executors
	 *
	 * @return The ColdBox Schedule class to work with the schedule: coldbox.system.async.executors.Executor
	 */
	Executor function newExecutor( required name, type, numeric threads, boolean debug, boolean loadAppContext, numeric parallelism ) {}
	/**
	 * Build a Java executor according to passed type and threads
	 *
	 * @see            https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/Executors.html
	 * @type           Available types are: fixed, fork_join, cached, single, scheduled, work_stealing, virtual, {WireBoxID}
	 * @threads        The number of threads to seed the executor with, if it allows it
	 * @debug          Add output debugging
	 * @loadAppContext Load the CFML App contexts or not, disable if not used
	 *
	 * @return A Java ExecutorService wrapped in a ColdBox Executor object
	 */
	Executor function buildExecutor( required type, numeric threads, boolean debug, boolean loadAppContext, numeric parallelism ) {}
	/**
	 * Shortcut to newExecutor( type: "scheduled" )
	 */
	Executor function newScheduledExecutor( required name, numeric threads, boolean debug, boolean loadAppContext ) {}
	/**
	 * Shortcut to newExecutor( type: "single", threads: 1 )
	 */
	Executor function newSingleExecutor( required name, boolean debug, boolean loadAppContext ) {}
	/**
	 * Shortcut to newExecutor( type: "cached" )
	 */
	Executor function newCachedExecutor( required name, numeric threads, boolean debug, boolean loadAppContext ) {}
	/**
	 * Get a registered executor registered in this async manager
	 *
	 * @name The executor name
	 *
	 * @return The executor object: coldbox.system.async.executors.Executor
	 *
	 * @throws ExecutorNotFoundException
	 */
	Executor function getExecutor( required name ) {}
	/**
	 * Get the array of registered executors in the system
	 *
	 * @return Array of names
	 */
	array function getExecutorNames() {}
	/**
	 * Verify if an executor exists
	 *
	 * @name The executor name
	 */
	boolean function hasExecutor( required name ) {}
	/**
	 * Delete an executor from the registry, if the executor has not shutdown, it will shutdown the executor for you
	 * using the shutdownNow() event
	 *
	 * @name The scheduler name
	 */
	coldbox.system.async.AsyncManager function deleteExecutor( required name ) {}
	/**
	 * Shutdown an executor or force it to shutdown, you can also do this from the Executor themselves.
	 * If an un-registered executor name is passed, it will ignore it
	 *
	 * @name    The name of the executor to shutdown
	 * @force   Use the shutdownNow() instead of the shutdown() method
	 * @timeout The timeout to use when force=false, to make sure all tasks finish gracefully. Deafult is 30 seconds.
	 */
	coldbox.system.async.AsyncManager function shutdownExecutor( required name, boolean force, numeric timeout ) {}
	/**
	 * Shutdown all registered executors in the system gracefully or not by using force = true
	 *
	 * @force   By default (false) it gracefully shuts them down, else uses the shutdownNow() methods
	 * @timeout The timeout to use when force=false, to make sure all tasks finish gracefully. Deafult is 30 seconds.
	 *
	 * @return AsyncManager
	 */
	coldbox.system.async.AsyncManager function shutdownAllExecutors( boolean force, numeric timeout ) {}
	/**
	 * Returns a structure of status maps for every registered executor in the
	 * manager. This is composed of tons of stats about the executor
	 *
	 * @name The name of the executor to retrieve th status map ONLY!
	 *
	 * @return A struct of metadata about the executor or all executors
	 */
	struct function getExecutorStatusMap( name ) {}
	/**
	 * Create a new ColdBox future backed by a Java completable future
	 *
	 * @value          The actual closure/lambda/udf to run with or a completed value to seed the future with
	 * @executor       A custom executor to use with the future, else use the default
	 * @debug          Add debugging to system out or not, defaults is false
	 * @loadAppContext Load the CFML engine context into the async threads or not, default is yes.
	 *
	 * @return ColdBox Future completed or new
	 */
	Future function newFuture( any value, any executor, boolean debug, boolean loadAppContext ) {}
	/**
	 * Create a completed ColdBox future backed by a Java Completable Future
	 *
	 * @value          The value to complete the future with
	 * @debug          Add debugging to system out or not, defaults is false
	 * @loadAppContext Load the CFML engine context into the async threads or not, default is yes.
	 *
	 * @return ColdBox Future completed
	 */
	Future function newCompletedFuture( required any value, boolean debug, boolean loadAppContext ) {}
	/**
	 * Alias to newFuture().all()
	 */
	Future function all() {}
	/**
	 * Alias to newFuture().allApply()
	 */
	any function allApply() {}
	/**
	 * Alias to newFuture().anyOf()
	 */
	Future function anyOf() {}
	/**
	 * Build out a scheduler object for usage within this async manager context and return it to you.
	 * You must manage it's persistence, we only wire it and create it for you so you can use it
	 * to schedule tasks.
	 *
	 * @name The unique name for the scheduler
	 */
	Scheduler function newScheduler( required name ) {}
	/**
	 * Build out a new Duration class
	 */
	Duration function duration() {}
	/**
	 * Build out a new Period class
	 */
	Period function period() {}
	/**
	 * Build an array out of a range of numbers or using our range syntax.
	 * You can also build negative ranges
	 *
	 * <pre>
	 * arrayRange( "1..5" )
	 * arrayRange( "-10..5" )
	 * arrayRange( 1, 500 )
	 * </pre>
	 *
	 * @from The initial index, defaults to 1 or you can use the {start}..{end} notation
	 * @to   The last index item
	 */
	array function arrayRange( any from, numeric to ) {}
	/**
	 * Utility to send to output to the output stream
	 *
	 * @var Variable/Message to send
	 */
	coldbox.system.async.AsyncManager function out( required var ) {}
	/**
	 * Utility to send to output to the error stream
	 *
	 * @var Variable/Message to send
	 */
	coldbox.system.async.AsyncManager function err( required var ) {}
}
