// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/Test.cfc — do not edit.
component extends="wheels.Global" {
	wheels.Test function init() {}
	/**
	 * Called from a test function.
	 * If expression evaluates to false, record a failure against the test.
	 *
	 * [section: Test Model]
	 * [category: Testing Functions]
	 *
	 * @expression String containing CFML expression to evaluate.
	 * @2..n String(s) containing space-delimited list of variables to evaluate and include in the failure message to help determine cause of failed assertion.
	 */
	public void function assert( required string expression ) {}
	/**
	 * Called from a test function to cause the test to fail.
	 * Will throw an exception resulting in a test failure along with an option message.
	 *
	 * @param message	Message to record in test results against failure.
	 */
	public void function fail( string message ) {}
	/**
	 * Used to examine an expression
	 * Any overloaded arguments get passed to cfdump's attributeCollection
	 *
	 * [section: Test Model]
	 * [category: Testing Functions]
	 *
	 * @expression The expression to examine
	 * @display  Whether to display the debug call. False returns without outputting anything into the buffer. Good when you want to leave the debug command in the test for later purposes, but don't want it to display
	 */
	public any function debug( required string expression, boolean display ) {}
	/**
	 * Catches a raised error and returns the error type
	 * Great if you want to	test that a certain exception will be raised.
	 *
	 * [section: Test Model]
	 * [category: Testing Functions]
	 *
	 * @expression String containing CFML expression to evaluate
	 */
	public string function raised( required string expression ) {}
	/**
	 * Run all the tests in a component.
	 *
	 * @param resultKey	Key to store distinct test result sets under in
	 * request scope, defaults to "test"
	 * @returns true if no errors
	 */
	public boolean function $runTest( string resultKey, string testname ) {}
	/**
	 * Builds the recorded message for a test error from a cfcatch object.
	 * Kept as a separate public helper (cross-engine invariant #7) so the
	 * catch block in $runTest never reads function-scoped locals — on Lucee 7
	 * reading a var-declared local inside a catch can fail with
	 * "variable [MESSAGE] doesn't exist" for certain exception shapes, which
	 * turned a single failing test into a suite-wide 500 (#3458).
	 *
	 * Every field read is guarded with StructKeyExists: native (Java)
	 * exceptions wrapped by the engine do not carry the full cfcatch shape.
	 *
	 * @e The cfcatch object describing the error.
	 */
	public string function $testErrorMessage( required any e ) {}
	/**
	 * Clear results.
	 *
	 * @param resultKey	Key to store distinct test result sets under in
	 * request scope, defaults to "test"
	 */
	public void function $resetTestResults( string resultKey ) {}
	/**
	 * Report test results at overall, test case and test level, highlighting
	 * failures and errors.
	 *
	 * @param resultKey	Key to retrieve distinct test result sets from in
	 * request scope, defaults to "test"
	 * @returns			HTML formatted test results
	 */
	public any function $results( string resultKey ) {}
	/**
	 * The function wheels uses to run tests
	 */
	public any function $wheelsRunner( struct options ) {}
	/**
	 * Args:
	 * component: path to the component you want to check as a valid test
	 * shouldExtend: if the component should extend a base component to be a valid test
	 */
	public boolean function $isValidTest( required string component, string shouldExtend ) {}
	/**
	 * Removes the base test directory from the test name to make them prettier and more readable.
	 */
	public string function $cleanTestCase( required string name, string path ) {}
	/**
	 * Cleans up the test name so they are more readable.
	 */
	public string function $cleanTestName( required string name ) {}
	/**
	 * Cleans up the test path.
	 */
	public string function $cleanTestPath( required string path ) {}
	/**
	 * This resolves all the paths needed to run the tests.
	 */
	public struct function $resolvePaths( struct options ) {}
	/**
	 * Returns a query containing all the test to run and their directory path.
	 */
	public query function $listTestPackages( struct options, string filter ) {}
	/**
	 * Initialises the test environment and populates test database.
	 */
	public void function $initialiseTestEnvironment( required struct paths, required struct options ) {}
	/**
	 * Seeds the test database.
	 */
	public void function $seedDatabase( required struct paths ) {}
	/**
	 * Returns true if a file path is a wheels core file.
	 */
	public any function $isCoreFile( required string path ) {}
	public any function $evaluateExpression( required string expression ) {}
	function onDIcomplete() {}
}
