// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/WheelsTest.cfc — do not edit.
/**
 * Base WheelsTest spec for Wheels tests.
 * Dynamically binds methods from `application.wo` into both
 * the `variables` and `this` scope for convenience.
 *
 * This is the primary base class for BDD-style tests in Wheels.
 * Extends: wheels.Testbox (deprecated) → wheels.WheelsTest (current)
 */
component extends="wheels.wheelstest.system.BaseSpec" {
	/**
	 * Bind application.wo's helpers into this instance (both variables and
	 * this scope). Runs from the pseudo-constructor above AND from init():
	 * RustCFML skips pseudo-constructor code when instantiating an
	 * already-compiled component directly (new wheels.WheelsTest()), so
	 * init() covers that path. The binding is idempotent, so engines that
	 * run both paths are unaffected.
	 */
	public any function $bindApplicationHelpers() {}
	/**
	 * Constructor — re-runs the helper binding so a directly instantiated
	 * WheelsTest works on engines that skip pseudo-constructor code for
	 * already-compiled components (RustCFML). Matches BaseSpec's remote
	 * access modifier, which Adobe requires of overrides.
	 */
	remote wheels.WheelsTest function init() {}
	/**
	 * Create a TestClient and visit the given path (HTTP GET).
	 * Returns the TestClient for fluent assertion chaining.
	 *
	 * Usage in tests:
	 * visit("/users").assertOk().assertSee("John")
	 *
	 * @path URL path to visit
	 */
	public any function visit( required string path ) {}
	/**
	 * Join a suffix onto the engine's temp directory with the separator
	 * normalized. RustCFML's GetTempDirectory() omits the trailing slash
	 * (Lucee and Adobe include it), so a bare concatenation produces a path
	 * at the filesystem root on Linux — `/tmpwheels-…` instead of
	 * `/tmp/wheels-…` — and every file operation fails with a permission
	 * error. Use this helper for BOTH construction and cleanup so the
	 * RemoveChars/Replace sweeps in specs' finally blocks key on the same
	 * normalized form.
	 */
	public string function $tempPath( required string suffix ) {}
	/**
	 * Delete a directory and everything in it, symlink-safe.
	 *
	 * `DirectoryDelete(path, recurse=true)` leaves the directory behind on
	 * Adobe CF 2023 when the tree contains a symlink — it throws "The specified
	 * directory ... cannot be deleted. This directory is not empty." — which
	 * errored the symlink-fixture specs (S4 and the mappings-escape spec in
	 * `hardener/PluginsHardenerShouldSpec.cfc`) on every adobe2023 matrix leg
	 * and cascaded into the specs that share the same fixture root.
	 *
	 * Walk the tree first and unlink symlinks with `java.nio.file.Files`, which
	 * removes the link itself instead of following it, then hand the now
	 * link-free tree to the plain recursive delete. On a JVM-free engine
	 * (RustCFML, which never builds symlink fixtures) the walk is a no-op and
	 * the recursive delete runs unchanged.
	 *
	 * @path Directory to remove. A path that does not exist is a no-op.
	 */
	public void function $removeTree( required string path ) {}
	/**
	 * Internal function for `$removeTree()`. Recursively deletes every symlink
	 * an entry points at, leaving real files and directories for the caller's
	 * recursive delete.
	 */
	private void function $unlinkSymlinks( required string path ) {}
	/**
	 * Return a configured TestClient instance.
	 * The base URL is auto-detected from the current server port.
	 *
	 * @testContext When true (default), send the isolation header + cookie so
	 * fixture HTTP binds the isolated test application (issue #3374). Pass
	 * false to address the live application (isolation specs).
	 */
	public any function $testClient( boolean testContext ) {}
	/**
	 * Auto-detect the base URL of the running test server. Resolved through
	 * a layered lookup mirroring BrowserTest.$resolveBaseUrl, so HTTPS,
	 * non-localhost, and vhosted setups target the right origin instead of
	 * a hardcoded http://localhost. Precedence, highest first:
	 *
	 * 1. this.testClientBaseUrl             — per-spec override
	 * 2. get("testClientBaseUrl")           — Wheels setting
	 * 3. -Dwheels.testClient.baseUrl=...    — JVM system property
	 * 4. WHEELS_TEST_CLIENT_BASE_URL env    — CI / shell
	 * 5. $detectTestBaseUrlFromCgi(cgi)     — scheme/host/port of the
	 * in-flight test-runner request
	 * 6. "http://localhost:8080" default    — bare LuCLI port
	 */
	private string function $getTestBaseUrl() {}
	/**
	 * Derive the test base URL from the in-flight test-runner request,
	 * preserving scheme (https) and host instead of assuming
	 * http://localhost. Mirrors BrowserTest.$detectBaseUrlFromCgi.
	 */
	public string function $detectTestBaseUrlFromCgi( required any cgiScope ) {}
}
