// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/core/delegates/JsonUtil.cfc — do not edit.
/**
 * This delegate is useful to deal with opinionated json conversion for integration with JS libraries and more.
 */
component {
	property name ="util" inject ="coldbox.system.core.util.Util" delegate="toJson,prettyJson,toPrettyJson";
	variables.util = new coldbox.system.core.util.Util();
	/**
	 * This function allows you to serialize simple or complex data so it can be used within HTML Attributes.
	 *
	 * @data The simple or complex data to bind to an HTML Attribute
	 */
	function forAttribute( required data ) {}
}
