// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/cbsecurity@a890b0cb52b4 models/jwt/storages/CacheTokenStorage.cfc — do not edit.
/**
 * Copyright since 2016 by Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * A CacheBox cache based token storage
 */
component {
	property name="wirebox" inject="wirebox";
	property name="cachebox" inject="cachebox";
	property name="settings" inject="coldbox:moduleSettings:cbSecurity";
	property name="jwtService" inject="JwtService@cbSecurity";
	/**
	 * Storage properties
	 */
	property name="properties";
	/**
	 * The linked cache provider
	 */
	property name="cache";
	/**
	 * The configured key prefix for the storage
	 */
	property name="keyPrefix";
	variables.jwtService = new cbsecurity.models.jwt.JwtService();
	/**
	 * Constructor
	 */
	cbsecurity.models.jwt.storages.CacheTokenStorage function init() {}
	/**
	 * Configure the storage by passing in the properties
	 *
	 * @properties The storage properties
	 *
	 * @return JWTStorage
	 */
	cbsecurity.models.jwt.storages.CacheTokenStorage function configure( required properties ) {}
	/**
	 * Set a token in the storage
	 *
	 * @key        The cache key
	 * @token      The token to store
	 * @expiration The token expiration
	 * @payload    The payload
	 *
	 * @return JWTStorage
	 */
	cbsecurity.models.jwt.storages.CacheTokenStorage function set( required key, required token, required expiration, required payload ) {}
	/**
	 * Verify if the passed in token key exists
	 *
	 * @key The cache key
	 */
	boolean function exists( required key ) {}
	/**
	 * Retrieve the token via the cache key, if the key doesn't exist a TokenNotFoundException will be thrown
	 *
	 * @key          The cache key
	 * @defaultValue If not found, return a default value
	 *
	 * @throws TokenNotFoundException
	 */
	struct function get( required key, struct defaultValue ) {}
	/**
	 * Invalidate/delete one or more keys from the storage
	 *
	 * @key A cache key or an array of keys to clear
	 *
	 * @return True, if deleted
	 */
	boolean function clear( required any key ) {}
	/**
	 * Clear all the keys in the storage
	 *
	 * @return JWTStorage
	 */
	cbsecurity.models.jwt.storages.CacheTokenStorage function clearAll() {}
	/**
	 * Retrieve all the jwt keys stored in the storage
	 */
	array function keys() {}
	/**
	 * The size of the storage
	 */
	numeric function size() {}
	/**
	 * Build out a prefixed key
	 */
	private function buildKey( required key ) {}
}
