// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/ConfigService.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano
 *
 * I handle working with the CommandBox.json file
 */
component {
	property name="configSettings";
	property name="configSettingOverrides";
	property name="possibleConfigSettings";
	property name="configFilePath";
	property name="serverServiceCompletePerformed" type="boolean" default="false";
	property name='formatterUtil' inject='formatter';
	property name='ModuleService' inject='ModuleService';
	property name='JSONService' inject='JSONService';
	property name='ServerService' inject='provider:ServerService';
	property name='interceptorService' inject='interceptorService';
	property name='systemSettings' inject='SystemSettings';
	variables.formatterUtil = new commandbox.system.util.Formatter();
	variables.ModuleService = new commandbox.system.services.ModuleService();
	variables.JSONService = new commandbox.system.services.JSONService();
	variables.ServerService = new commandbox.system.services.ServerService();
	variables.interceptorService = new commandbox.system.services.InterceptorService();
	variables.systemSettings = new commandbox.system.util.SystemSettings();
	/**
	 * Constructor
	 */
	commandbox.system.services.ConfigService function init() {}
	function onDIComplete() {}
	function setConfigSettings( required struct configSettings, boolean quiet ) {}
	/**
	 * Get a setting from a configuration structure
	 * @name.hint The name of the setting.  Allows for "deep" struct/array names.
	 * @defaultValue.hint The default value to use if setting does not exist
	 */
	function getSetting( required name, defaultValue ) {}
	/**
	 * Get a setting from a configuration structure with JMESPath
	 * @name.hint The name of the setting.  Allows for "deep" struct/array names.
	 * @defaultValue.hint The default value to use if setting does not exist
	 */
	function getSettingJMES( required name, defaultValue ) {}
	/**
	 * Check if a value exists in a configuration structure
	 * @name.hint The name of the setting.  Allows for "deep" struct/array names.
	 */
	boolean function settingExists( required name ) {}
	/**
	 * Set a value in the application configuration settings
	 * @name.hint The name of the setting.  Allows for "deep" struct/array names.
	 * @value.hint The value to set
	 * @thisAppend.hint Append an array or struct to existing
	 */
	commandbox.system.services.ConfigService function setSetting( required name, required value, boolean thisAppend, boolean quiet ) {}
	/**
	 * Remove a value in the application configuration settings
	 * @name.hint The name of the setting.  Allows for "deep" struct/array names.
	 */
	commandbox.system.services.ConfigService function removeSetting( required name, boolean quiet ) {}
	/**
	 * Loads config settings from disk
	 */
	function loadConfig() {}
	/**
	 * Return all config settings including env var/sys prop overrides
	 */
	function getConfigSettings( boolean noOverrides ) {}
	/**
	 * Loads config settings from env vars or Java system properties
	 */
	function loadOverrides() {}
	/**
	 * Persists config settings to disk
	 */
	function saveConfig( boolean quiet ) {}
	/**
	 * Dynamic completion for property name based on contents of commandbox.json
	 * @all Pass false to ONLY suggest existing setting names.  True will suggest all possible settings.
	 * @asSet Pass true to add = to the end of the options
	 */
	function completeProperty( all, asSet ) {}
}
