// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/EndpointService.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 *
 * I handle working with Endpoints
 */
component {
	property name="tempDir" inject="tempDir@constants";
	property name="wirebox" inject="wirebox";
	property name="fileSystemUtil" inject="FileSystem";
	property name="consoleLogger" inject="logbox:logger:console";
	property name="configService" inject="configService";
	property name='interceptorService' inject='interceptorService';
	property name="endpointRegistry" type="struct";
	property name="endpointRootPath" type="string" default="/commandbox/system/endpoints";
	variables.fileSystemUtil = new commandbox.system.util.FileSystem();
	variables.configService = new commandbox.system.services.ConfigService();
	variables.interceptorService = new commandbox.system.services.InterceptorService();
	/**
	 * Constructor
	 */
	commandbox.system.services.EndpointService function init() {}
	function onCLIStart() {}
	/**
	 * Inspect the endpoints folder and register them.
	 */
	function buildEndpointRegistry( string rootDirectory ) {}
	/**
	 * Look for custom ForgeBox endpoints that are in the config and register them
	 * These will use the same base ForgeBox.cfc endpoint but with custom data
	 */
	function registerCustomForgeboxEndpoints() {}
	/**
	 * Register a single CFC instance as an endpoint
	 *
	 * @oEndPoint An instance of a CFC implementing IEndPoint
	 */
	function registerEndpoint( required any oEndPoint ) {}
	/**
	 * Inspects ID and returns name of endpoint.  If none is specified, tests for local file
	 * or folder.  Defaults to forgebox.
	 * @ID The id of the endpoint
	 * @currentWorkingDirectory Where we are working from
	 */
	struct function resolveEndpointData( required string ID, required string currentWorkingDirectory ) {}
	/**
	 * Returns the endpoint object.
	 * @endpointName The name of the endpoint to retrieve
	 */
	IEndpoint function getEndpoint( required string endpointName ) {}
	/**
	 * Inspects ID and returns endpoint object, endpointName, and ID (with endpoint stripped).
	 * @ID The id of the endpoint
	 * @currentWorkingDirectory Where we are working from
	 */
	struct function resolveEndpoint( required string ID, required string currentWorkingDirectory ) {}
	/**
	 * A facade to create a user with an interactive endpoint.  Keeping this logic here so I can standardize the storage
	 * of the APIToken and make it reusable outside of the command.
	 * @endpointName The name of the endpoint
	 * @username ForgeBox username
	 * @password The password
	 * @email ForgeBox email
	 * @firstName First name
	 * @lastName Last Name
	 */
	function createEndpointUser( required string endpointName, required string username, required string password, required string email, required string firstName, required string lastName ) {}
	/**
	 * A facade to login a user with an interactive endpoint.  Keeping this logic here so I can standardize the storage
	 * of the APIToken and make it reusable outside of the command.
	 * @endpointName The name of the endpoint
	 * @username The username
	 * @password The password to use
	 */
	function loginEndpointUser( required string endpointName, required string username, required string password ) {}
	/**
	 * A facade to logout a user with an interactive endpoint.  Keeping this logic here so I can standardize the storage
	 * of the APIToken and make it reusable outside of the command.  Passing no username should log out all users.
	 * @endpointName The name of the endpoint
	 * @username The username
	 */
	function logoutEndpointUser( required string endpointName, required string username ) {}
	/**
	 * A facade to publish a package with an interactive endpoint.
	 * @endpointName The name of the endpoint to publish to
	 * @directory The directory to publish
	 */
	function publishEndpointPackage( required string endpointName, required string directory, boolean upload, boolean forceUpload ) {}
	/**
	 * A facade to unpublish a package with an interactive endpoint.
	 * @endpointName The name of the endpoint to publish to
	 * @directory The directory to publish
	 * @version The version to unpublish
	 */
	function unpublishEndpointPackage( required string endpointName, required string directory, string version ) {}
	function forgeboxEndpointNameComplete() {}
}
