// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/ModuleService.cfc — do not edit.
component {
	property name="moduleData";
	property name="CommandService" inject="CommandService";
	property name="EndpointService" inject="EndpointService";
	property name="ConfigService" inject="Configservice";
	property name="SystemSettings" inject="SystemSettings";
	property name="consoleLogger" inject="logbox:logger:console";
	property name="fileSystemUtil" inject="FileSystem";
	variables.CommandService = new commandbox.system.services.CommandService();
	variables.EndpointService = new commandbox.system.services.EndpointService();
	variables.ConfigService = new commandbox.system.services.ConfigService();
	variables.SystemSettings = new commandbox.system.util.SystemSettings();
	variables.fileSystemUtil = new commandbox.system.util.FileSystem();
	/**
	 * Constructor
	 */
	public commandbox.system.services.ModuleService function init( required any shell ) {}
	function getShell() {}
	/**
	 * Called by loader service when configuration file loads
	 */
	public void function configure() {}
	/**
	 * Called when the application stops
	 */
	public void function onShutdown() {}
	/**
	 * Get the discovered module's registry structure
	 */
	public struct function getModuleRegistry() {}
	/**
	 * Return the loaded module's configuration objects
	 */
	public struct function getModuleConfigCache() {}
	/**
	 * Rescan the module locations directories and re-register all located modules, this method does NOT register or activate any modules, it just reloads the found registry
	 */
	public any function rebuildModuleRegistry() {}
	/**
	 * Register all modules for the application. Usually called by framework to load configuration data.
	 */
	public commandbox.system.services.ModuleService function registerAllModules() {}
	/**
	 * Register and activate a new module
	 * @moduleName The name of the module to load.
	 * @invocationPath The module's invocation path to its root from the webroot (the instantiation path,ex:myapp.myCustomModules), if empty we use registry location, if not we are doing a explicit name+path registration. Do not include the module name, you passed that in the first argument right
	 */
	public void function registerAndActivateModule( required string moduleName, string invocationPath ) {}
	/**
	 * Register a module's configuration information and config object
	 * @moduleName The name of the module to load.
	 * @invocationPath The module's invocation path to its root from the webroot (the instantiation path,ex:myapp.myCustomModules), if empty we use registry location, if not we are doing a explicit name+path registration. Do not include the module name, you passed that in the first argument right
	 * @parent The name of the parent module
	 * @force Force a registration
	 */
	public boolean function registerModule( required string moduleName, string invocationPath, string parent, boolean force ) {}
	/**
	 * unregisters a targeted module
	 * @moduleName The module to reload
	 */
	public void function unregisterModule( required string moduleName ) {}
	/**
	 * unregisters a targeted module
	 * @moduleName The module to reload
	 */
	public void function unloadAndUnregisterModule( required string moduleName ) {}
	/**
	 * Load all module mappings
	 */
	public any function loadMappings() {}
	/**
	 * Go over all the loaded module configurations and activate them for usage within the application
	 */
	public void function activateAllModules() {}
	/**
	 * Activate a module
	 * @moduleName The name of the module to load. It must exist and be valid. Else we ignore it by logging a warning and returning false.
	 */
	public commandbox.system.services.ModuleService function activateModule( required string moduleName ) {}
	/**
	 * Reload a targeted module
	 * @moduleName The module to reload
	 */
	public void function reload( required string moduleName ) {}
	/**
	 * Reload all modules
	 */
	public void function reloadAll() {}
	/**
	 * Get a listing of all loaded modules
	 */
	public array function getLoadedModules() {}
	/**
	 * Check and see if a module has been registered
	 */
	public boolean function isModuleRegistered( required string moduleName ) {}
	/**
	 * Check and see if a module has been activated
	 */
	public boolean function isModuleActive( required string moduleName ) {}
	/**
	 * Unload a module if found from the configuration
	 * @moduleName The module name to unload
	 */
	public boolean function unload( required string moduleName ) {}
	/**
	 * Unload all registered modules
	 */
	public void function unloadAll() {}
	/**
	 * Load the module configuration object and return it
	 * @config The module config structure
	 * @moduleName The module name
	 */
	public any function loadModuleConfiguration( required struct config, required string moduleName ) {}
	/**
	 * @moduleSettings The module setting structure
	 * @moduleName The module name
	 */
	public function overrideConfigSettings( required struct moduleSettings, required string moduleName, required struct configSettings ) {}
	public function overrideAllConfigSettings( required struct configSettings ) {}
	/**
	 * Build the modules registry
	 * @locations The array of locations to register
	 */
	private void function buildRegistry( required array locations ) {}
	/**
	 * Get an array of modules found and add to the registry structure
	 * @dirPath Path to scan
	 */
	private void function scanModulesDirectory( required string dirPath ) {}
	/**
	 * Checks if the module can be loaded or registered
	 * @moduleName The module name
	 */
	private boolean function canLoad( required string moduleName ) {}
}
