// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/S3Service.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 *
 * I convert s3 paths (s3://bucket/path) to signed HTTPS urls
 */
component {
	property name="configService" inject="configService";
	property name="systemSettings" inject="SystemSettings";
	property name="fileSystemUtil" inject="FileSystem";
	property name='wirebox' inject='wirebox';
	/**
	 * Local URL to query for IAM role
	 */
	property name="iamRolePath" type="string";
	property name="bucketRegionCache" type="struct";
	variables.configService = new commandbox.system.services.ConfigService();
	variables.systemSettings = new commandbox.system.util.SystemSettings();
	variables.fileSystemUtil = new commandbox.system.util.FileSystem();
	/**
	 * Constructor
	 */
	commandbox.system.services.S3Service function init() {}
	function onDIComplete() {}
	/**
	 * Generate a signed HTTPS URL from a S3 path.
	 *
	 * @s3Path.hint Path to S3 object specified in the format s3://bucket/path/to/object
	 * @verbose.hint Set to true to log additional information
	 */
	public string function generateSignedURL( required string s3Path, boolean verbose ) {}
	private function generatePresignedPath( method, bucket, objectKey, bucketRegion, credentials ) {}
	private function resolveBucketRegion( bucket, defaultRegion, verbose ) {}
	private function resolveAwsSettings( bucket, verbose ) {}
	private function resolveCredentials( endpointSettings, credentialsFile, profile, verbose ) {}
	private function iso8601( dateToFormat ) {}
	private function encodeUrl( urlPath, encodeForwardSlash ) {}
	private function makeHTTPRequest( urlPath, method, redirect, timeout, headers, allowProxy ) {}
}
