// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/ServerEngineService.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Platform by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 */
component {
	property name='tempDir' inject='tempDir@constants';
	property name='packageService' inject='PackageService';
	property name='endpointService' inject='EndpointService';
	property name='cr' inject='cr@constants';
	property name='shell' inject='shell';
	property name="semanticVersion" inject="provider:semanticVersion@semver";
	property name="artifactService" inject="artifactService";
	property name="wirebox" inject="wirebox";
	property name="fileSystemUtil" inject="fileSystem";
	variables.packageService = new commandbox.system.services.PackageService();
	variables.endpointService = new commandbox.system.services.EndpointService();
	variables.shell = new commandbox.system.Shell();
	variables.semanticVersion = new commandbox.system.modules.semver.models.SemanticVersion();
	variables.artifactService = new commandbox.system.services.ArtifactService();
	variables.fileSystemUtil = new commandbox.system.util.FileSystem();
	/**
	 * install the server if not already installed to the target directory
	 *
	 * @cfengine	CFML Engine name (lucee, adobe, railo, boxlang)
	 * @baseDirectory base directory for server install
	 * @serverInfo The struct of server settings
	 * @serverHomeDirectory Override where the server's home with be
	 */
	public function install( required cfengine, required baseDirectory, required struct serverInfo, required string serverHomeDirectory ) {}
	/**
	 * install adobe
	 */
	public function installAdobe( installDetails, serverInfo ) {}
	/**
	 * install BoxLang
	 */
	public function installBoxlang( installDetails, serverInfo ) {}
	public function _installBoxlang( installDetails, serverInfo, WebXMLPath ) {}
	/**
	 * install lucee
	 */
	public function installLucee( installDetails, serverInfo ) {}
	/**
	 * install railo
	 */
	public function installRailo( installDetails, serverInfo ) {}
	/**
	 * Downloads a CF engine endpoint and unzips the "Engine.[WAR|zip] archive into the destination
	 * The WAR will be placed in a folder named {cfengine}-{version}/ unless an installDir is supplied.
	 *
	 * @ID The endpoint ID to use for the CF Engine.
	 * @destination The folder where this site's servers are stored.
	 */
	function installEngineArchive( required string ID, required string destination, required struct serverInfo, required string serverHomeDirectory ) {}
	private function calcEngineContextPaths( installDetails, serverInfo ) {}
	/**
	 * configure web.xml file for Lucee and Railo
	 *
	 * @cfengine lucee or railo
	 * @source source web.xml
	 * @destination target web.xml
	 */
	public function configureWebXML( required cfengine, required version, required source, required destination, required struct serverInfo, required struct installDetails, boolean forceUpdate ) {}
	/**
	 * Ensure a given servlet has a specific init param value
	 *
	 * @webXML XML Doc of webl.xml
	 * @servletClass Name of servlet to check
	 * @initParamName Name of init param to ensure exists
	 * @initParamValue Value init param needs to have
	 *
	 * @returns true if changes were made, false if nothing was updated.
	 */
	function ensureProperServletInitParam( webXML, string servletClass, string initParamName, string initParamValue ) {}
	/**
	 * Ensure a given servlet has a specific init param value
	 *
	 * @webXML XML Doc of webl.xml
	 * @servletClass Name of servlet to check
	 * @initParamName Name of init param to ensure exists
	 *
	 * @returns true if changes were made, false if nothing was updated.
	 */
	function removeServletInitParam( webXML, string servletClass, string initParamName ) {}
	/**
	 * Write an XML file to disk and format it so it's human-readable
	 *
	 * @XMLDoc XML Doc to write (complex value)
	 * @path File path to write XML to
	 */
	private function writeXMLFile( XMLDoc, path ) {}
	/**
	 * Find the Lucee jar in the lib directory and if it's packed, unpack it.
	 * If the unpacked jar is found in artifacts, use it instead.
	 * If not, unpack and store in artifacts for next time.
	 *
	 * @libDirectory Directory where the libs are for the server
	 * @luceeVersion Semver for the Lucee version so we can use artifacts
	 */
	private function unpackLuceeJar( libDirectory, luceeVersion ) {}
	/**
	 * Take a pack200 packed jar and unpack it into the same folder, deleting the original
	 *
	 * @packedFile Path to the packed file named something.foo.pack.gz. Will be replaced with something.foo
	 */
	private function unpackInPlace( packedFile ) {}
	function getCLIEngineName() {}
	private function ensureSeedProperties( required string seedPropertiesPath ) {}
}
