// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/services/ServerService.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant, Scott Steinbeck
 *
 * I manage servers
 */
component {
	/**
	 * Where the server libs are located
	 */
	property name="libDir";
	/**
	 * Where the server configuration file is
	 */
	property name="serverConfig";
	/**
	 * Where custom servers are stored
	 */
	property name="customServerDirectory";
	/**
	 * Where the Java Command Executable is
	 */
	property name="javaCommand";
	/**
	 * Where the Run War jar path is
	 */
	property name="jarPath";
	property name='interceptorService' inject='interceptorService';
	property name='configService' inject='ConfigService';
	property name='CommandService' inject='provider:CommandService';
	property name='JSONService' inject='JSONService';
	property name='packageService' inject='packageService';
	property name='serverEngineService' inject='serverEngineService';
	property name='consoleLogger' inject='logbox:logger:console';
	property name='rootLogger' inject='logbox:root';
	property name='wirebox' inject='wirebox';
	property name='CR' inject='CR@constants';
	property name='parser' inject='parser';
	property name='systemSettings' inject='SystemSettings';
	property name='javaService' inject='provider:javaService';
	property name='ansiFormatter' inject='AnsiFormatter';
	property name="printUtil" inject="print";
	variables.interceptorService = new commandbox.system.services.InterceptorService();
	variables.configService = new commandbox.system.services.ConfigService();
	variables.CommandService = new commandbox.system.services.CommandService();
	variables.JSONService = new commandbox.system.services.JSONService();
	variables.packageService = new commandbox.system.services.PackageService();
	variables.serverEngineService = new commandbox.system.services.ServerEngineService();
	variables.systemSettings = new commandbox.system.util.SystemSettings();
	variables.javaService = new commandbox.system.services.JavaService();
	variables.ansiFormatter = new commandbox.system.util.AnsiFormatter();
	variables.printUtil = new commandbox.system.util.Print();
	/**
	 * Constructor
	 *
	 * @shell.inject shell
	 * @formatter.inject Formatter
	 * @fileSystem.inject FileSystem
	 * @homeDir.inject HomeDir@constants
	 * @consoleLogger.inject logbox:logger:console
	 * @logger.inject logbox:logger:{this}
	 */
	commandbox.system.services.ServerService function init( required shell, required formatter, required fileSystem, required homeDir, required consoleLogger, required logger ) {}
	/**
	 * Returns the default server.json settings as a struct
	 */
	function getDefaultServerJSON() {}
	/**
	 * Start a server instance
	 *
	 * @serverProps A struct of settings to influence how to start the server. Params not provided by the user are null.
	 */
	function start( Struct serverProps ) {}
	/**
	 * Load site config from an external file
	 */
	function loadSiteConfig( site, siteName ) {}
	/**
	 * This function abstracts file system expansion and default values so it is reusabe
	 * - .site.json -> expand paths relative to .site.json file
	 * - server.json site block -> expand paths relative to serverjson file
	 * - server.json web block -> expand paths relative to server.json file
	 * - config defaults web block -> expand paths relative to webroot
	 */
	private function expandAndDefaultConfig( config ) {}
	/**
	 * Resolve all the settings for a given site, merging in server.json web defaults and config defaults
	 * Also merges in any server properties that were passed on the command line
	 * Throws if any settings are found that cannot be set on a per-site basis
	 * Returns nothing, just modifies the serverInfo struct in place
	 *
	 * @name The name of the site to resolve
	 * @serverInfo The serverInfo struct to modify
	 * @serverProps The server properties passed on the command line
	 * @serverJSON The full server.json data
	 * @defaults The config defaults struct
	 * @multiSite True if there is more than one site defined
	 */
	function resolveSiteSettings( string name, struct serverInfo, struct serverProps, struct serverJSON, struct defaults, boolean multiSite, string engineName ) {}
	/**
	 * Build out all bindings for a site, expanding all possible hosts and defaulting values.
	 * Bindings are array of structs having these keys.
	 * - IP
	 * - port
	 * - host
	 * - type
	 * - site
	 */
	function buildBindings( required struct serverInfo, serverJSON, defaults, serverProps, serverDetails ) {}
	/**
	 * Create default binding struct, expanding a bindings for each possible host name
	 */
	struct function newBinding( required site, IP, port, hosts, type, HTTP2Enable, SSLCertFile, SSLKeyFile, SSLKeyPass, SSLCerts, AJPSecret, clientCertMode, clientCertCACertFiles, clientCertCATrustStoreFile, clientCertCATrustStorePass, clientCertSSLRenegotiationEnable ) {}
	/**
	 * allows to iterate on a tray menu item recursively
	 * and checks for the default image and default shell
	 */
	array function appendMenuItems( array trayOptions, relativePath, array parentOptions ) {}
	/**
	 * checks for the default image and default shell
	 */
	function prepareMenuItem( menuItem, relativePath ) {}
	function fixBinaryPath( command, fullPath ) {}
	/**
	 * Detects if the first heap size is larger than the second
	 * @heapSize1 Specified as 1024m, 2G, or 512k
	 * @heapSize2 Specified as 1024m, 2G, or 512k
	 */
	function isHeapLarger( heapSize1, heapSize2 ) {}
	/**
	 * Convert heap in format like 1G to 1024
	 * Will always return MB, but without the "m"
	 */
	function convertHeapToMB( heapSize ) {}
	function getFirstServer() {}
	/**
	 * Unified logic to resolve a server given an optional name, directory, and server.json path.
	 * Returns resolved name, webroot, serverConfigFile, serverInfo from the last start and serverJSON
	 * Use this for all 'server' commands that let a user specify the server they want by convention (CWD),
	 * name, directory, or server.json path.
	 *
	 * @serverProps A struct that can contains name, directory, and/or serverConfigFile
	 *
	 * @returns a struct containing
	 * - defaultName
	 * - defaultwebroot
	 * - defaultServerConfigFile
	 * - serverJSON
	 * - serverInfo
	 * - serverIsNew
	 */
	function resolveServerDetails( required struct serverProps ) {}
	/**
	 * Stop server
	 * @serverInfo.hint The server information struct: [ webroot, name, port, stopSocket, logDir, status, statusInfo ]
	 *
	 * @returns struct of [ error, messages ]
	 */
	struct function stop( required struct serverInfo ) {}
	/**
	 * Forget server from the configurations
	 * @serverInfo.hint struct of server info (ports, etc.)
	 * @all.hint remove ALL servers
	 */
	function forget( required struct serverInfo ) {}
	/**
	 * Get a custom server folder name according to our naming convention to avoid collisions with name
	 * @serverInfo The server information
	 */
	function getCustomServerFolder( required struct serverInfo ) {}
	/**
	 * Get a random port for the specified host
	 * @host.hint host to get port on, defaults 127.0.0.1
	 */
	function getRandomPort( host ) {}
	/**
	 * Find out if a given host/port is already bound
	 * @host.hint host to test port on, defaults 127.0.0.1
	 */
	function isPortAvailable( host, required port ) {}
	/**
	 * Find out what the IP address is for a given host
	 * @host.hint host to test port on such as localsite.com
	 */
	function getAddressByHost( required string host ) {}
	/**
	 * Find out if a given Process ID (PID) is a running java service
	 * @pidStr.hint PID to test on
	 */
	function isProcessAlive( required pidStr, throwOnError ) {}
	/**
	 * Logic to tell if a server is running
	 * @serverInfo.hint Struct of server information
	 * @quick When set to true, only the PID file is checked for on disk. When set to false, the OS is actually asked if the process is still running.
	 */
	function isServerRunning( required struct serverInfo, boolean quick ) {}
	/**
	 * persist server info
	 * @serverInfo.hint struct of server info (ports, etc.)
	 */
	function setServerInfo( required struct serverInfo ) {}
	function calculateServerID( webroot, name ) {}
	function normalizeWebroot( required string webroot ) {}
	/**
	 * Create initial server JSON
	 */
	function initServers() {}
	/**
	 * persist servers
	 *
	 * @servers struct of serverInfos
	 */
	commandbox.system.services.ServerService function setServers( required Struct servers ) {}
	/**
	 * get servers struct from config file on disk
	 */
	struct function getServers() {}
	/**
	 * Get a server information struct by name or directory.
	 * Returns empty struct if not found.
	 * @directory.hint the directory to find
	 * @name.hint The name to find
	 */
	struct function getServerInfoByDiscovery( required directory, required name, serverConfigFile ) {}
	/**
	 * Get a server information struct by name, if not found it returns an empty struct
	 * @name.hint The name to find
	 */
	struct function getServerInfoByName( required name ) {}
	/**
	 * Get a server information struct by serverConfigFile if not found it returns an empty struct
	 * @name.serverConfigFile The serverConfigFile to find
	 */
	struct function getServerInfoByServerConfigFile( required serverConfigFile ) {}
	/**
	 * Get all servers registered as an array of names
	 */
	array function getServerNames() {}
	/**
	 * Get a server information struct by webrot, if not found it returns an empty struct
	 * @webroot.hint The webroot to find
	 */
	struct function getServerInfoByWebroot( required webroot ) {}
	/**
	 * Get server info for webroot
	 * @webroot.hint root directory for served content
	 */
	struct function getServerInfo( required webroot, required name ) {}
	/**
	 * Returns a new server info structure
	 */
	struct function newServerInfoStruct() {}
	/**
	 * Returns a new site info structure with only the properties that are relevant to a site
	 */
	struct function newSiteInfoStruct() {}
	/**
	 * Read a server.json file.  If it doesn't exist, returns an empty struct
	 * This only returns properties specifically set in the file.
	 */
	struct function readServerJSON( required string path ) {}
	/**
	 * Save a server.json file.
	 */
	function saveServerJSON( required string configFilePath, required struct data ) {}
	/**
	 * Dynamic completion for property name based on contents of server.json
	 * @directory web root
	 * @all Pass false to ONLY suggest existing setting names.  True will suggest all possible settings.
	 * @asSet Pass true to add = to the end of the options
	 */
	function completeProperty( required directory, all, asSet, paramSoFar ) {}
	/**
	 * Dynamic completion for server names, sorted by last started
	 */
	function serverNameComplete() {}
	/**
	 * Loads config settings from env vars or Java system properties
	 */
	function loadOverrides( serverJSON, serverInfo, boolean verbose ) {}
	/**
	 * Nice wrapper to run a server script
	 *
	 * @scriptName Name of the server script to run
	 * @directory The web root
	 * @ignoreMissing Set true to ignore missing server scripts, false to throw an exception
	 * @interceptData An optional struct of data if this server script is being fired as part of an interceptor announcement.  Will be loaded into env vars
	 */
	function runScript( required string scriptName, string directory, boolean ignoreMissing, interceptData ) {}
	function isSingleServerMode() {}
}
