// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/search/SearchResults.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * The official ContentBox Search Results Object
 */
component {
	property name="results" type="any" hint="The search results in query or array or whatever format";
	property name="total" type="numeric" hint="The total number of records found";
	property name="searchTime" type="numeric" hint="The amount of time it took for the search in milliseconds";
	property name="searchTerm" type="string" hint="The search term used";
	property name="error" type="boolean" hint="Mark if the search results produce an error or not";
	property name="errorMessages" type="array" hint="An array of error messagse if any";
	property name="metadata" type="struct" hint="Any metadata structure you wish to store";
	/**
	 * Constructor
	 */
	contentbox.models.search.SearchResults function init() {}
	/**
	 * Populate a search memento
	 *
	 * @return SearchResults
	 */
	contentbox.models.search.SearchResults function populate( required struct memento ) {}
	/**
	 * Get the search memento
	 *
	 * @return struct of { "results","searchTime","total","metadata","error","errorMessages","searchTerm" }
	 */
	struct function getMemento() {}
}
