// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/config/ApplicationLoader.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This service loads all application configuration from conventions or a ColdBox config
 */
component {
	/**
	 * Constructor
	 *
	 * @constructor
	 */
	coldbox.system.web.config.ApplicationLoader function init( required controller ) {}
	/**
	 * Parse the application configuration file
	 *
	 * @overrideAppMapping The direct location of the application in the web server.
	 * @overrideWebMapping
	 */
	coldbox.system.web.config.ApplicationLoader function loadConfiguration( string overrideAppMapping, string overrideWebMapping ) {}
	/**
	 * Calculate the AppMapping
	 *
	 * @configStruct The global settings structure
	 */
	function calculateAppMapping( required configStruct ) {}
	/**
	 * Parse ColdBox Settings
	 *
	 * @oConfig            The config cfc
	 * @config             The config struct
	 * @overrideAppMapping The override mapping string
	 */
	function parseColdboxSettings( required oConfig, required config, overrideAppMapping ) {}
	/**
	 * Parse Your Settings
	 *
	 * @oConfig The config cfc
	 * @config  The config struct
	 */
	function parseYourSettings( required oConfig, required config ) {}
	/**
	 * Parse Your Conventions
	 *
	 * @oConfig The config cfc
	 * @config  The config struct
	 */
	function parseConventions( required oConfig, required config ) {}
	/**
	 * Parse invocation paths
	 */
	function parseInvocationPaths( required oConfig, required config ) {}
	/**
	 * Parse external locations
	 */
	function parseExternalLocations( required oConfig, required config ) {}
	/**
	 * Parse layouts and views
	 */
	function parseLayoutsViews( required oConfig, required config ) {}
	/**
	 * Parse cachebox
	 */
	function parseCacheBox( required oConfig, required config ) {}
	/**
	 * Parse interceptors
	 */
	function parseInterceptors( required oConfig, required config ) {}
	/**
	 * Parse LogBox
	 */
	function parseLogBox( required oConfig, required config, required configHash ) {}
	/**
	 * Parse WireBox
	 */
	function parseWireBox( required oConfig, required config ) {}
	/**
	 * Parse the Server-Sent Events settings
	 */
	function parseSSE( required oConfig, required config ) {}
	function parseFlashScope( required oConfig, required config ) {}
	/**
	 * Parse Executors
	 */
	function parseExecutors( required oConfig, required config ) {}
	/**
	 * Parse Modules
	 */
	function parseModules( required oConfig, required config ) {}
	/**
	 * Detect the running environment and return the name
	 */
	private function detectEnvironment( required oConfig, required config, environment ) {}
	/**
	 * Load LogBox by convention
	 */
	private function loadLogBoxByConvention( required logBoxConfig, required config ) {}
	/**
	 * Load LogBox by file
	 */
	private function loadLogBoxByFile( required logBoxConfig, required filePath ) {}
	/**
	 * Basically get the right config file to load in place
	 */
	private function loadCacheBoxByConvention( required config ) {}
	/**
	 * Get the App Mapping as Dots
	 */
	private function getAppMappingAsDots( required appMapping ) {}
}
