// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/Renderer.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * The system web renderer. In charge of location views/layouts and rendering them.
 *
 * @author Luis Majano <lmajano@ortussolutions.com>
 */
component extends="coldbox.system.FrameworkSupertype" {
	/**
	 * DI *
	 */
	property name="templateCache" inject="cachebox:template";
	property name="layoutsConvention";
	property name="LayoutsExternalLocation";
	property name="viewsConvention";
	property name="ViewsExternalLocation";
	property name="appMapping";
	property name="modulesConfig" type="struct";
	property name="viewsHelper";
	property name="lockName";
	property name="isDiscoveryCaching";
	property name="expandPathCache";
	property name="locateViewCache";
	property name="locateLayoutCache";
	/**
	 * Constructor
	 */
	coldbox.system.web.Renderer function init() {}
	/**
	 * Deprecated/Removed Methods *
	 */
	function renderview() {}
	function renderLayout() {}
	function renderExternalView() {}
	/**
	 * This is the startup procedures for the renderer. This is called after all modules, interceptions and contributions have been done
	 * in order to allow for all chicken and the egg issues are not relevant.
	 */
	function startup() {}
	/**
	 * set the explicit view bit, used mostly internally
	 *
	 * @view          The name of the view to render
	 * @module        The name of the module this view comes from
	 * @args          The view/layout passthrough arguments
	 * @viewVariables The view variables in the variables scope
	 *
	 * @return Renderer
	 */
	coldbox.system.web.Renderer function setExplicitView( required string view, module, struct args, struct viewVariables ) {}
	/**
	 * get the explicit view bit
	 */
	function getExplicitView() {}
	/**
	 * Render out a view
	 *
	 * @view                   The the view to render, if not passed, then we look in the request context for the current set view.
	 * @args                   A struct of arguments to pass into the view for rendering, will be available as 'args' in the view.
	 * @module                 The module to render the view from explicitly
	 * @cache                  Cached the view output or not, defaults to false
	 * @cacheTimeout           The time in minutes to cache the view
	 * @cacheLastAccessTimeout The time in minutes the view will be removed from cache if idle or requested
	 * @cacheSuffix            The suffix to add into the cache entry for this view rendering
	 * @cacheProvider          The provider to cache this view in, defaults to 'template'
	 * @collection             A collection to use by this Renderer to render the view as many times as the items in the collection (Array or Query)
	 * @collectionAs           The name of the collection variable in the partial rendering.  If not passed, we will use the name of the view by convention
	 * @collectionStartRow     The start row to limit the collection rendering with
	 * @collectionMaxRows      The max rows to iterate over the collection rendering with
	 * @collectionDelim        A string to delimit the collection renderings by
	 * @prePostExempt          If true, pre/post view interceptors will not be fired. By default they do fire
	 * @name                   The name of the rendering region to render out, Usually all arguments are coming from the stored region but you override them using this function's arguments.
	 * @viewVariables          A struct of variables to incorporate into the view's variables scope.
	 *
	 * @throws ViewNotSetException If no view is set to render or none found
	 */
	function view( view, struct args, module, boolean cache, cacheTimeout, cacheLastAccessTimeout, cacheSuffix, cacheProvider, collection, collectionAs, numeric collectionStartRow, numeric collectionMaxRows, collectionDelim, boolean prePostExempt, name, viewVariables ) {}
	/**
	 * Render a view composed of collections, mostly used internally, use at your own risk.
	 */
	function renderViewCollection( view, viewPath, viewHelperPath, args, collection, collectionAs, numeric collectionStartRow, numeric collectionMaxRows, collectionDelim, viewVariables ) {}
	/**
	 * Render a view alongside its helpers, used mostly internally, use at your own risk.
	 *
	 * @view           The view name to render
	 * @viewPath       The path of the view to render
	 * @viewHelperPath The helpers for the view to load before it
	 * @args           The view arguments structure
	 * @variables      The struct of variables to incorporate into the view's `variables` scope
	 *
	 * @return The rendered view string
	 */
	private function renderViewComposite( view, viewPath, viewHelperPath, args, viewVariables ) {}
	/**
	 * Renders an external view anywhere that cfinclude works.
	 *
	 * @view                   The the view to render
	 * @args                   A struct of arguments to pass into the view for rendering, will be available as 'args' iview.
	 * @cache                  Cached the view output or not, defaults to false
	 * @cacheTimeout           The time in minutes to cache the view
	 * @cacheLastAccessTimeout The time in minutes the view will be removed from cache if idle or requested
	 * @cacheSuffix            The suffix to add into the cache entry for this view rendering
	 * @cacheProvider          The provider to cache this view in, defaults to 'template'
	 * @viewVariables          A struct of variables to incorporate into the view's variables scope.
	 */
	function externalView( required view, struct args, boolean cache, cacheTimeout, cacheLastAccessTimeout, cacheSuffix, cacheProvider, viewVariables ) {}
	/**
	 * Render a layout or a layout + view combo
	 *
	 * @layout        The layout to render out
	 * @module        The module to explicitly render this layout from
	 * @view          The view to render within this layout
	 * @args          An optional set of arguments that will be available to this layouts/view rendering ONLY
	 * @viewModule    The module to explicitly render the view from
	 * @prePostExempt If true, pre/post layout interceptors will not be fired. By default they do fire
	 * @viewVariables A struct of variables to incorporate into the view's variables scope.
	 */
	function layout( layout, module, view, struct args, viewModule, boolean prePostExempt, viewVariables ) {}
	/**
	 * Locate a layout in the conventions system
	 *
	 * @layout The layout name
	 */
	function locateLayout( required layout ) {}
	/**
	 * Locate a layout in the module system
	 *
	 * @layout         The layout name
	 * @module         The name of the module we are searching for
	 * @explicitModule Are we locating explicitly or implicitly for a module layout
	 */
	function locateModuleLayout( required layout, module, boolean explicitModule ) {}
	/**
	 * Locate a view in the conventions or external paths
	 *
	 * @view The view to locate
	 */
	function locateView( required view ) {}
	/**
	 * Locate a view in the module system
	 *
	 * @view           The view name
	 * @module         The name of the module we are searching for
	 * @explicitModule Are we locating explicitly or implicitly for a module layout
	 */
	function locateModuleView( required view, module, boolean explicitModule ) {}
	/**
	 * Discover view+helper path locations.  The returned helper and view locations will have the appropriate extension.
	 *
	 * @view           The view to discover
	 * @module         The module address
	 * @explicitModule Is the module explicit or discoverable.
	 * @isLayout       Are we discovering a layout or a view
	 *
	 * @return struct  = { viewPath:string, viewHelperPath:string }
	 */
	function discoverViewPaths( required view, module, boolean explicitModule, boolean isLayout ) {}
	/**
	 * Memoized expandPath() — the mapping-to-absolute-path computation is pure and
	 * never changes between requests, so we cache it unconditionally.
	 */
	private function cachedExpandPath( required string path ) {}
	/**
	 * Verifies if we should render the implicit view or not
	 */
	private boolean function shouldRenderImplicitView( required string view ) {}
	/**
	 * Set's the view according to the executed event.
	 *
	 * @return Renderer
	 */
	private coldbox.system.web.Renderer function discoverImplicitViews() {}
	/**
	 * Incorporate a rendering region into the arguments struct
	 *
	 * @name  The name of the rendering region
	 * @event The request context
	 * @args  The arguments struct to incorporate the rendering region into
	 *
	 * @return The arguments processed
	 *
	 * @throws InvalidRenderingRegion - If the region name does not exist
	 */
	private function incorporateRenderingRegion( required name, required event, any args ) {}
}
