// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/logging/config/LogBoxConfig.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This is a LogBox configuration object.  You can use it to configure a LogBox variables.
 */
component {
	/**
	 * The ColdBox Utility object
	 */
	property name="utility";
	/**
	 * The appenders registered
	 */
	property name="appenders" type="struct";
	/**
	 * The categories registered
	 */
	property name="categories" type="struct";
	/**
	 * The root logger registered
	 */
	property name="rootLogger" type="struct";
	/**
	 * Flag to allow serializing complex objects in `extraInfo`.
	 */
	property name ="serializeExtraInfo" type ="boolean" default="true";
	this.logLevels = new coldbox.system.logging.LogLevels();
	variables.utility = new coldbox.system.core.util.Util();
	/**
	 * Constructor
	 *
	 * @CFCConfig     The logBox Data Configuration CFC
	 * @CFCConfigPath The logBox Data Configuration CFC path to use
	 */
	coldbox.system.logging.config.LogBoxConfig function init( any CFCConfig, string CFCConfigPath ) {}
	/**
	 * Get the ColdBox Utility object
	 */
	private coldbox.system.core.util.Util function getUtil() {}
	/**
	 * Reset the configuration
	 */
	coldbox.system.logging.config.LogBoxConfig function reset() {}
	/**
	 * Load a data configuration CFC data DSL
	 *
	 * @rawDSL The data configuration DSL structure
	 */
	coldbox.system.logging.config.LogBoxConfig function loadDataDSL( required struct rawDSL ) {}
	/**
	 * Reset appender configuration
	 */
	coldbox.system.logging.config.LogBoxConfig function resetAppenders() {}
	/**
	 * Reset categories configuration
	 */
	coldbox.system.logging.config.LogBoxConfig function resetCategories() {}
	/**
	 * Reset root configuration
	 */
	coldbox.system.logging.config.LogBoxConfig function resetRoot() {}
	/**
	 * Get the config memento
	 */
	struct function getMemento() {}
	/**
	 * Validates the configuration. If not valid, it will throw an appropriate exception.
	 *
	 * @throws AppenderNotFound - If an appender is not found in the configuration
	 */
	coldbox.system.logging.config.LogBoxConfig function validate() {}
	/**
	 * Add an appender configuration
	 *
	 * @name       A unique name for the appender to register. Only unique names can be registered per instance
	 * @class      The appender's class to register. We will create, init it and register it for you
	 * @properties The structure of properties to configure this appender with.
	 * @layout     The layout class path to use in this appender for custom message rendering.
	 * @levelMin   The default log level for the root logger, by default it is 0 (FATAL). Optional. ex: config.logLevels.WARN
	 * @levelMax   The default log level for the root logger, by default it is 3 (INFO). Optional. ex: config.logLevels.WARN
	 */
	coldbox.system.logging.config.LogBoxConfig function appender( required name, required class, struct properties, layout, levelMin, levelMax ) {}
	/**
	 * Add an appender configuration
	 *
	 * @appenders A list of appenders to configure the root logger with. Send a * to add all appenders
	 * @levelMin  The default log level for the root logger, by default it is 0 (FATAL). Optional. ex: config.logLevels.WARN
	 * @levelMax  The default log level for the root logger, by default it is 4 (DEBUG). Optional. ex: config.logLevels.WARN
	 * @exclude   a list of appenders to exclude from the root logger
	 *
	 * @throws InvalidAppenders
	 */
	coldbox.system.logging.config.LogBoxConfig function root( required appenders, levelMin, levelMax, exclude ) {}
	/**
	 * Get the root logger definition
	 */
	struct function getRoot() {}
	/**
	 * Add a new category configuration with appender(s).  Appenders MUST be defined first, else this method will throw an exception
	 *
	 * @name      A unique name for the appender to register. Only unique names can be registered per instance
	 * @levelMin  The default log level for the root logger, by default it is 0 (FATAL). Optional. ex: config.logLevels.WARN
	 * @levelMax  The default log level for the root logger, by default it is 4 (DEBUG). Optional. ex: config.logLevels.WARN
	 * @appenders A list of appender names to configure this category with. By default it uses all the registered appenders
	 * @exclude   A list of appender names to exclude from this category
	 */
	coldbox.system.logging.config.LogBoxConfig function category( required name, levelMin, levelMax, appenders, exclude ) {}
	/**
	 * Get a specified category definition
	 *
	 * @name The category name
	 */
	struct function getCategory( required name ) {}
	/**
	 * Check if a category definition exists
	 *
	 * @name The category name
	 */
	boolean function categoryExists( required name ) {}
	/**
	 * Get the configured categories
	 */
	struct function getAllCategories() {}
	/**
	 * Get all the configured appenders
	 */
	struct function getAllAppenders() {}
	/**
	 * Exclude appenders from a list of appenders
	 *
	 * @appenders A list of appenders to exclude from
	 * @exclude   A list of appenders to exclude
	 */
	string function excludeAppenders( required string appenders, required string exclude ) {}
	/**
	 * Add categories to the DEBUG level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function debug() {}
	/**
	 * Add categories to the INFO level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function info() {}
	/**
	 * Add categories to the WARN level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function warn() {}
	/**
	 * Add categories to the ERROR level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function error() {}
	/**
	 * Add categories to the FATAL level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function fatal() {}
	/**
	 * Add categories to the OFF level. Send each category as an argument.
	 */
	coldbox.system.logging.config.LogBoxConfig function off() {}
	/**
	 * Convert levels from an incoming structure of data
	 *
	 * @target The structure to look for elements: LevelMin and LevelMax
	 */
	private struct function convertLevels( required target ) {}
	/**
	 * Level checks on incoming levels
	 *
	 * @levelMin
	 * @levelMax
	 *
	 * @throws InvalidLevel
	 */
	private function levelChecks( required levelMin, required levelMax ) {}
}
