// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/modules/JSONPrettyPrint/models/CFMLPrinter.cfc — do not edit.
component {
	property name="ANSIPrint" inject="ANSIPrint@JSONPrettyPrint";
	variables.ANSIPrint = new commandbox.system.modules.JSONPrettyPrint.models.ANSIPrint();
	public commandbox.system.modules.JSONPrettyPrint.models.CFMLPrinter function init() {}
	/**
	 * Pretty JSON
	 * @json A string containing JSON, or a complex value that can be serialized to JSON
	 * @indent String to use for indenting lines.  Defaults to four spaces.
	 * @lineEnding String to use for line endings.  Defaults to CRLF on Windows and LF on *nix
	 * @spaceAfterColon Add space after each colon like "value": true instead of"value":true
	 * @sortKeys Specify a sort type to sort the keys of json objects: "text" or "textnocase"
	 * @ansiColors A struct of ANSI color codes. If supplied, output will be ANSI encoded. Struct keys are "constant", "key", "number", and "string" and values are valid ANSI escape sequence such as chr( 27 ) & '[38;5;52m'.
	 */
	public string function formatJson( required any json, string indent, string lineEnding, boolean spaceAfterColon, string sortKeys, struct ansiColors ) {}
	private string function printString( json, settings, baseIndent ) {}
}
