// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/modules/JSONPrettyPrint/models/JSONSimpleParser.cfc — do not edit.
component {
	public commandbox.system.modules.JSONPrettyPrint.models.JSONSimpleParser function init() {}
	public struct function parse( src, pos ) {}
	private any function parseObject( src, pos ) {}
	private any function parseArray( src, pos ) {}
	private any function parseElement( src, pos ) {}
	private any function parseKeyValue( src, pos ) {}
	private void function invalidJSON( src, pos ) {}
	private numeric function lineFromChar( src, pos ) {}
}
