// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/core/util/Util.cfc — do not edit.
/**
 * The main ColdBox utility library.
 */
component {
	/**
	 * SERVER/USER/CFML ENGINE HELPERS *
	 */
	private function getClassMappingHelper() {}
	/**
	 * Add a path to the application's custom tag path
	 *
	 * @path The absolute path to the directory containing tags
	 */
	coldbox.system.core.util.Util function addCustomTagPath( required path ) {}
	/**
	 * Add a CFML Mapping to the running engine
	 *
	 * @name     The name of the mapping
	 * @path     The path of the mapping
	 * @mappings A struct of mappings to incorporate instead of one-offs
	 */
	coldbox.system.core.util.Util function addMapping( string name, string path, struct mappings ) {}
	/**
	 * Check if you are in cfthread or not for any CFML Engine
	 *
	 * @path The file target
	 */
	boolean function inThread() {}
	/**
	 * Get the hostname of the executing machine.
	 */
	function discoverInetHost() {}
	/**
	 * Get the server IP Address
	 */
	string function getServerIp() {}
	/**
	 * Get the Java InetAddress object
	 *
	 * @return java.net.InetAddress
	 */
	private function getInetAddress() {}
	/**
	 * Convert an array to struct argument notation
	 *
	 * @target The array to convert
	 */
	struct function arrayToStruct( required array target ) {}
	/**
	 * Get the last modified date of a file
	 *
	 * @filename The file target
	 */
	function fileLastModified( required filename ) {}
	/**
	 * Rip the extension of a filename.
	 *
	 * @filename The file target
	 */
	function ripExtension( required filename ) {}
	/**
	 * Turn any system path, either relative or absolute, into a fully qualified one
	 *
	 * @path The file target
	 */
	function getAbsolutePath( required path ) {}
	/**
	 * Format an incoming json string to a pretty version
	 *
	 * @target The target json to prettify
	 *
	 * @return The prettified json
	 */
	string function prettyJson( string target ) {}
	/**
	 * Opinionated method that serializes json in a more digetstible way:
	 * - queries as array of structs
	 * - no dumb secure prefixes
	 * And it also prettifies the output
	 *
	 * @obj The object to be serialized and prettified
	 */
	string function toPrettyJson( required any obj ) {}
	/**
	 * Opinionated method that serializes json in a more digetstible way:
	 * - queries as array of structs
	 * - no dumb secure prefixes
	 *
	 * @obj The object to be serialized
	 */
	string function toJson( required any obj ) {}
	/**
	 * PlaceHolder Replacer for strings containing <code>${}</code> patterns
	 *
	 * @str      The string target
	 * @settings The structure of settings to use in the replacements
	 *
	 * @return The string with the replacements
	 */
	function placeHolderReplacer( required str, required settings ) {}
	/**
	 * Get the mixer utility
	 *
	 * @return coldbox.system.core.dynamic.MixerUtil
	 */
	function getMixerUtil() {}
	/**
	 * Checks if an object is of the passed in family type
	 *
	 * @family The family to covert it to: handler, interceptor
	 * @target The target object
	 */
	boolean function isFamilyType( required family, required target ) {}
	/**
	 * Decorate an object as a ColdBox Family object
	 *
	 * @family The family to convert it to
	 * @target The target object
	 *
	 * @return The same target object
	 */
	function convertToColdBox( required family, required target ) {}
	/**
	 * Should we stop recursion or not due to class name found: Boolean
	 *
	 * @className      The class name to check
	 * @stopRecursions An array of classes to stop processing for during inheritance trails
	 */
	private boolean function stopClassRecursion( required classname, required stopRecursions ) {}
	/**
	 * Returns a single-level metadata struct that includes all items inhereited from extending classes.
	 *
	 * @component      The component instance or path to get the metadata from
	 * @stopRecursions An array of classes to stop processing for during inheritance trails
	 * @md             A structure containing a copy of the metadata for this level of recursion.
	 *
	 * @return struct of metadata
	 */
	function getInheritedMetaData( required component, array stopRecursions, struct md ) {}
	/**
	 * Get the Hibernate version string from the running engine
	 */
	public string function getHibernateVersion() {}
}
