// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/menu/Menu.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Core Menu Entity
 */
component extends="contentbox.models.BaseEntity" {
	/**
	 * **                          DI
	 */
	property name="menuService" inject="provider:menuService@contentbox" persistent="false";
	property name="menuItemService" inject="provider:menuItemService@contentbox" persistent="false";
	property name="ORMService" inject="provider:entityservice" persistent="false";
	/**
	 * **                          PROPERTIES
	 */
	property name="menuID" column="menuID" fieldtype="id" generator="uuid" length="36" ormtype="string" update="false";
	property name="title" column="title" notnull="true" ormtype="string" length="200" default="" index="idx_menutitle";
	property name="slug" column="slug" notnull="true" ormtype="string" length="200" default="" index="idx_menuslug";
	property name="menuClass" column="menuClass" ormtype="string" length="160" default="";
	property name="listClass" column="listClass" ormtype="string" length="160" default="";
	property name="listType" column="listType" ormtype="string" length="20" default="ul";
	property name="site" notnull="true" cfc="contentbox.models.system.Site" fieldtype="many-to-one" fkcolumn="FK_siteID" lazy="true";
	property name="menuItems" singularName="menuItem" fieldtype="one-to-many" type="array" cfc="contentbox.models.menu.item.BaseMenuItem" fkcolumn="FK_menuID" cascade="all-delete-orphan" inverse="true" lazy="extra";
	variables.menuService = new contentbox.models.menu.MenuService();
	variables.menuItemService = new contentbox.models.menu.MenuItemService();
	variables.site = new contentbox.models.system.Site();
	/**
	 * constructor
	 */
	contentbox.models.menu.Menu function init() {}
	/**
	 * @Override due to bi-directional relationships
	 */
	contentbox.models.menu.Menu function addMenuItem( required menuItem ) {}
	/**
	 * @Override due to bi-directional relationships
	 */
	contentbox.models.menu.Menu function setMenuItems( required array menuItems ) {}
	/**
	 * Creates menu items from raw data objects and attaches them to this menu.
	 *
	 * @rawData The raw data from which to create menu items
	 */
	array function populateMenuItems( required array rawData ) {}
	/**
	 * Retrieves root menu items (only items with no parents)
	 */
	array function getRootMenuItems() {}
	/**
	 * Shortcut to get the site name
	 */
	function getSiteName() {}
	/**
	 * Shortcut to get the site slug
	 */
	function getSiteSlug() {}
	/**
	 * Shortcut to get the site id
	 */
	function getSiteId() {}
	/**
	 * Build a site snapshot
	 */
	struct function getSiteSnapshot() {}
	/**
	 * Recursive function to build menu items hierarchy from raw data
	 *
	 * @rawData The raw data definitions for the menu items
	 */
	private array function createMenuItems( required array rawData ) {}
}
