// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/menu/MenuItemService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright 2012 by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * Apache License, Version 2.0
 *
 * Copyright Since [2012] [Luis Majano and Ortus Solutions,Corp]
 *
 * Licensed under the Apache License, Version 2.0 (the "License" );
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * Service to handle menu items.
 */
component extends="cborm.models.VirtualEntityService" {
	property name="wirebox" inject="wirebox";
	/**
	 * The providers struct holder
	 */
	property name="providers" type="struct";
	/**
	 * Constructor
	 */
	contentbox.models.menu.MenuItemService function init() {}
	/**
	 * Runs after constructor to complete DI
	 */
	function onDIComplete() {}
	/**
	 * Registers a provider with the service
	 *
	 * @type.hint         The type of provider
	 * @providerPath.hint Logical path for getting instance of provider
	 */
	public contentbox.models.menu.MenuItemService function registerProvider( required string type, required string providerPath ) {}
	/**
	 * Unregisters a provider with the service
	 *
	 * @type.hint The type of provider
	 */
	public contentbox.models.menu.MenuItemService function unRegisterProvider( required string type ) {}
	/**
	 * Retrieves a registered provider
	 *
	 * @type.hint The type of provider
	 */
	public any function getProvider( required string type ) {}
}
