// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/ui/ThemeService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Manages ContentBox themes
 */
component {
	property name="settingService" inject="settingService@contentbox";
	property name="siteService" inject="siteService@contentbox";
	property name="widgetService" inject="provider:widgetService@contentbox";
	property name="moduleSettings" inject="coldbox:setting:modules";
	property name="interceptorService" inject="coldbox:interceptorService";
	property name="wirebox" inject="wirebox";
	property name="html" inject="HTMLHelper@coldbox";
	property name="cbHelper" inject="provider:CBHelper@contentbox";
	property name="moduleService" inject="coldbox:moduleService";
	/**
	 * The location of core themes on disk: Defaults to /modules/contentbox/themes
	 */
	property name="coreThemesPath";
	/**
	 * The location of custom themes on disk: Defaults to /modules_app/contentbox-custom/_themes
	 */
	property name="customThemesPath";
	/**
	 * The theme registry of records
	 */
	property name="themeRegistry" type="struct";
	/**
	 * The cache of widgets for the active theme
	 */
	property name="widgetCache" type="struct";
	variables.settingService = new contentbox.models.system.SettingService();
	variables.siteService = new contentbox.models.system.SiteService();
	variables.widgetService = new contentbox.models.ui.WidgetService();
	variables.cbHelper = new contentbox.models.system.CBHelper();
	/**
	 * Constructor
	 */
	contentbox.models.ui.ThemeService function init() {}
	/**
	 * onDIComplete startup the theming services according to loaded module data
	 */
	void function onDIComplete() {}
	/**
	 * Does the current active theme have a maintenance view
	 */
	boolean function themeMaintenanceViewExists() {}
	/**
	 * Get the current active theme's maintenance layout
	 */
	string function getThemeMaintenanceLayout() {}
	/**
	 * Get the current theme's print layouts in ColdBox layout string format
	 *
	 * @format export format
	 * @layout layout name
	 */
	string function getThemePrintLayout( required format, required layout ) {}
	/**
	 * Get the current theme's search layout
	 */
	string function getThemeSearchLayout() {}
	/**
	 * Returns the invocation path for the requested widget from themes service's layout cache
	 *
	 * @widgetName The name of the widget
	 */
	string function getThemeWidgetInvocationPath( required string widgetName ) {}
	/**
	 * This method is called from the UI module to make sure all site themes are online before
	 * serving requets
	 */
	function startupSiteThemes() {}
	/**
	 * Startup a theme in the system, processes interceptions, modules, widgets, etc
	 *
	 * @name           The name of the theme to activate
	 * @processWidgets Process widget registration on activation, defaults to true.
	 * @site           The site id or object we are starting up this theme for
	 */
	function startupTheme( required name, boolean processWidgets, any site ) {}
	/**
	 * Save theme settings as they are coming from form submissions as a struct with a common prefix
	 * cb_theme_{themeName}_{settingName}
	 *
	 * @name     The theme name
	 * @settings The settings struct
	 *
	 * @return ThemeService
	 */
	contentbox.models.ui.ThemeService function saveThemeSettings( required name, required struct settings ) {}
	/**
	 * Get the current active theme record for the current working site
	 */
	struct function getActiveTheme() {}
	/**
	 * Get a theme record from the registry by name.
	 *
	 * @themeName The name of the theme
	 */
	struct function getThemeRecord( required themeName ) {}
	/**
	 * Verify if the passed theme name is the currently working site active theme
	 *
	 * @themeName The name of the theme to check
	 */
	boolean function isActiveTheme( required themeName ) {}
	/**
	 * Activate a specific theme for the current working site
	 *
	 * @themeName The theme name to activate
	 */
	contentbox.models.ui.ThemeService function activateTheme( required themeName ) {}
	/**
	 * Get all registered themes via the registry.
	 */
	struct function getThemes() {}
	/**
	 * Get all registered custom themes via the registry.
	 */
	struct function getCustomThemes() {}
	/**
	 * Build the theme registry via discovery
	 */
	contentbox.models.ui.ThemeService function buildThemeRegistry() {}
	/**
	 * Process a theme record and store appropriate data and cfc registries
	 *
	 * @name           The name of the theme on disk
	 * @path           The path of the theme
	 * @invocationPath The invocation path of the theme
	 * @includePath    The include path of the theme
	 * @type           The type of theme it is: core, custom
	 * @module         The module this theme exists under
	 */
	function processThemeRecord( name, path, invocationPath, includePath, type, module ) {}
	/**
	 * Remove a custom theme only.
	 *
	 * @themeName The theme to remove
	 */
	boolean function removeTheme( required themeName ) {}
	/**
	 * Get constraints for setting fields
	 *
	 * @themeName The name of the theme
	 */
	struct function getSettingsConstraints( required themeName ) {}
	/**
	 * Build out the settings form HTML
	 *
	 * @activeTheme The active theme struct
	 */
	function buildSettingsForm( required struct activeTheme ) {}
	/**
	 * generateModal - Generate the modal for Theme Setting Help
	 *
	 * @settingName   - The name of the setting the Theme Setting Help modal will be created for
	 * @thisSettingMD - The setting struct itself
	 */
	function generateModal( required settingName, required thisSettingMD ) {}
	/**
	 * Get all themes loaded on disk path, only returns directories
	 *
	 * @path The path to check
	 */
	private array function getThemesOnDisk( required path ) {}
	/**
	 * Unregister theme settings
	 *
	 * @settings The settings to unregister
	 *
	 * @return ThemeService
	 */
	private contentbox.models.ui.ThemeService function unregisterThemeSettings( required array settings ) {}
	/**
	 * Register a theme's settings
	 *
	 * @name     The theme name
	 * @settings The settings struct
	 * @site     The site this theme is activated on
	 *
	 * @return ThemeService
	 */
	private contentbox.models.ui.ThemeService function registerThemeSettings( required name, required array settings, required site ) {}
}
