// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/BaseTask.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 *
 * I am the base task implementation.  An abstract class if you will.
 */
component extends="commandbox.system.BaseCommand" {
	/**
	 * Run another task by DSL.
	 * @taskFile The name of the task to run.
	 */
	function task( required taskFile ) {}
	/**
	 * Loads a module into memory from disk.  Relative paths will be resolved
	 * based on the location of the task runner CFC.
	 * The module will be left in memory and will not be unloaded.
	 * If the module is already loaded in memory, nothing will happen.
	 *
	 * @moduleDirectory Path to module folder. Ex: build/modules/myModule/
	 */
	function loadModule( required string moduleDirectory ) {}
	/**
	 * Loads an array of module directories. All modules will be registered first.  Then all will be activated.
	 */
	function loadModules( required array moduleDirectories ) {}
	/**
	 * This resolves an absolute or relative path using the rules of the operating system and CLI.
	 * It doesn't follow CF mappings and will also always return a trailing slash if pointing to
	 * an existing directory.
	 *
	 * Resolve the incoming path from the file system
	 * @path.hint The directory to resolve
	 * @basePath.hint An expanded base path to resolve the path against. Defaults to directory that the task lives in.
	 */
	function resolvePath( required string path, basePath ) {}
}
