// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/security/SecurityService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Our contentbox security service must match our interface: ISecurityService
 */
component {
	property name="authorService" inject="authorService@contentbox";
	property name="settingService" inject="settingService@contentbox";
	property name="siteService" inject="siteService@contentbox";
	property name="cacheStorage" inject="cacheStorage@cbStorages";
	property name="cookieStorage" inject="cookieStorage@cbStorages";
	property name="requestStorage" inject="RequestStorage@cbstorages";
	property name="mailService" inject="mailService@cbmailservices";
	property name="renderer" inject="coldbox:renderer";
	property name="CBHelper" inject="CBHelper@contentbox";
	property name="cache" inject="cachebox:template";
	property name="bCrypt" inject="BCrypt@BCrypt";
	property name="cbCSRF" inject="@cbcsrf";
	property name="encryptionKey";
	variables.authorService = new contentbox.models.security.AuthorService();
	/**
	 * Constructor
	 */
	contentbox.models.security.SecurityService function init() {}
	/**
	 * Update an author's last login timestamp
	 *
	 * @author The author object
	 */
	contentbox.models.security.Author function updateAuthorLoginTimestamp( required author ) {}
	/**
	 * Alias to getAuthorSession() created to satisfy JWT Services
	 */
	function getUser() {}
	/**
	 * Tries to get the currently logged in user by using our lookup algorithm:
	 *
	 * - Look in request storage
	 * - Look in cache
	 * - Look in remember me cookie
	 * - Tough look, you are an invalid user, return an unauthenticated user
	 *
	 * @return Logged in or new author object
	 */
	contentbox.models.security.Author function getAuthorSession() {}
	/**
	 * Verifies if a user is logged in or not. Required for JWT Services
	 */
	boolean function isLoggedIn() {}
	/**
	 * Logs an authenticated author into the system. Required for JWT services
	 *
	 * @author The author to log in
	 */
	contentbox.models.security.Author function login( required author ) {}
	/**
	 * Delete an author session wether web or api based: Required for JWT services
	 *
	 * @return SecurityService
	 */
	contentbox.models.security.SecurityService function logout() {}
	/**
	 * Authenticate an author via ContentBox credentials. If the user is not valid an InvalidCredentials is thrown. Required for JWT services
	 *
	 * The usage of the LogThemIn boolean flag is essential for two-factor authentication, where a user is authenticated
	 * but not yet validated by a two-factor mechanism.  Thus, the default is to ONLY authenticate but not log them in yet.
	 *
	 * For our RESTFul API, we can do an authenticate and login at the same time.
	 *
	 * @username  The username to validate
	 * @password  The password to validate
	 * @logThemIn If true, we will log them in automatically, else it will be the caller's job to do so via the `login()` method.
	 *
	 * @return User : The logged in user object
	 *
	 * @throws InvalidCredentials
	 */
	contentbox.models.security.Author function authenticate( required username, required password, boolean logThemIn ) {}
	/**
	 * Leverages bcrypt to do a one way encrypt of a string using our salts
	 *
	 * @string The string to bcrypt
	 */
	string function encryptString( required string ) {}
	/**
	 * This function will store a reset token in hash for the user to pickup on password resets
	 *
	 * @author The author to create the reset token for.
	 */
	string function generateResetToken( required Author author ) {}
	/**
	 * Send password reminder email, this verifies that the email is valid and they must click on the token
	 * link in order to reset their password.
	 *
	 * @author      The author to send the reminder to
	 * @adminIssued Was this reset issued by a user or an admin
	 * @issuer      The admin that issued the reset
	 *
	 * @return The mailing results of the password reminder: struct.
	 */
	struct function sendPasswordReminder( required Author author, boolean adminIssued, Author issuer ) {}
	/**
	 * This function validates an incoming pw reset token to figure out their user.
	 * The token is not removed just yet. It will be removed once the password has been reset.
	 *
	 * @token The security token
	 *
	 * @return {error, author}
	 */
	struct function validateResetToken( required token ) {}
	/**
	 * Resets a user's password.
	 *
	 * @token    Security token
	 * @author   The author you are reseting the password for
	 * @password The password you have chosen
	 *
	 * @return {error:boolean, messages:string}
	 */
	struct function resetUserPassword( required token, required Author author, required password ) {}
	/**
	 * Check to authorize a user to view a content entry or page
	 *
	 * @content  The content object
	 * @password The password to check
	 */
	boolean function authorizeContent( required content, required password ) {}
	/**
	 * Checks Whether a content entry or page is protected and user has credentials for it
	 *
	 * @content The content object to check
	 */
	boolean function isContentViewable( required content ) {}
	/**
	 * Get remember me cookie
	 */
	any function getRememberMe() {}
	/**
	 * Get keep me logged in cookie
	 */
	any function getKeepMeLoggedIn() {}
	/**
	 * Set remember me cookie
	 *
	 * @username The username to store
	 * @days     The days to store
	 */
	contentbox.models.security.SecurityService function setRememberMe( required username, required numeric days ) {}
	/**
	 * ContentBox encryption
	 *
	 * @encValue value to encrypt
	 */
	string function encryptIt( required encValue ) {}
	/**
	 * ContentBox Decryption
	 *
	 * @decValue value to decrypt
	 */
	string function decryptIt( required decValue ) {}
	/**
	 * Verifies we have a salt in our installation
	 * if not, it will generate a new cb_enc_key
	 */
	string function getEncryptionKey() {}
	/**
	 * Get Real IP, by looking at clustered, proxy headers and locally.
	 */
	function getRealIP() {}
	/**
	 * Get password content protected salt
	 *
	 * @content The content object
	 */
	private string function getContentProtectedHash( required content ) {}
}
