// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/qb@8eaab747f040 models/Query/JoinClause.cfc — do not edit.
/**
 * Represents a Join clause in a sql statement
 */
component extends="qb.models.Query.QueryBuilder" {
	/**
	 * A reference to the parent query to which this join clause belongs.
	 */
	property name="joiningQuery" type="qb.models.Query.QueryBuilder";
	/**
	 * The join type of the join clause.
	 */
	property name="type" type="string";
	/**
	 * The table to join.
	 */
	property name="table" type="any";
	/**
	 * In the {cross,outer}Apply case, the already-toSql'd string of the table expr source.
	 * e.g. will be a string like "select 1 from foo where x = ?"
	 */
	property name="lateralRawExpression" type="string";
	/**
	 * Bindings belonging to a lateral source. These participate in duplicate
	 * join comparison while the parent query owns the executable bindings.
	 */
	property name="lateralBindings" type="array";
	variables.joiningQuery = new qb.models.Query.QueryBuilder();
	/**
	 * Creates a basic join clause.
	 *
	 * @joiningQuery A reference to the query to which this join clause belongs.
	 * @type The join type of this join clause.
	 * @table The table to join.
	 * @lateralRawExpression The already-compiled table expression for a lateral join.
	 * @lateralBindings Bindings belonging to the lateral table expression.
	 *
	 * @return qb.models.Query.JoinClause
	 */
	public qb.models.Query.JoinClause function init( required QueryBuilder joiningQuery, required string type, required any table, string lateralRawExpression, array lateralBindings ) {}
	/**
	 * Add a column condition to the join statement.
	 *
	 * @first The name of the first column with which to join. A closure can be passed to create nested join statements.
	 * @operator The join operator to use.
	 * @second The name of the second column with which to join.
	 * @combinator The combinator to use between joins.
	 *
	 * @return qb.models.Query.JoinClause
	 */
	public qb.models.Query.JoinClause function on( required first, operator, second, combinator ) {}
	/**
	 * Add an or column condition to the join statement.
	 *
	 * @first The name of the first column with which to join. A closure can be passed to create nested join statements.
	 * @operator The join operator to use.
	 * @second The name of the second column with which to join.
	 *
	 * @return qb.models.Query.JoinClause
	 */
	public qb.models.Query.JoinClause function orOn( required first, operator, second ) {}
	/**
	 * Returns whether the object is a JoinClause.
	 * This exists because isInstanceOf is super slow!
	 *
	 * @returns boolean
	 */
	public boolean function isJoin() {}
}
