// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/qb@8eaab747f040 models/Query/JsonQueryBuilderSupport.cfc — do not edit.
/**
 * Exposes the public JSON builder API while delegating JSON definition work
 * to the lazily instantiated JsonQueryClause collaborator.
 */
component {
	/**
	 * Finds a JSON path separator after any known table qualifier. Table aliases
	 * may themselves contain arrows, particularly aliases generated by Quick.
	 */
	public numeric function getJsonPathStart( required string column ) {}
	/**
	 * Creates a grammar-aware JSON scalar path expression.
	 *
	 * The explicit form accepts a column and an array of path segments. Arrow
	 * syntax is accepted as a shortcut and is normalized to the same shape.
	 *
	 * @column The JSON column, or an arrow path such as `profile->name`.
	 * @path The JSON object keys and array indexes to traverse.
	 * @alias An optional select alias.
	 *
	 * @return A typed column definition understood by each grammar.
	 */
	public struct function jsonPath( required string column, array path, string alias ) {}
	/**
	 * Adds a JSON containment predicate.
	 *
	 * Explicit: `whereJsonContains( "profile", [ "languages" ], "en" )`
	 * Shortcut: `whereJsonContains( "profile->languages", "en" )`
	 */
	public qb.models.Query.QueryBuilder function whereJsonContains( required string column, any path, any value, string combinator, boolean negate ) {}
	public qb.models.Query.QueryBuilder function orWhereJsonContains( required string column, any path, any value ) {}
	public qb.models.Query.QueryBuilder function whereJsonDoesntContain( required string column, any path, any value ) {}
	public qb.models.Query.QueryBuilder function orWhereJsonDoesntContain( required string column, any path, any value ) {}
	/**
	 * Adds a JSON path existence predicate.
	 *
	 * Explicit: `whereJsonExists( "profile", [ "name" ] )`
	 * Shortcut: `whereJsonExists( "profile->name" )`
	 */
	public qb.models.Query.QueryBuilder function whereJsonExists( required string column, array path, string combinator, boolean negate ) {}
	public qb.models.Query.QueryBuilder function orWhereJsonExists( required string column, array path ) {}
	public qb.models.Query.QueryBuilder function whereJsonDoesntExist( required string column, array path ) {}
	public qb.models.Query.QueryBuilder function orWhereJsonDoesntExist( required string column, array path ) {}
	/**
	 * Adds a JSON array length predicate.
	 *
	 * Explicit: `whereJsonLength( "profile", [ "languages" ], ">", 1 )`
	 * Shortcut: `whereJsonLength( "profile->languages", ">", 1 )`
	 * Explicit equality shortcut: `whereJsonLength( "profile", [ "languages" ], 1 )`
	 * Arrow equality shortcut: `whereJsonLength( "profile->languages", 1 )`
	 */
	public qb.models.Query.QueryBuilder function whereJsonLength( required string column, any path, any operator, any value, string combinator ) {}
	public qb.models.Query.QueryBuilder function orWhereJsonLength( required string column, any path, any operator, any value ) {}
}
