// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/qb@8eaab747f040 models/Query/QueryValidator.cfc — do not edit.
/**
 * Validates query builder inputs using an immutable snapshot of the builder's
 * validation settings.
 */
component {
	property name="validateOperatorsAndCombinators" type="boolean";
	property name="validateDuplicateSelectColumns" type="boolean";
	property name="validateQueryExecuteReturnType" type="boolean";
	/**
	 * Creates a validator for one immutable set of builder settings.
	 */
	public qb.models.Query.QueryValidator function init( boolean validateOperatorsAndCombinators, boolean validateDuplicateSelectColumns, boolean validateQueryExecuteReturnType ) {}
	/**
	 * Returns whether a value is not a supported SQL operator.
	 */
	public boolean function isInvalidOperator( any operator ) {}
	/**
	 * Throws when operator validation is enabled and the value is unsupported.
	 */
	public void function validateOperator( any operator ) {}
	/**
	 * Throws when combinator validation is enabled and the value is unsupported.
	 */
	public void function validateCombinator( required string combinator ) {}
	/**
	 * Throws when an ORDER BY direction is unsupported.
	 */
	public void function validateOrderDirection( required string direction ) {}
	/**
	 * Validates that all statically identifiable select output names are unique.
	 */
	public void function validateUniqueSelectColumns( required array columns, required grammar ) {}
	/**
	 * Guards or removes native queryExecute return type options.
	 */
	public void function validateQueryExecuteOptions( required struct options ) {}
	/**
	 * Returns a statically identifiable output name for a selected column.
	 */
	private any function getSelectOutputName( required struct column, required grammar ) {}
	/**
	 * Normalizes an output name for the case-insensitive keys used by CFML structs.
	 */
	private string function normalizeSelectOutputName( required string outputName ) {}
}
