// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/cborm@3cd94ac1b256 models/EventHandler.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This Event Handler listens to ORM events and announces them as ColdBox events.
 * This event handler should ONLY be used for CFML engines that support ORM event handlers.
 *
 * If you are using BoxLang PRIME ORM, use the BXEventHandler.cfc instead.
 */
component extends="coldbox.system.remote.ColdboxProxy" {
	/**
	 * preLoad called by hibernate which in turn announces a coldbox interception: ORMPreLoad
	 */
	public void function preLoad( any entity ) {}
	/**
	 * postLoad called by hibernate which in turn announces a coldbox interception: ORMPostLoad
	 */
	public void function postLoad( any entity ) {}
	/**
	 * postDelete called by hibernate which in turn announces a coldbox interception: ORMPostDelete
	 */
	public void function postDelete( any entity ) {}
	/**
	 * preDelete called by hibernate which in turn announces a coldbox interception: ORMPreDelete
	 */
	public void function preDelete( any entity ) {}
	/**
	 * preUpdate called by hibernate which in turn announces a coldbox interception: ORMPreUpdate
	 */
	public void function preUpdate( any entity, Struct oldData ) {}
	/**
	 * postUpdate called by hibernate which in turn announces a coldbox interception: ORMPostUpdate
	 */
	public void function postUpdate( any entity ) {}
	/**
	 * preInsert called by hibernate which in turn announces a coldbox interception: ORMPreInsert
	 */
	public void function preInsert( any entity ) {}
	/**
	 * postInsert called by hibernate which in turn announces a coldbox interception: ORMPostInsert
	 */
	public void function postInsert( any entity ) {}
	/**
	 * preSave called by ColdBox Base service before save() calls
	 */
	public void function preSave( any entity ) {}
	/**
	 * postSave called by ColdBox Base service after transaction commit or rollback via the save() method
	 */
	public void function postSave( any entity ) {}
	/**
	 * Called before the session is flushed.
	 */
	public void function preFlush( any entities ) {}
	/**
	 * Called after the session is flushed.
	 */
	public void function postFlush( any entities ) {}
	/**
	 * postNew called by ColdBox which in turn announces a coldbox interception: ORMPostNew
	 */
	public void function postNew( any entity, any entityName ) {}
	/**
	 * Get the system Event Manager
	 */
	public any function getEventManager() {}
	/**
	 * process entity injection
	 *
	 * @entityName the entity to process, we use hash codes to identify builders
	 * @entity     The entity object
	 *
	 * @return The processed entity
	 */
	public function processEntityInjection( required entityName, required entity ) {}
	/**
	 * Lazy loading of the ORM utility according to the CFML engine you are on
	 *
	 * @return cborm.models.util.IORMUtil
	 */
	private function getOrm() {}
}
