// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/cache/CacheFactory.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ----
 *
 * The main CacheBox factory and configuration of caches. From this factory
 * is where you will get all the caches you need to work with or register more caches.
 *
 * @author Luis Majano
 */
component {
	/**
	 * The unique factory id
	 */
	property name="factoryId";
	/**
	 * The factory version
	 */
	property name="version";
	/**
	 * The CacheBox Configuration object linkage
	 */
	property name="config";
	/**
	 * The ColdBox object linkage
	 */
	property name="coldbox";
	/**
	 * The WireBox object linkage
	 */
	property name="wirebox";
	/**
	 * The LogBox object linkage
	 */
	property name="logbox";
	/**
	 * A configured log class
	 */
	property name="log";
	/**
	 * The Event Manager object linkage
	 */
	property name="eventManager";
	/**
	 * The array of events this factory registers
	 */
	property name="eventStates" type="array";
	/**
	 * The registered caches this factory keeps track of
	 */
	property name="caches" type="struct";
	/**
	 * The Global AsyncManager
	 *
	 * @see coldbox.system.async.AsyncManager
	 */
	property name="asyncManager";
	/**
	 * The logBox task scheduler executor
	 *
	 * @see coldbox.system.async.executors.ScheduledExecutor
	 */
	property name="taskScheduler";
	/**
	 * Constructor
	 *
	 * @config              The CacheBoxConfig object or path to use to configure this instance of CacheBox. If not passed then CacheBox will instantiate the default configuration.
	 * @config.doc_generic  coldbox.system.cache.config.CacheBoxConfig
	 * @coldbox             A coldbox application that this instance of CacheBox can be linked to, if not using it, just ignore it.
	 * @coldbox.doc_generic coldbox.system.web.Controller
	 * @factoryID           A unique ID or name for this factory. If not passed I will make one up for you.
	 * @wirebox             A configured wirebox instance to get logbox, asyncManager, and EventManager from.  If not passed, I will create new ones.
	 */
	coldbox.system.cache.CacheFactory function init( config, coldbox, factoryId, wirebox ) {}
	/**
	 * Configure the cache factory for operation, called by the init().
	 * You can also re-configure CacheBox programmatically.
	 *
	 * @config A CacheBox Config object, path or struct to configure LogBox with.
	 */
	function configure( required config ) {}
	/**
	 * Register all the configured listeners in the configuration file
	 *
	 * @throws CacheBox.ListenerCreationException
	 */
	coldbox.system.cache.CacheFactory function registerListeners() {}
	/**
	 * Get a reference to a registered cache in this factory.  If the cache does not exist it will return an exception. Type: coldbox.system.cache.providers.ICacheProvider
	 *
	 * @name The cache name to get
	 *
	 * @return coldbox.system.cache.providers.ICacheProvider
	 *
	 * @throws CacheFactory.CacheNotFoundException
	 */
	function getCache( required name ) {}
	/**
	 * Register a new instantiated cache with this cache factory
	 *
	 * @cache             The cache to register
	 * @cache.doc_generic coldbox.system.cache.providers.ICacheProvider
	 */
	coldbox.system.cache.CacheFactory function addCache( required cache ) {}
	/**
	 * Add a default named cache to our registry, create it, config it, register it and return it of type: coldbox.system.cache.providers.ICacheProvider
	 *
	 * @name  The name of the default cache to create
	 * @throw CacheFactory.InvalidNameException,CacheFactory.CacheExistsException
	 *
	 * @return coldbox.system.cache.providers.ICacheProvider
	 */
	function addDefaultCache( required name ) {}
	/**
	 * Recursively sends shutdown commands to al registered caches and cleans up in preparation for shutdown
	 */
	coldbox.system.cache.CacheFactory function shutdown() {}
	/**
	 * Send a shutdown command to a specific cache provider to bring down gracefully. It also removes it from the cache factory
	 *
	 * @name The name of the cache to shutdown
	 */
	coldbox.system.cache.CacheFactory function shutdownCache( required name ) {}
	/**
	 * Remove the cache factory from scope registration if enabled, else does nothing
	 */
	coldbox.system.cache.CacheFactory function removeFromScope() {}
	/**
	 * Try to remove a named cache from this factory, returns Boolean if successful or not
	 *
	 * @name The name of the cache to remove
	 */
	boolean function removeCache( required name ) {}
	/**
	 * Remove all the registered caches in this factory, this triggers individual cache shutdowns
	 */
	coldbox.system.cache.CacheFactory function removeAll() {}
	/**
	 * A nice way to call reap on all registered caches
	 */
	coldbox.system.cache.CacheFactory function reapAll() {}
	/**
	 * Check if the passed in named cache is already registered in this factory or not
	 */
	boolean function cacheExists( required name ) {}
	/**
	 * Replace a registered named cache with a new decorated cache of the same name.
	 *
	 * @cache                      The name of the cache to replace or the actual instance of the cache to replace
	 * @cache.doc_generic          coldbox.system.cache.providers.ICacheProvider or string
	 * @decoratedCache             The decorated cache manager instance to replace with of type coldbox.system.cache.providers.ICacheProvider
	 * @decoratedCache.doc_generic coldbox.system.cache.providers.ICacheProvider
	 */
	coldbox.system.cache.CacheFactory function replaceCache( required cache, required decoratedCache ) {}
	/**
	 * Clears all the elements in all the registered caches without de-registrations
	 */
	coldbox.system.cache.CacheFactory function clearAll() {}
	/**
	 * Expires all the elements in all the registered caches without de-registrations
	 */
	coldbox.system.cache.CacheFactory function expireAll() {}
	/**
	 * Get the array of caches registered with this factory
	 */
	array function getCacheNames() {}
	/**
	 * Checks if Coldbox application controller is linked
	 */
	boolean function isColdBoxLinked() {}
	/**
	 * Get the default cache provider of type coldbox.system.cache.providers.ICacheProvider"
	 *
	 * @return coldbox.system.cache.providers.ICacheProvider
	 */
	function getDefaultCache() {}
	/**
	 * Get the scope registration information
	 */
	struct function getScopeRegistration() {}
	/**
	 * Create a new cache according the the arguments, register it and return it of type: coldbox.system.cache.providers.ICacheProvider
	 *
	 * @name       The name of the cache to create
	 * @provider   The provider class path of the cache to add
	 * @properties The configuration properties of the cache
	 *
	 * @return coldbox.system.cache.providers.ICacheProvider
	 */
	function createCache( required name, required provider, struct properties ) {}
	/**
	 * Register this cachefactory on a user specified scope
	 */
	private coldbox.system.cache.CacheFactory function doScopeRegistration() {}
	/**
	 * Register a new cache on this cache factory
	 *
	 * @cache             The cache instance to register with this factory of type: coldbox.system.cache.providers.ICacheProvider
	 * @cache.doc_generic coldbox.system.cache.providers.ICacheProvider
	 *
	 * @throws CacheFactory.CacheExistsException
	 */
	private coldbox.system.cache.CacheFactory function registerCache( required cache ) {}
}
