// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/context/EventHandlerBean.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * I model a ColdBox Event Handler Execution
 */
component {
	/**
	 * Invocation path
	 */
	property name="invocationPath";
	/**
	 * The handler to execute
	 */
	property name="handler";
	/**
	 * The method to execute
	 */
	property name="method";
	/**
	 * The module assignment
	 */
	property name="module";
	/**
	 * Missing action method
	 */
	property name="missingAction";
	/**
	 * Private execution
	 */
	property name="isPrivate" type="boolean";
	/**
	 * View dispatching
	 */
	property name="viewDispatch" type="boolean";
	/**
	 * Action metadata
	 */
	property name="actionMetadata" type="struct";
	/**
	 * Handler metadata
	 */
	property name="handlerMetadata" type="struct";
	/**
	 * Registered handler metadata
	 */
	property name="handlerRecord" type="struct";
	/**
	 * Precalculated runnable execution path
	 */
	property name="runnable";
	/**
	 * Precalculated full event string
	 */
	property name="fullEvent";
	/**
	 * Precalculated default event string
	 */
	property name="defaultEvent";
	/**
	 * Registered handler source
	 */
	property name="handlerSource";
	/**
	 * Constructor
	 *
	 * @invocationPath The default invocation path
	 */
	coldbox.system.web.context.EventHandlerBean function init( invocationPath ) {}
	/**
	 * This verifies if a specific action has been tagged with an annotation.
	 *
	 * @key The annotation key to verify
	 *
	 * @return True if the action has been annotated with the key, else false.
	 */
	boolean function actionMetadataExists( required key ) {}
	/**
	 * Return the full action metadata structure or filter by key and default value if needed
	 *
	 * @key          The key to search for in the action metadata
	 * @defaultValue Default value to return if not found
	 *
	 * @return any
	 */
	function getActionMetadata( key, defaultValue ) {}
	/**
	 * Return the full handler metadata structure or filter by key and default value if needed
	 *
	 * @key          The key to search for in the handler metadata
	 * @defaultValue Default value to return if not found
	 *
	 * @return any
	 */
	function getHandlerMetadata( string key, defaultValue ) {}
	/**
	 * Verify if the metadata is loaded or not.
	 */
	boolean function isMetadataLoaded() {}
	/**
	 * Get the full execution string
	 */
	function getFullEvent() {}
	/**
	 * Get the runnable execution path
	 */
	function getRunnable() {}
	/**
	 * Set the invocation path and invalidate derived runnable paths.
	 *
	 * @invocationPath The invocation path
	 *
	 * @return EventHandlerBean
	 */
	coldbox.system.web.context.EventHandlerBean function setInvocationPath( required invocationPath ) {}
	/**
	 * Set the handler and invalidate derived event/runnable paths.
	 *
	 * @handler The handler to execute
	 *
	 * @return EventHandlerBean
	 */
	coldbox.system.web.context.EventHandlerBean function setHandler( required handler ) {}
	/**
	 * Set the method and invalidate derived event paths.
	 *
	 * @method The method to execute
	 *
	 * @return EventHandlerBean
	 */
	coldbox.system.web.context.EventHandlerBean function setMethod( required method ) {}
	/**
	 * Set the module and invalidate derived event paths.
	 *
	 * @module The module assignment
	 *
	 * @return EventHandlerBean
	 */
	coldbox.system.web.context.EventHandlerBean function setModule( required module ) {}
	/**
	 * Apply a registered handler record to the bean.
	 *
	 * @handlerRecord The registered handler metadata
	 *
	 * @return EventHandlerBean
	 */
	coldbox.system.web.context.EventHandlerBean function setHandlerRecord( required struct handlerRecord ) {}
	/**
	 * Is this a module execution
	 */
	boolean function isModule() {}
	/**
	 * Are we in missing action execution
	 */
	boolean function isMissingAction() {}
}
