// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/util/DateUtil.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Static date utility object
 */
component {
	/**
	 * Return now() in UTC
	 */
	function nowUTC() {}
	/**
	 * Conver the incoming date time to UTC using the dateTimeFormat() method
	 *
	 * @see      https://cfdocs.org/datetimeformat
	 * @dateTime The date time object/string to convert
	 */
	function toUTC( required dateTime ) {}
	/**
	 * Convert epoch milliseconds into local time object.
	 *
	 * @epoch The epoch time in milliseconds
	 *
	 * @return ColdFusion date/time equivalent
	 */
	function epochToLocal( epoch ) {}
}
