#!/usr/bin/env bash
# Prints the Homebrew formula for one clif release, from its archives.
#
#   packaging/homebrew/formula.sh <version> <dir>
#
# <dir> holds the release's clif-{darwin,linux}-{amd64,arm64}.tar.gz. The
# formula installs the prebuilt binary rather than building from source: CGO
# and the tree-sitter grammar make a source build slow, and the binaries are
# the ones every editor extension already runs. It also links cfmleditor-lsp,
# the name before the rename, which older editor extensions look for on PATH.
set -euo pipefail

version="${1:?usage: formula.sh <version> <dir>}"
dir="${2:?usage: formula.sh <version> <dir>}"
version="${version#v}"
base="https://github.com/cfmleditor/clif/releases/download/v${version}"

sha() {
	local f="${dir}/clif-$1.tar.gz"
	[ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
	shasum -a 256 "$f" | cut -d' ' -f1
}

cat <<FORMULA
# Generated by packaging/homebrew/formula.sh in cfmleditor/clif for each
# release. Edit that script, not this file.
class Clif < Formula
  desc "CFML language server and command-line checks (formerly cfmleditor-lsp)"
  homepage "https://github.com/cfmleditor/clif"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/clif-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "${base}/clif-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${base}/clif-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "${base}/clif-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin.install "clif"
    bin.install_symlink "clif" => "cfmleditor-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clif version")
    assert_match "usage: clif unresolved", shell_output("#{bin}/clif unresolved --help")
  end
end
FORMULA
