// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/media/MediaService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Manage's the system's media files
 */
component {
	property name="settingService" inject="settingservice@contentbox";
	/**
	 * ContentBox Providers Map
	 */
	property name="providers" type="struct";
	variables.provider = new contentbox.models.media.BaseProvider();
	variables.settingService = new contentbox.models.system.SettingService();
	/**
	 * Constructor
	 *
	 * @wirebox.inject wirebox
	 */
	contentbox.models.media.MediaService function init( required wirebox ) {}
	/**
	 * Get the default system media provider name as a string
	 */
	function getDefaultProviderName() {}
	/**
	 * Get the default system media provider object
	 *
	 * @return contentbox.models.media.BaseProvider
	 */
	contentbox.models.media.BaseProvider function getDefaultProvider() {}
	/**
	 * Get a named provider object
	 *
	 * @name The provider to get,that must be registered
	 *
	 * @return contentbox.models.media.BaseProvider
	 */
	contentbox.models.media.BaseProvider function getProvider( required name ) {}
	/**
	 * Register a new media provider in ContentBox
	 *
	 * @provider The provider object to register
	 */
	contentbox.models.media.MediaService function registerProvider( required contentbox.models.media.BaseProvider provider ) {}
	/**
	 * UnRegister a provider in ContentBox
	 *
	 * @name The name of the provider to unregister
	 */
	contentbox.models.media.MediaService function unRegisterProvider( required name ) {}
	/**
	 * Get an array of registered providers in alphabetical order
	 */
	array function getRegisteredProviders() {}
	/**
	 * Get an array of registered provider names in alphabetical order with their display names
	 *
	 * @return array of structs { name, displayName, description }
	 */
	array function getRegisteredProvidersMap() {}
	/**
	 * Get the path to the core media root
	 *
	 * @absolute Return the absolute path or relative, if absolute then it expands the path.
	 */
	function getCoreMediaRoot( required boolean absolute ) {}
}
