// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/wheelstest/system/util/MixerUtil.cfc — do not edit.
/**
 * A utility object that provides runtime mixins
 */
component {
	property name="mixins";
	/**
	 * Constructor
	 */
	wheels.wheelstest.system.util.MixerUtil function init() {}
	/**
	 * Start method injection set -> Injects: includeitMixin,injectMixin,removeMixin,invokerMixin,injectPropertyMixin,removePropertyMixin,getPropertyMixin
	 *
	 * @target target object
	 */
	function start( required target ) {}
	/**
	 * Remove mixed methods
	 *
	 * @target target object
	 */
	wheels.wheelstest.system.util.MixerUtil function stop( required target ) {}
	/**
	 * Exposes a private function publicly
	 */
	wheels.wheelstest.system.util.MixerUtil function exposeMixin( required method, newName ) {}
	/**
	 * Executes a dynamic method according to injected name
	 */
	function methodProxy() {}
	/**
	 * Include a template
	 */
	wheels.wheelstest.system.util.MixerUtil function includeitMixin( required template ) {}
	/**
	 * Get the variables scope
	 */
	function getVariablesMixin() {}
	/**
	 * Injects a method into the class
	 */
	wheels.wheelstest.system.util.MixerUtil function injectMixin( required name, required udf ) {}
	/**
	 * Get a property from a scope
	 */
	function getPropertyMixin( required name, scope, defaultValue ) {}
	/**
	 * injects a property into the passed scope
	 */
	wheels.wheelstest.system.util.MixerUtil function injectPropertyMixin( required propertyName, required propertyValue, scope ) {}
	/**
	 * Removes a method in a class
	 */
	wheels.wheelstest.system.util.MixerUtil function removeMixin( required UDFName ) {}
	/**
	 * Removes a method in a class
	 */
	wheels.wheelstest.system.util.MixerUtil function removePropertyMixin( required propertyName, scope ) {}
	/**
	 * Calls private/packaged/public methods
	 */
	function invokerMixin( required method, argCollection, argList ) {}
}
