// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/services/BaseService.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * Base Helper class for all ColdBox services
 */
component {
	/**
	 * ColdBox Controller
	 */
	property name="controller";
	/**
	 * Service logger
	 */
	property name="log";
	/**
	 * Env Delegate
	 */
	property name="envDelegate";
	/**
	 * Once configuration file loads
	 */
	function onConfigurationLoad() {}
	/**
	 * Once aspects are loaded
	 */
	function afterAspectsLoad() {}
	/**
	 * On framework shutdown
	 */
	function onShutdown() {}
	/**
	 * Get the service logger
	 */
	function getLogger() {}
	/**
	 * Get the Env delegate
	 */
	function getEnvDelegate() {}
	/**
	 * Get the LogBox instance (lazy-cached)
	 */
	function getLogBox() {}
	/**
	 * Get the CacheBox instance (lazy-cached)
	 */
	function getCacheBox() {}
}
