// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/services/ModuleService.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * I oversee and manage ColdBox modules
 */
component extends="coldbox.system.web.services.BaseService" {
	/**
	 * Logger object
	 */
	property name="logger";
	/**
	 * Configuration cache dictionary
	 */
	property name="mConfigCache";
	/**
	 * Module registry dictionary
	 */
	property name="moduleRegistry";
	/**
	 * Engine Mapping registry Dictionary
	 */
	property name="mappingRegistry";
	/**
	 * App config overrides registry
	 */
	property name="appConfigModules";
	/**
	 * Constructor
	 */
	coldbox.system.web.services.ModuleService function init( required controller ) {}
	/**
	 * Called by loader service when configuration file loads
	 */
	coldbox.system.web.services.ModuleService function onConfigurationLoad() {}
	/**
	 * Get all the module config overrides from the app's config/modules directory, this is used to merge into the module's config struct when loading a module,
	 * this allows you to have environment specific overrides for modules without having to touch the module's code or have multiple versions of the same module for different environments
	 */
	private void function registerModuleAppOverrides() {}
	/**
	 * Called when the application stops
	 */
	coldbox.system.web.services.ModuleService function onShutdown() {}
	/**
	 * Get the discovered module's registry structure
	 */
	struct function getModuleRegistry() {}
	/**
	 * Return the loaded module's configuration objects
	 */
	struct function getModuleConfigCache() {}
	/**
	 * Rescan the module locations directories and re-register all located modules, this{method does NOT register or activate any modules, it just reloads the found registry
	 */
	coldbox.system.web.services.ModuleService function rebuildModuleRegistry() {}
	/**
	 * Register all modules for the application. Usually called by framework to load configuration data.
	 */
	coldbox.system.web.services.ModuleService function registerAllModules() {}
	/**
	 * Register and activate a new module
	 *
	 * @moduleName     The name of the module to load.
	 * @invocationPath The module's invocation path to its root from the webroot (the instantiation path,ex:myapp.myCustomModules), if empty we use registry location, if not we are doing a explicit name+path registration. Do not include the module name, you passed that in the first argument right
	 */
	function registerAndActivateModule( required moduleName, invocationPath ) {}
	/**
	 * Register a module's configuration information and config object
	 *
	 * @moduleName     The name of the module to load.
	 * @invocationPath The module's invocation path to its root from the webroot (the instantiation path,ex:myapp.myCustomModules), if empty we use registry locatioif not we are doing a explicit name+path registration. Do not include the module name, you passed that in the first argument right
	 * @parent         The name of the parent module
	 * @force          Force a registration
	 * @bundle         If the module belongs to a bundle
	 * @parentInjector The parent injector if used
	 *
	 * @return If the module registered or not
	 *
	 * @throws InvalidModuleName - When a module is not on disk
	 */
	boolean function registerModule( required moduleName, invocationPath, parent, boolean force, bundle, parentInjector ) {}
	/**
	 * Load all module mappings
	 */
	coldbox.system.web.services.ModuleService function loadMappings() {}
	/**
	 * Go over all the loaded module configurations and activate them for usage within the{application
	 */
	function activateAllModules() {}
	/**
	 * Activate a module
	 *
	 * @moduleName The name of the module to activate. It must exist and be valid. Else we ignore it by logging a warning
	 *
	 * @return The Module Service
	 *
	 * @throws IllegalModuleState - When the requested module to active is not registered
	 */
	coldbox.system.web.services.ModuleService function activateModule( required moduleName ) {}
	/**
	 * Reload a targeted module
	 *
	 * @moduleName The module
	 */
	coldbox.system.web.services.ModuleService function reload( required moduleName ) {}
	/**
	 * Reload all modules
	 */
	coldbox.system.web.services.ModuleService function reloadAll() {}
	/**
	 * Get a listing of all loaded modules
	 */
	array function getLoadedModules() {}
	/**
	 * Check and see if a module has been registered
	 *
	 * @moduleName The module
	 */
	function isModuleRegistered( required moduleName ) {}
	/**
	 * Check and see if a module has been activated
	 *
	 * @moduleName The module
	 */
	boolean function isModuleActive( required moduleName ) {}
	/**
	 * Unload a module if found from the configuration
	 *
	 * @moduleName The module
	 *
	 * @return If the module unloaded or not
	 */
	boolean function unload( required moduleName ) {}
	/**
	 * Unload all registered modules
	 */
	coldbox.system.web.services.ModuleService function unloadAll() {}
	/**
	 * Load the module configuration object and return it now loaded
	 *
	 * @config     The config structure
	 * @moduleName The module name
	 * @parent     The parent that invoked the registration
	 * @parent     The parent injector this module will be linked to
	 *
	 * @return struct : { config:class, injector:class }
	 */
	struct function loadModuleConfiguration( required struct config, required moduleName, parent, parentInjector ) {}
	/**
	 * Build the modules registry
	 *
	 * @locations The array of locations to register
	 */
	private function buildRegistry( required array locations ) {}
	/**
	 * Load module settings override from config disk
	 *
	 * @config     The module config struct
	 * @moduleName The target module name
	 */
	private function loadModuleSettingsOverride( required struct config, required moduleName ) {}
	/**
	 * Scan a directory for modules and add them to the registry if not already there, so we can have multiple module locations with order of preference
	 *
	 * @dirPath The path to scan for modules, we will expand it and use the physical path for scanning
	 */
	private function scanModulesDirectory( required dirPath ) {}
	/**
	 * Checks if the module can be loaded or registered
	 *
	 * @moduleName The module to check
	 */
	private boolean function canLoad( required moduleName ) {}
}
