// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/web/services/RequestService.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This service takes care of preparing and creating request contexts. Facades to FORM and URL
 */
component extends="coldbox.system.web.services.BaseService" {
	/**
	 * Constructor
	 *
	 * @controller The ColdBox Controller.
	 */
	coldbox.system.web.services.RequestService function init( required controller ) {}
	/**
	 * Once configuration loads this method is fired by the service loader.
	 */
	function onConfigurationLoad() {}
	/**
	 * Once aspects load this method is fired by the service loader.
	 */
	function afterAspectsLoad() {}
	/**
	 * I capture an incoming request. Returns: coldbox.system.web.context.RequestContext
	 *
	 * @event     Override to instead use this as the main event instead of looking for it in form/url
	 * @proxyCall If true, we ignore routing, since this is a proxy remote call
	 *
	 * @return coldbox.system.web.context.RequestContext
	 */
	any function requestCapture( event, boolean proxyCall ) {}
	/**
	 * Tests if the incoming context is an event cache
	 *
	 * @context                The request context to test for event caching
	 * @context.docbox_generic coldbox.system.web.context.RequestContext
	 * @fwCache                Flag to hard purge the cache if needed
	 */
	coldbox.system.web.services.RequestService function eventCachingTest( required context, boolean fwCache ) {}
	/**
	 * Get the Request context from request scope or create a new one.
	 * Creation will be thread safe so two threads sharing the request scope
	 * don't both create a new context and overwrite
	 *
	 * @return coldbox.system.web.context.RequestContext
	 */
	function getContext( string classPath ) {}
	/**
	 * Get the Request context from request scope or return null if not exists
	 *
	 * @return coldbox.system.web.context.RequestContext or null if not found
	 */
	private function getContextFromScope() {}
	/**
	 * Set the request context into the request scope
	 *
	 * @context Request Context object
	 */
	coldbox.system.web.services.RequestService function setContext( required context ) {}
	/**
	 * Remove the context from scope
	 */
	coldbox.system.web.services.RequestService function removeContext() {}
	/**
	 * Does the request context exist in request scope
	 */
	boolean function contextExists() {}
	/**
	 * Return the flash scope instance in use by the framework.
	 */
	any function getFlashScope() {}
	/**
	 * Rebuild's the Flash RAM Scope if the application spec has changed, else it ignores it
	 */
	coldbox.system.web.services.RequestService function rebuildFlashScope() {}
	/**
	 * Build's the Flash RAM Scope as defined in the application spec.
	 */
	coldbox.system.web.services.RequestService function buildFlashScope() {}
	/**
	 * Creates a new request context object
	 *
	 * @return coldbox.system.web.context.RequestContext
	 */
	function createContext( string classPath ) {}
}
