// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/logging/LogEvent.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This resembles a logging event within LogBox
 */
component {
	/**
	 * The category to log messages under
	 */
	property name="category" default="";
	/**
	 * The timestamp of the log
	 */
	property name="timestamp";
	/**
	 * The message to log
	 */
	property name="message" default="";
	/**
	 * The severity to log with
	 */
	property name="severity" default="";
	/**
	 * Any extra info to log
	 */
	property name="extrainfo" default="";
	/**
	 * Flag to allow serializing complex objects in `extraInfo`.
	 */
	property name ="serializeExtraInfo" type ="boolean" default="true";
	variables.xmlConverter = new coldbox.system.core.conversion.XMLConverter();
	variables.util = new coldbox.system.core.util.Util();
	/**
	 * Constructor
	 *
	 * @message            The message to log.
	 * @severity           The severity level to log.
	 * @extraInfo          Extra information to send to the loggers.
	 * @category           The category to log this message under.  By default it is blank.
	 * @serializeExtraInfo Flag to allow serializing complex objects in `extraInfo`. Default is true.
	 */
	coldbox.system.logging.LogEvent function init( required message, required severity, extraInfo, category, boolean serializeExtraInfo ) {}
	function getXmlConverter() {}
	function getUtil() {}
	/**
	 * Get the extra info as a string representation
	 */
	function getExtraInfoAsString() {}
}
