// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/jline/CommandParser.cfc — do not edit.
/**
 * Copyright Since 2014 CommandBox by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano, Denny Valliant
 *
 * CommandBox Command Line Parser and Tokenizer
 */
component {
	property name='parser' inject='parser';
	function parse( string line, numeric cursor, any context ) {}
}
