// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/commandbox@28a136f9b477 cfml/system/util/jline/SignalHandler.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Platform by Ortus Solutions, Corp
 * www.coldbox.org | www.ortussolutions.com
 * @author Brad Wood, Luis Majano
 * I am a JLine highlighter class that handles terminal signals
 */
component {
	property name='shell' inject='shell';
	variables.shell = new commandbox.system.Shell();
	function handle( signal ) {}
}
