// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/cache/util/ElementCleaner.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 *
 * A ColdBox utility to help clean cached objects for ColdBox Application Caches
 *
 * @author Luis Majano
 */
component {
	/**
	 * Constructor
	 *
	 * @cacheProvider             The associated cache manager/provider of type: coldbox.system.cache.providers.ICacheProvider
	 * @cacheProvider.doc_generic coldbox.system.cache.providers.ICacheProvider
	 */
	coldbox.system.cache.util.ElementCleaner function init( required coldbox.system.cache.providers.ICacheProvider cacheProvider ) {}
	/**
	 * Get the associated cache provider/manager of type: coldbox.system.cache.providers.ICacheProvider
	 *
	 * @return coldbox.system.cache.providers.ICacheProvider
	 */
	coldbox.system.cache.providers.ICacheProvider function getAssociatedCache() {}
	/**
	 * Clears keys using the passed in object key snippet
	 *
	 * @keySnippet The cache key snippet to use
	 * @regex      Use regex or not, defaults to false
	 */
	coldbox.system.cache.util.ElementCleaner function clearByKeySnippet( required keySnippet, boolean regex ) {}
	/**
	 * Clears all the event permutations from the cache according to snippet and querystring.
	 * Be careful when using incomplete event name with query strings as partial event names are not guaranteed to match with query string permutations
	 *
	 * @eventsnippet The event snippet to clear on. Can be partial or full
	 * @queryString  If passed in, it will create a unique hash out of it. For purging purposes
	 */
	coldbox.system.cache.util.ElementCleaner function clearEvent( required eventsnippet, queryString ) {}
	/**
	 * Clears all the event permutations from the cache according to the list of snippets and querystrings.
	 * Be careful when using incomplete event name with query strings as partial event names are not guaranteed to match with query string permutations
	 *
	 * @eventsnippets The comma-delimited list event snippet to clear on. Can be partial or full
	 * @queryString   The comma-delimited list of queryStrings passed in. If passed in, it will create a unique hash out of it. For purging purposes.  If passed in the list length must be equal to the list length of the event snippets passed in
	 */
	coldbox.system.cache.util.ElementCleaner function clearEventMulti( required eventsnippets, queryString ) {}
	/**
	 * Clears all events from the cache
	 */
	coldbox.system.cache.util.ElementCleaner function clearAllEvents() {}
	/**
	 * Clears all view name permutations from the cache according to the view name
	 *
	 * @viewSnippet The view name snippet to purge from the cache
	 */
	coldbox.system.cache.util.ElementCleaner function clearView( required viewSnippet ) {}
	/**
	 * Clears all view name permutations from the cache according to the view name.
	 *
	 * @viewSnippet The comma-delimited list or array of view snippet to clear on. Can be partial or full
	 */
	coldbox.system.cache.util.ElementCleaner function clearViewMulti( required viewSnippets ) {}
	/**
	 * Clears all views from the cache.
	 */
	coldbox.system.cache.util.ElementCleaner function clearAllViews() {}
}
