// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/cache/util/EventURLFacade.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This cfc acts as an URL/FORM facade for event caching.  The associated cache
 * will have to implement the IColdboxApplicationCache in order to retrieve the right
 * prefix keys.
 */
component {
	property name="cacheProvider";
	/**
	 * Constructor
	 *
	 * @cacheProvider Provider to connect to
	 */
	coldbox.system.cache.util.EventURLFacade function init( required cacheProvider ) {}
	/**
	 * Build an app link via the request context object
	 */
	string function buildAppLink() {}
	/**
	 * Build a unique hash from an incoming request context
	 * Note: the 'event' key is always ignored from the request collection
	 *
	 * @event           A request context object
	 * @targetContext   The targeted request context object
	 * @eventDictionary The event metadata containing cache annotations
	 */
	string function getUniqueHash( required event, required struct eventDictionary ) {}
	/**
	 * Build a unique hash according to an incoming query string, mostly used when calling the clear functions of
	 * cache providers
	 *
	 * @args A querystring based argument collection
	 */
	function buildHash( required string args ) {}
	/**
	 * Build an event key according to passed in params
	 *
	 * @targetEvent     The targeted ColdBox event executed
	 * @targetContext   The targeted request context object
	 * @eventDictionary The event metadata containing cache annotations
	 */
	string function buildEventKey( required targetEvent, required targetContext, required struct eventDictionary ) {}
	/**
	 * Build an event key according to passed in params
	 *
	 * @keySuffix   The key suffix used in the cache key
	 * @targetEvent The targeted ColdBox event executed
	 * @targetArgs  A query string based argument collection like a query string
	 */
	string function buildEventKeyNoContext( required keySuffix, required targetEvent, required targetArgs ) {}
	/**
	 * Builds a basic cache key without the hash component
	 *
	 * @keySuffix   The key suffix used
	 * @targetEvent The targeted ColdBox event string
	 */
	string function buildBasicCacheKey( required keySuffix, required targetEvent ) {}
}
