// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/testing/BaseModelTest.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * Standalone base test case for model objects
 */
component extends="coldbox.system.testing.BaseTestCase" {
	/**
	 * Setup a model to test
	 */
	function setup() {}
}
