// Generated by cmd/cfstubgen from https://github.com/ColdBox/coldbox-platform@c318d8d9a48a system/testing/VirtualApp.cfc — do not edit.
/**
 * Copyright Since 2005 ColdBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This object is in charge of starting up virtual ColdBox applications used in integration testing.
 * The Virtual applications follow the convention of loading into the application scope.
 */
component {
	variables.cbController = new coldbox.system.testing.mock.web.MockController();
	/**
	 * Constructor
	 *
	 * @appMapping The mapping that points to the ColdBox's application root. This will be expanded via <pre>expandPath()</pre>
	 * @configPath The CFC path to the ColdBox configuration object to load. The default is <pre>config.Coldbox</pre>
	 * @webMapping The direct location of the application's web root in the server, only used if using a modern non-webroot template
	 */
	coldbox.system.testing.VirtualApp function init( string appMapping, string configPath, string webMapping ) {}
	/**
	 * Startup a virtual ColdBox application for integration testing purposes.
	 *
	 * @force Force the startup of the application even if found. Default is false
	 *
	 * @return The loaded Application controller
	 */
	function startup( boolean force ) {}
	/**
	 * Restart the virtual app
	 */
	function restart() {}
	/**
	 * Verifies if the ColdBox application is in application scope and running
	 */
	boolean function isRunning() {}
	/**
	 * Get the running application controller. Null if not in scope!
	 */
	function getController() {}
	/**
	 * Shuts down a virtual ColdBox application.
	 * It expects the <pre>cbController</pre> to be the app by convention.
	 *
	 * @force If true, it forces all shutdowns this is usually true when doing reinits. Defaults to true for testing.
	 */
	function shutdown( boolean force ) {}
}
