// Generated by cmd/cfstubgen from https://github.com/coldbox-modules/cborm@3cd94ac1b256 models/resources/BaseHandler.cfc — do not edit.
/**
 * This base handler will inherit from the ColdBox REST Handler but actually implement it
 * for CRUD operations using ORM, cbORM and ColdBox Resources.
 *
 * ## Pre-Requisites
 *
 * - You will be injecting Virtual Entity services
 * - Your entities need to inherit from ActiveEntity
 * - You will need to register the routes using ColdBox <code>resources()</code> method
 * - You will need mementifier active
 *
 * ## Requirements
 *
 * In order for this to work, you will create a handler that inherits from this base
 * and make sure that you inject the appropriate virtual entity service using the variable name: <code>ormService</code>
 * Also populate the variables as needed
 *
 * <pre>
 * component extends="BaseOrmResource"{
 *
 * // Inject the correct virtual entity service to use
 * property name="ormService" inject="RoleService"
 * property name="ormService" inject="entityService:Permission"
 *
 * // The default sorting order string: permission, name, data desc, etc.
 * variables.sortOrder = "";
 * // The name of the entity this resource handler controls. Singular name please.
 * variables.entity 	= "Permission";
 * }
 * </pre>
 *
 * That's it!  All resource methods: <code>index, create, show, update, delete</code> will be implemented for you.
 * You can create more actions or override them as needed.
 */
component extends="coldbox.system.RestHandler" {
	/**
	 * *	DI
	 */
	property name="settings" inject="coldbox:moduleSettings:cborm";
	property name="cbpaginator" inject="Pagination@cbpaginator";
	/**
	 * Display all resource records with pagination
	 *
	 * "description" : "A comma delimitted list of properties to include in the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A comma delimitted list of properties to exclude from the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A boolean indicator if we use default includes/excludes in the memento of the entity or JUST the passed in includes/excludes params.  Default is false",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "boolean", "default" : false }
	 * }
	 * "description" : "The sorting string to use via the orm services",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "The page to retrieve using pagination"
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "integer", "default" : 1 }
	 * }
	 *
	 * @param    -includes {
	 * @param    -excludes {
	 * @param    -ignoreDefaults {
	 * @param    -sortOrder {
	 * @param    -page {
	 * @criteria If you pass a criteria object, then we will use that instead of creating a new one
	 * @results  If you pass in a results struct, it must contain the following keys: { count:numeric, records: array of objects }
	 *
	 * @throws InvalidResultsException - If a results struct is passed and any of the required keys are not found
	 */
	function index( event, rc, prc, criteria, struct results ) {}
	/**
	 * Create a resource
	 *
	 * Composition of ORM relationships is on by default (populate.composeRelationships)
	 * This method calls the `save()` method on the orm service, unless you override it
	 *
	 * "description" : "A comma delimitted list of properties to include in the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A comma delimitted list of properties to exclude from the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A boolean indicator if we use default includes/excludes in the memento of the entity or JUST the passed in includes/excludes params.  Default is false",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "boolean", "default" : false }
	 * }
	 *
	 * @param      -includes {
	 * @param      -excludes {
	 * @param      -ignoreDefaults {
	 * @populate   Population arguments
	 * @validate   Validation arguments
	 * @saveMethod Defaults to `save()`
	 */
	function create( event, rc, prc, struct populate, struct validate, string saveMethod ) {}
	/**
	 * Show a resource using the id
	 *
	 * "description" : "A comma delimitted list of properties to include in the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A comma delimitted list of properties to exclude from the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A boolean indicator if we use default includes/excludes in the memento of the entity or JUST the passed in includes/excludes params.  Default is false",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "boolean", "default" : false }
	 * }
	 * "description" : "The id to use to retrieve the entity."
	 * "in" : "path",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : 0 }
	 * }
	 *
	 * @param -includes {
	 * @param -excludes {
	 * @param -ignoreDefaults {
	 * @param -id {
	 */
	function show( event, rc, prc ) {}
	/**
	 * Update a resource using an id
	 *
	 * "description" : "A comma delimitted list of properties to include in the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A comma delimitted list of properties to exclude from the final representation leveraging the mementifier module. Nested properties are supported.",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : "" }
	 * }
	 * "description" : "A boolean indicator if we use default includes/excludes in the memento of the entity or JUST the passed in includes/excludes params.  Default is false",
	 * "in" : "query",
	 * "required" : false,
	 * "schema" : { "type" : "boolean", "default" : false }
	 * }
	 * "description" : "The id to use to retrieve the entity."
	 * "in" : "path",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : 0 }
	 * }
	 *
	 * @param    -includes {
	 * @param    -excludes {
	 * @param    -ignoreDefaults {
	 * @param    -id {
	 * @populate Population arguments
	 * @validate Validation arguments
	 */
	function update( event, rc, prc, struct populate, struct validate, string saveMethod ) {}
	/**
	 * Delete a resource
	 *
	 * "description" : "The id to use to retrieve the entity."
	 * "in" : "path",
	 * "required" : false,
	 * "schema" : { "type" : "string", "default" : 0 }
	 * }
	 *
	 * @param        -id {
	 * @deleteMethod The method used for deleting, we default to delete()
	 */
	function delete( event, rc, prc, string deleteMethod ) {}
	/**
	 * Calculate the starting offset for the incoming page
	 *
	 * @page The page to lookup on
	 *
	 * @return The page start offset
	 */
	private function getPageOffset( page ) {}
	/**
	 * Get the max number of rows to retrieve according to global settings
	 * or passed in through RC
	 */
	private function getMaxRows( event ) {}
	/**
	 * Coverts a value to the correct javaType for the property passed in.
	 *
	 * @propertyName The property name
	 * @value        The property value
	 */
	private function autoCast( required propertyName, required value ) {}
	/**
	 * Get a brand new criteria builder object
	 *
	 * @useQueryCaching  Activate query caching for the list operations
	 * @queryCacheRegion The query cache region to use, which defaults to criterias.{entityName}
	 * @defaultAsQuery   To return results as queries or array of objects or reports, default is array as results might not match entities precisely
	 *
	 * @return cborm.models.criterion.CriteriaBuilder
	 */
	private cborm.models.criterion.CriteriaBuilder function newCriteria( boolean useQueryCaching, string queryCacheRegion, datasource ) {}
}
