// Generated by cmd/cfstubgen from https://github.com/cfwheels/cfwheels@ef0436596635 wheels/wheelstest/system/Assertion.cfc — do not edit.
/**
 * Copyright Since 2005 TestBox Framework by Luis Majano and Ortus Solutions, Corp
 * www.ortussolutions.com
 * ---
 * This object represents our Assertion style DSL for Unit style testing
 */
component {
	/**
	 * Fail assertion
	 *
	 * @message The message to send in the failure
	 * @detail  The detail to add in the exception
	 */
	function fail( message, detail ) {}
	/**
	 * Skip a Test
	 *
	 * @message The message to send in the skip information dialog
	 * @detail  The detail to add in the exception
	 */
	function skip( message, detail ) {}
	/**
	 * Assert that the passed expression is true
	 *
	 * @expression The expression to test
	 * @message    The message to send in the failure
	 */
	function assert( required boolean expression, message ) {}
	/**
	 * Assert something is true
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isTrue( required boolean actual, message ) {}
	/**
	 * Assert something is false
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isFalse( required boolean actual, message ) {}
	/**
	 * Assert something is equal to each other, no case is required
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isEqual( any expected, any actual, message ) {}
	/**
	 * Assert something is not equal to each other, no case is required
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isNotEqual( any expected, any actual, message ) {}
	/**
	 * Assert an object is the same instance as another object
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isSameInstance( required any expected, required any actual, message ) {}
	/**
	 * Assert an object is not the same instance as another object
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isNotSameInstance( required any expected, required any actual, message ) {}
	/**
	 * Assert strings are equal to each other with case.
	 *
	 * @expected The expected data
	 * @actual   The actual data to test
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isEqualWithCase( string expected, string actual, message ) {}
	/**
	 * Assert something is null
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function null( any actual, message ) {}
	/**
	 * Assert something is not null
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notNull( any actual, message ) {}
	/**
	 * Assert the type of the incoming actual data, it uses the internal ColdFusion isValid() function behind the scenes
	 *
	 * @type    The type to check, valid types are: array, binary, boolean, component, date, time, float, numeric, integer, query, string, struct, url, uuid
	 * @actual  The actual data to check
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function typeOf( required string type, required any actual, message ) {}
	/**
	 * Assert that is NOT a type of the incoming actual data, it uses the internal ColdFusion isValid() function behind the scenes
	 *
	 * @type    The type to check, valid types are: array, binary, boolean, component, date, time, float, numeric, integer, query, string, struct, url, uuid
	 * @actual  The actual data to check
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notTypeOf( required string type, required any actual, message ) {}
	/**
	 * Assert that the actual object is of the expected instance type
	 *
	 * @actual   The actual data to check
	 * @typeName The typename to check
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function instanceOf( required any actual, required string typeName, message ) {}
	/**
	 * Assert that the actual object is NOT of the expected instance type
	 *
	 * @actual   The actual data to check
	 * @typeName The typename to check
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notInstanceOf( required any actual, required string typeName, message ) {}
	/**
	 * Assert that the actual data matches the incoming regular expression with no case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function match( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data matches the incoming regular expression with case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function matchWithCase( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data does NOT match the incoming regular expression with case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notMatchWithCase( required string actual, required string regex, message ) {}
	/**
	 * Assert that the actual data does NOT match the incoming regular expression with no case sensitivity
	 *
	 * @actual  The actual data to check
	 * @regex   The regex to check with
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notMatch( required string actual, required string regex, message ) {}
	/**
	 * Assert that a given key exists in the passed in struct/object
	 *
	 * @target        The target object/struct
	 * @key           The key to check for existence
	 * @message       The message to send in the failure
	 * @caseSensitive If the key check is case sensitive
	 */
	wheels.wheelstest.system.Assertion function key( required any target, required string key, message, boolean caseSensitive ) {}
	/**
	 * Assert that a given key DOES NOT exist in the passed in struct/object
	 *
	 * @target        The target object/struct
	 * @key           The key to check for existence
	 * @message       The message to send in the failure
	 * @caseSensitive If the key check is case sensitive
	 */
	wheels.wheelstest.system.Assertion function notKey( required any target, required string key, message, boolean caseSensitive ) {}
	/**
	 * Assert that a given key exists in the passed in struct by searching the entire nested structure
	 *
	 * @target  The target object/struct
	 * @key     The key to check for existence anywhere in the nested structure
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function deepKey( required struct target, required string key, message ) {}
	/**
	 * Assert that a given key DOES NOT exists in the passed in struct by searching the entire nested structure
	 *
	 * @target  The target object/struct
	 * @key     The key to check for existence anywhere in the nested structure
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notDeepKey( required struct target, required string key, message ) {}
	/**
	 * Assert the size of a given string, array, structure or query
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @length  The length to check
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function lengthOf( required any target, required string length, message ) {}
	/**
	 * Assert the size of a given string, array, structure or query
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @length  The length to check
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notLengthOf( required any target, required string length, message ) {}
	/**
	 * Assert that a a given string, array, structure or query is empty
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isEmpty( required any target, message ) {}
	/**
	 * Assert that a a given string, array, structure or query is not empty
	 *
	 * @target  The target object to check the length for, this can be a string, array, structure or query
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isNotEmpty( required any target, message ) {}
	/**
	 * Assert that the passed in function will throw an exception
	 *
	 * @target  The target function to execute and check for exceptions
	 * @type    Match this type with the exception thrown
	 * @regex   Match this regex against the message + detail of the exception
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function throws( required any target, type, regex, message ) {}
	/**
	 * Assert that the passed in function will NOT throw an exception, an exception of a specified type or exception message regex
	 *
	 * @target  The target function to execute and check for exceptions
	 * @type    Match this type with the exception thrown
	 * @regex   Match this regex against the message+detail of the exception
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notThrows( required any target, type, regex, message ) {}
	/**
	 * Assert that the passed in actual number or date is expected to be close to it within +/- a passed delta and optional datepart
	 *
	 * @expected The expected number or date
	 * @actual   The actual number or date
	 * @delta    The +/- delta to range it
	 * @datepart If passed in values are dates, then you can use the datepart to evaluate it
	 * @message  The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function closeTo( required any expected, required any actual, required any delta, datePart, message ) {}
	/**
	 * Assert that the passed in actual number or date is between the passed in min and max values
	 *
	 * @actual  The actual number or date to evaluate
	 * @min     The expected min number or date
	 * @max     The expected max number or date
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function between( required any actual, required any min, required any max, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with no case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function includes( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function includesWithCase( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument does not exist in the incoming string or array with case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notIncludesWithCase( required any target, required any needle, message ) {}
	/**
	 * Assert that the given "needle" argument exists in the incoming string or array with no case-sensitivity
	 *
	 * @target  The target object to check if the incoming needle exists in. This can be a string or array
	 * @needle  The substring to find in a string or the value to find in an array
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notIncludes( required any target, required any needle, message ) {}
	/**
	 * Assert that the given target string starts with the given needle string with no case-sensitivity
	 *
	 * $assert.startsWith( "hello world", "hello" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function startsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't start with the given needle string with no case-sensitivity
	 *
	 * $assert.notStartsWith( "hello world", "hello" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notStartsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string starts with the given needle string with case-sensitivity
	 *
	 * $assert.startsWith( "hello world", "hello" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function startsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't start with the given needle string with case-sensitivity
	 *
	 * $assert.notStartsWith( "hello world", "hello" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notStartsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string ends with the given needle string with no case-sensitivity
	 *
	 * $assert.endsWith( "hello world", "World" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function endsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't end with the given needle string with no case-sensitivity
	 *
	 * $assert.notEndsWith( "hello world", "peace" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notEndsWith( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string ends with the given needle string with case-sensitivity
	 *
	 * $assert.endsWith( "hello world", "ld" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function endsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the given target string doesn't end with the given needle string with case-sensitivity
	 *
	 * $assert.notEndsWith( "hello world", "ld" );
	 *
	 * @target  The target string to check
	 * @needle  The starts with string
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function notEndsWithCase( required string target, required string needle, message ) {}
	/**
	 * Assert that the actual value is greater than the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isGT( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is greater than or equal the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isGTE( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is less than the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isLT( required any actual, required any target, message ) {}
	/**
	 * Assert that the actual value is less than or equal the target value
	 *
	 * @actual  The actual value
	 * @target  The target value
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isLTE( required any actual, required any target, message ) {}
	/**
	 * Get a string name representation of an incoming object.
	 */
	function getStringName( obj ) {}
	/**
	 * Assert something is JSON
	 *
	 * @actual  The actual data to test
	 * @message The message to send in the failure
	 */
	wheels.wheelstest.system.Assertion function isJSON( required any actual, message ) {}
	/**
	 * PRIVATE Methods **********************************
	 */
	private boolean function equalize( any expected, any actual ) {}
	private boolean function $equalizeSimpleValues( any expected, any actual ) {}
	private boolean function $equalizeQueries( any expected, any actual ) {}
	private boolean function $equalizeArrays( any expected, any actual ) {}
	private boolean function $equalizeStructs( any expected, any actual ) {}
	private boolean function $equalizeFunctions( any expected, any actual ) {}
	private boolean function $equalizeXml( any expected, any actual ) {}
	/**
	 * Returns the length of the target based on its type
	 *
	 * @target The target to get the length of
	 */
	private function getTargetLength( required any target ) {}
	/**
	 * Get the identity hash code for the target.
	 *
	 * @target The target to get the hash code for
	 */
	private function getIdentityHashCode( required any target ) {}
	/**
	 * Normalize the target to a struct if possible.
	 *
	 * @target The target to normalize
	 *
	 * @throws InvalidTargetType - If we can normalize it to a struct
	 */
	private function normalizeToStruct( any target ) {}
	private string function limitString( required string str, required numeric limit, string end ) {}
}
