// Generated by cmd/cfstubgen from https://github.com/Ortus-Solutions/ContentBox@312f1823ad44 contentbox/models/system/SettingService.cfc — do not edit.
/**
 * ContentBox - A Modular Content Platform
 * Copyright since 2012 by Ortus Solutions, Corp
 * www.ortussolutions.com/products/contentbox
 * ---
 * Setting Service for ContentBox apps.
 * All settings are cached as a struct constructed using the following format:
 * - global : { name : value } // global settings
 * - sites : {
 * slug : { name : value }
 * }
 */
component extends="cborm.models.VirtualEntityService" {
	property name="siteService" inject="siteService@contentbox";
	property name="cachebox" inject="cachebox";
	property name="moduleSettings" inject="coldbox:setting:modules";
	property name="appName" inject="coldbox:setting:appName";
	property name="contentboxSettings" inject="coldbox:moduleSettings:contentbox";
	/**
	 * The cache provider name to use for settings caching. Defaults to 'template' cache.
	 * This can also be set in the global ContentBox settings page to any CacheBox cache.
	 */
	property name="cacheProviderName" default="template";
	/**
	 * Bit that detects if CB has been installed or not
	 */
	property name="CBReadyFlag" default="false" type="boolean";
	variables.siteService = new contentbox.models.system.SiteService();
	/**
	 * Constructor
	 */
	contentbox.models.system.SettingService function init() {}
	/**
	 * This method will go over all system settings and make sure that there are no missing default core settings.
	 * If they are, we will create the core settings with the appropriate defaults: this.DEFAULTS
	 */
	contentbox.models.system.SettingService function preFlightCheck() {}
	/**
	 * Get a collection (struct) of settings that represent the defaults for a site in ContentBox
	 */
	struct function getSiteSettingDefaults() {}
	/**
	 * The static key used for caching all the settings of this installation
	 */
	string function getSettingsCacheKey() {}
	/**
	 * Check if the installer is present
	 */
	boolean function isInstallationPresent() {}
	/**
	 * Delete the installer module
	 */
	boolean function deleteInstaller() {}
	/**
	 * Check if contentbox has been installed by checking if there are no settings and no cb_active ONLY
	 * If the query comes back with active, it will not run it again.
	 */
	boolean function isCBReady() {}
	/**
	 * Mark cb as ready to serve
	 */
	contentbox.models.system.SettingService function activateCB() {}
	/**
	 * Get a global setting
	 *
	 * @name         The name of the seting
	 * @defaultValue The default value if setting not found.
	 *
	 * @return The setting value or default value if not found
	 *
	 * @throws SettingNotFoundException
	 */
	function getSetting( required name, defaultValue ) {}
	/**
	 * Get a site setting
	 *
	 * @siteSlug     The site to get the setting from
	 * @name         The name of the seting
	 * @defaultValue The default value if setting not found.
	 *
	 * @return The setting value or default value if not found
	 *
	 * @throws SettingNotFoundException
	 */
	function getSiteSetting( required siteSlug, required name, defaultValue ) {}
	/**
	 * Get all global settings
	 *
	 * @force To force clear the cache
	 */
	struct function getAllSettings( boolean force ) {}
	/**
	 * Get all site settings
	 *
	 * @slug  The site slug to use to retrieve the settings
	 * @force To force clear the cache
	 */
	struct function getAllSiteSettings( required siteSlug, boolean force ) {}
	/**
	 * Get all the default site settings
	 *
	 * @force To force clear the cache
	 */
	struct function getDefaultSiteSettings( boolean force ) {}
	/**
	 * Get the entire settings container from cache or build it out.
	 *
	 * @force Force build
	 */
	struct function getSettingsContainer( boolean force ) {}
	/**
	 * Try to find a setting object by site and name
	 *
	 * @site The site object, this can be null
	 * @name The name of the setting
	 *
	 * @return The setting object or null
	 */
	function findSiteSetting( required site, required name ) {}
	/**
	 * Build out a settings container by global and sites.
	 *
	 * @return struct of { global : {}, sites : { slug : {} } }
	 */
	struct function buildSettingsContainer() {}
	/**
	 * This will store the incoming structure as the settings in cache.
	 * Usually this method is used for major overrides.
	 */
	contentbox.models.system.SettingService function storeSettings( struct settings ) {}
	/**
	 * flush settings cache for current multi-tenant host
	 */
	contentbox.models.system.SettingService function flushSettingsCache() {}
	/**
	 * Bulk saving of options using a memento structure of options
	 * This is usually done from the settings display manager
	 *
	 * @memento The struct of settings
	 * @site    Optional site to attach the settings to
	 *
	 * @return SettingService
	 */
	contentbox.models.system.SettingService function bulkSave( struct memento, site ) {}
	/**
	 * Build file browser settings structure so you can execute multiple containers
	 *
	 * @return struct
	 */
	struct function buildFileBrowserSettings() {}
	/**
	 * Setting search with filters
	 *
	 * @search    The search term for the name
	 * @max       The max records
	 * @offset    The offset to tuse
	 * @sortOrder The sort order
	 * @siteID    The site id to filter on
	 *
	 * @return struct of { count, settings }
	 */
	struct function search( search, max, offset, sortOrder, siteID ) {}
	/**
	 * Get all data prepared for export
	 */
	array function getAllForExport() {}
	/**
	 * Import data from a ContentBox JSON file. Returns the import log
	 *
	 * @importFile The json file to import
	 * @override   Override content if found in the database, defaults to false
	 *
	 * @return The console log of the import
	 *
	 * @throws InvalidImportFormat
	 */
	string function importFromFile( required importFile, boolean override ) {}
	/**
	 * Import data from an array of structures or a single structure of data
	 *
	 * @importData A struct or array of data to import
	 * @override   Override content if found in the database, defaults to false
	 * @importLog  The import log buffer
	 *
	 * @return The console log of the import
	 *
	 * @throws InvalidImportFormat
	 */
	string function importFromData( required importData, boolean override, importLog ) {}
	/**
	 * Get the cache provider object to be used for settings
	 *
	 * @return coldbox.system.cache.ICacheProvider
	 */
	function getSettingsCacheProvider() {}
	/**
	 * Load up config overrides
	 */
	function loadConfigOverrides() {}
	/**
	 * Load up java environment overrides for ContentBox settings
	 * The pattern to look is `contentbox.{site}.{setting}`
	 * Example: contentbox.default.cb_media_directoryRoot
	 */
	function loadEnvironmentOverrides() {}
	/**
	 * Load the cache provider name from DB or default value
	 */
	private contentbox.models.system.SettingService function loadCacheProviderName() {}
}
